// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { CreateCargarubrosido, Cargarubrosido, CargarubrosidoFilter, CargarubrosidoPageResult, UpdateCargarubrosido } from '../model/Cargarubrosido';

/**
 * Puerto de entrada: cargaRubrosIDO.zul
 * Define los casos de uso del dominio para esta funcionalidad.
 */
export interface CargarubrosidoInputPort {
  /**
   * Obtiene una lista paginada de cargas masivas de rubros IDO
   */
  getCargasMasivas(filter: CargarubrosidoFilter): Promise<CargarubrosidoPageResult>;

  /**
   * Obtiene una carga masiva por su ID
   */
  getCargaMasivaById(id: number): Promise<Cargarubrosido>;

  /**
   * Inicia una nueva carga masiva de rubros IDO
   */
  createCargaMasiva(cargaMasiva: CreateCargarubrosido): Promise<Cargarubrosido>;

  /**
   * Actualiza una carga masiva existente
   */
  updateCargaMasiva(id: number, cargaMasiva: UpdateCargarubrosido): Promise<Cargarubrosido>;

  /**
   * Elimina una carga masiva por su ID
   */
  deleteCargaMasiva(id: number): Promise<void>;

  /**
   * Aprueba una carga masiva pendiente
   */
  aprobarCargaMasiva(id: number): Promise<Cargarubrosido>;
}