// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { CreateConsultarubrosidolist, Consultarubrosidolist, ConsultarubrosidolistFilter, ConsultarubrosidolistPageResult, UpdateConsultarubrosidolist } from '../model/Consultarubrosidolist';

/**
 * Puerto de entrada: consultaRubrosIdoList.zul
 * Define los casos de uso del dominio para esta funcionalidad.
 */
export interface ConsultarubrosidolistInputPort {
  /**
   * Obtiene una lista paginada de resultados de consulta de rubros IDO
   */
  consultarRubrosIDO(filter: ConsultarubrosidolistFilter): Promise<ConsultarubrosidolistPageResult>;

  /**
   * Obtiene un resultado de consulta por su ID
   */
  getConsultaById(id: number): Promise<Consultarubrosidolist>;

  /**
   * Crea un nuevo registro de consulta
   */
  createConsulta(consulta: CreateConsultarubrosidolist): Promise<Consultarubrosidolist>;

  /**
   * Actualiza un registro de consulta existente
   */
  updateConsulta(id: number, consulta: UpdateConsultarubrosidolist): Promise<Consultarubrosidolist>;

  /**
   * Elimina un registro de consulta por su ID
   */
  deleteConsulta(id: number): Promise<void>;

  /**
   * Cambia el estado de un rubro IDO
   */
  cambiarEstado(id: number, nuevoEstado: string): Promise<Consultarubrosidolist>;

  /**
   * Exporta los resultados de la consulta
   */
  exportarConsulta(filter: ConsultarubrosidolistFilter): Promise<Blob>;
}