// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { CreateRubrosidomain, Rubrosidomain, RubrosidomainFilter, RubrosidomainPageResult, UpdateRubrosidomain } from '../model/Rubrosidomain';

/**
 * Puerto de entrada: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Define los casos de uso del dominio para esta funcionalidad.
 */
export interface RubrosidomainInputPort {
  /**
   * Obtiene una lista paginada de rubros IDO
   */
  getRubrosIDO(filter: RubrosidomainFilter): Promise<RubrosidomainPageResult>;

  /**
   * Obtiene un rubro IDO por su ID
   */
  getRubroIDOById(id: number): Promise<Rubrosidomain>;

  /**
   * Crea un nuevo rubro IDO
   */
  createRubroIDO(rubroIDO: CreateRubrosidomain): Promise<Rubrosidomain>;

  /**
   * Actualiza un rubro IDO existente
   */
  updateRubroIDO(id: number, rubroIDO: UpdateRubrosidomain): Promise<Rubrosidomain>;

  /**
   * Elimina un rubro IDO por su ID
   */
  deleteRubroIDO(id: number): Promise<void>;
}