// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { CreateRubrosidomainRubrosidolistRubrosidodetail, RubrosidomainRubrosidolistRubrosidodetail, RubrosidomainRubrosidolistRubrosidodetailFilter, RubrosidomainRubrosidolistRubrosidodetailPageResult, UpdateRubrosidomainRubrosidolistRubrosidodetail } from '../model/RubrosidomainRubrosidolistRubrosidodetail';

/**
 * Puerto de entrada: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Define los casos de uso del dominio para esta funcionalidad.
 */
export interface RubrosidomainRubrosidolistRubrosidodetailInputPort {
  /**
   * Obtiene una lista paginada de rubros IDO
   */
  getRubrosIDO(filter: RubrosidomainRubrosidolistRubrosidodetailFilter): Promise<RubrosidomainRubrosidolistRubrosidodetailPageResult>;

  /**
   * Obtiene un rubro IDO por su ID
   */
  getRubroIDOById(id: number): Promise<RubrosidomainRubrosidolistRubrosidodetail>;

  /**
   * Crea un nuevo rubro IDO
   */
  createRubroIDO(rubroIDO: CreateRubrosidomainRubrosidolistRubrosidodetail): Promise<RubrosidomainRubrosidolistRubrosidodetail>;

  /**
   * Actualiza un rubro IDO existente
   */
  updateRubroIDO(id: number, rubroIDO: UpdateRubrosidomainRubrosidolistRubrosidodetail): Promise<RubrosidomainRubrosidolistRubrosidodetail>;

  /**
   * Elimina un rubro IDO por su ID
   */
  deleteRubroIDO(id: number): Promise<void>;
}