// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { CreateRubrosxprocesodialog, Rubrosxprocesodialog, RubrosxprocesodialogFilter, RubrosxprocesodialogPageResult, UpdateRubrosxprocesodialog } from '../model/Rubrosxprocesodialog';

/**
 * Puerto de entrada: rubrosxprocesoDialog.zul
 * Define los casos de uso del dominio para esta funcionalidad.
 */
export interface RubrosxprocesodialogInputPort {
  /**
   * Obtiene una lista paginada de asociaciones rubro-proceso
   */
  getRubrosxprocesos(filter: RubrosxprocesodialogFilter): Promise<RubrosxprocesodialogPageResult>;

  /**
   * Obtiene una asociación rubro-proceso por su ID
   */
  getRubroxprocesoById(id: number): Promise<Rubrosxprocesodialog>;

  /**
   * Crea una nueva asociación rubro-proceso
   */
  createRubroxproceso(rubroProceso: CreateRubrosxprocesodialog): Promise<Rubrosxprocesodialog>;

  /**
   * Actualiza una asociación rubro-proceso existente
   */
  updateRubroxproceso(id: number, rubroProceso: UpdateRubrosxprocesodialog): Promise<Rubrosxprocesodialog>;

  /**
   * Elimina una asociación rubro-proceso por su ID
   */
  deleteRubroxproceso(id: number): Promise<void>;
}