// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { CreateRubrosidocargaxproceso, Rubrosidocargaxproceso, RubrosidocargaxprocesoFilter, RubrosidocargaxprocesoPageResult, UpdateRubrosidocargaxproceso } from '../model/Rubrosidocargaxproceso';

/**
 * Puerto de entrada: rubrosIDOcargaxProceso.zul
 * Define los casos de uso del dominio para esta funcionalidad.
 */
export interface RubrosidocargaxprocesoInputPort {
  /**
   * Obtiene una lista paginada de ejecuciones de carga por proceso
   */
  getCargasPorProceso(filter: RubrosidocargaxprocesoFilter): Promise<RubrosidocargaxprocesoPageResult>;

  /**
   * Obtiene una carga por proceso por su ID
   */
  getCargaPorProcesoById(id: number): Promise<Rubrosidocargaxproceso>;

  /**
   * Ejecuta una nueva carga de rubros IDO por proceso
   */
  createCargaPorProceso(cargaProceso: CreateRubrosidocargaxproceso): Promise<Rubrosidocargaxproceso>;

  /**
   * Actualiza una carga por proceso existente
   */
  updateCargaPorProceso(id: number, cargaProceso: UpdateRubrosidocargaxproceso): Promise<Rubrosidocargaxproceso>;

  /**
   * Elimina una carga por proceso por su ID
   */
  deleteCargaPorProceso(id: number): Promise<void>;

  /**
   * Ejecuta la carga de rubros IDO para un proceso específico
   */
  ejecutarCargaProceso(procesoId: string): Promise<Rubrosidocargaxproceso>;
}