// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { CreateRubrosRubrosdialog, RubrosRubrosdialog, RubrosRubrosdialogFilter, RubrosRubrosdialogPageResult, UpdateRubrosRubrosdialog } from '../model/RubrosRubrosdialog';

/**
 * Puerto de entrada: rubros.zul / rubrosDialog.zul
 * Define los casos de uso del dominio para esta funcionalidad.
 */
export interface RubrosRubrosdialogInputPort {
  /**
   * Obtiene una lista paginada de rubros
   */
  getRubros(filter: RubrosRubrosdialogFilter): Promise<RubrosRubrosdialogPageResult>;

  /**
   * Obtiene un rubro por su ID
   */
  getRubroById(id: number): Promise<RubrosRubrosdialog>;

  /**
   * Crea un nuevo rubro
   */
  createRubro(rubro: CreateRubrosRubrosdialog): Promise<RubrosRubrosdialog>;

  /**
   * Actualiza un rubro existente
   */
  updateRubro(id: number, rubro: UpdateRubrosRubrosdialog): Promise<RubrosRubrosdialog>;

  /**
   * Elimina un rubro por su ID
   */
  deleteRubro(id: number): Promise<void>;
}