// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

export interface RubrosModuleConfig {
  moduleName: string;
  route: string;
}

export const RubrosConfig: RubrosModuleConfig = {
  moduleName: 'Rubros',
  route: '/rubros',
};
