/**
 * DTOs para funcionalidad: cargaRubrosIDO.zul (cargaRubrosIDO)
 * API Endpoints: GET /api/v1/rubros-ido/cargas-masivas, GET /api/v1/rubros-ido/cargas-masivas/{id},
 *                GET /api/v1/rubros-ido/cargas-masivas/{id}/lineas, POST /api/v1/rubros-ido/cargas-masivas,
 *                POST /api/v1/rubros-ido/cargas-masivas/{id}/aprobar, DELETE /api/v1/rubros-ido/cargas-masivas/{id}
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */

// ─── Request DTOs ───

export interface CreateCargarubrosidoRequest {
  archivo: File;  // Binary multipart
  empresaId: number;
  rubroId?: string;
  descripcion?: string;
}

export interface UpdateCargarubrosidoRequest {
  estado?: string;
  descripcion?: string;
}

export interface CargarubrosidoFilterParams {
  page?: number;
  size?: number;
  empresaId?: number;
  rubroId?: string;
  estado?: string;
  sort?: string;
}

// ─── Response DTOs ───

export interface CargarubrosidoResponse {
  id: number;
  nombreArchivo: string;
  fechaCarga: string;
  estado: string;
  usuarioCarga: string;
  numeroRegistros: number;
  numeroErrores: number;
  numeroExitosos: number;
  empresaId?: number;
  procesoId?: string;
  descripcion?: string;
  fechaActualizacion?: string;
}

export interface CargarubrosidoLineaResponse {
  lineaId?: number;
  rubroId: string;
  colaboradorId: number;
  valor?: number;
  estado?: string;
  mensaje?: string;
}

export interface CargarubrosidoListResponse {
  content: CargarubrosidoResponse[];
  totalElements: number;
  totalPages: number;
  number?: number;
  size?: number;
}

export interface CargarubrosidoLineaListResponse {
  content: CargarubrosidoLineaResponse[];
  totalElements: number;
  totalPages: number;
  number?: number;
  size?: number;
}

// ─── Response alias
export type CargaMasivaIDOPageResponseDTO = CargarubrosidoListResponse;
export type CargaMasivaIDOResponseDTO = CargarubrosidoResponse;
export type CargaMasivaIDOLineaPageResponseDTO = CargarubrosidoLineaListResponse;
export type CargaMasivaIDOResultDTO = { id: number; success: boolean; message: string };
export type ProcesoResponseDTO = { success: boolean; message: string };
export type DeleteResponseDTO = { success: boolean; message: string };

// ─── API Error DTO ───

export interface CargarubrosidoErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
