/**
 * DTOs para funcionalidad: clases-rubro
 * API Endpoints:
 *   GET /api/v1/nomina-colaborador/clases-rubro
 *   GET /api/v1/nomina-colaborador/clases-rubro/{claseId}
 * Generated by migration-flow | GeneratedAt: 2026-04-09
 */

export interface ClasesrubroFilterParams {
  page?: number;
  size?: number;
  search?: string;
}

export interface ClasesrubroResponse {
  vidclase: string;
  vclase: string;
  cocultar?: string;
  vnivel?: string;
  videxterno?: string;
  vidclasepadre?: string;
  creportenomina?: string;
  casignarubro?: string;
}

export interface ClasesrubroListResponse {
  content: ClasesrubroResponse[];
  totalElements: number;
  totalPages: number;
  number?: number;
  size?: number;
}

export type ClaseRubroListDTO = ClasesrubroListResponse;
export type ClaseRubroResumenDTO = ClasesrubroResponse;

export interface ClasesrubroErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
