/**
 * DTOs para funcionalidad: consultaRubrosIdoList.zul (consultaRubrosIdoList)
 * API Endpoints: GET /api/v1/rubros-ido/consulta, GET /api/v1/rubros-ido/consulta/{id},
 *                POST /api/v1/rubros-ido/consulta/exportar, PUT /api/v1/rubros-ido/consulta/{id}/estado,
 *                DELETE /api/v1/rubros-ido/consulta/{id}
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */

// ─── Request DTOs ───

export interface CreateConsultarubrosidolistRequest {
  rubroId?: string;
  colaboradorId?: number;
  empresaId?: number;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
}

export interface UpdateConsultarubrosidolistRequest {
  estado?: string;
}

export interface ExportarConsultaIDORequest {
  rubroId?: string;
  colaboradorId?: number;
  empresaId?: number;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
  formato?: string;  // 'CSV' | 'XLSX' | 'PDF'
}

export interface CambiarEstadoIDORequest {
  estado: string;
}

export interface ConsultarubrosidolistFilterParams {
  page?: number;
  size?: number;
  rubroId?: string;
  colaboradorId?: number;
  empresaId?: number;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
  localidadId?: number;
  centroCostoId?: number;
}

// ─── Response DTOs ───

export interface ConsultarubrosidolistResponse {
  id: number;
  rubroId: string;
  colaboradorId: number;
  tipoComportamiento: number;
  valor01: number;
  empresaId: number;
  estado: string;
  fechaDesde: string;
  fechaHasta?: string;
  nombreColaborador?: string;
  nombreRubro?: string;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export interface ConsultarubrosidolistListResponse {
  content: ConsultarubrosidolistResponse[];
  totalElements: number;
  totalPages: number;
  number?: number;
  size?: number;
}

export interface ExportarResponseDTO {
  success: boolean;
  archivoUrl?: string;
  message?: string;
}

// ─── Response alias
export type ConsultaRubroIDOPageResponseDTO = ConsultarubrosidolistListResponse;
export type RubroIDOResponseDTO = ConsultarubrosidolistResponse;
export type DeleteResponseDTO = { success: boolean; message: string };

// ─── API Error DTO ───

export interface ConsultarubrosidolistErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
