/**
 * DTOs para funcionalidad: rubrosxprocesoDialog.zul (rubrosxprocesoDialog)
 * API Endpoints: GET /api/v1/rubros-proceso, GET /api/v1/rubros-proceso/{id},
 *                POST /api/v1/rubros-proceso, PUT /api/v1/rubros-proceso/{id},
 *                DELETE /api/v1/rubros-proceso/{id}
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */

// ─── Request DTOs ───

export interface CreateRubrosxprocesodialogRequest {
  rubroId: string;
  procesoId: number;
  secuencia?: number;
  frecuenciaEjecucion?: string;
  procedimientoCalculo?: string;
  ambitoEjecucion?: string;
  insertaEnLote?: string;
  validaPlantillaContable?: string;
  estado?: string;
  activo?: boolean;
}

export interface UpdateRubrosxprocesodialogRequest {
  secuencia?: number;
  frecuenciaEjecucion?: string;
  procedimientoCalculo?: string;
  ambitoEjecucion?: string;
  insertaEnLote?: string;
  validaPlantillaContable?: string;
  estado?: string;
  activo?: boolean;
}

export interface RubrosxprocesodialogFilterParams {
  page?: number;
  size?: number;
  rubroId?: string;
  procesoId?: number;
}

// ─── Response DTOs ───

export interface RubrosxprocesodialogResponse {
  id: number;
  rubroId: string;
  rubroNombre?: string;
  procesoId: number;
  procesoNombre?: string;
  secuencia?: number;
  frecuenciaEjecucion?: string;
  procedimientoCalculo?: string;
  ambitoEjecucion?: string;
  insertaEnLote?: string;
  validaPlantillaContable?: string;
  estado?: string;
  usuarioIngreso?: string;
  fechaIngreso?: string;
  usuarioModificacion?: string;
  fechaModificacion?: string;
  activo?: boolean;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export interface RubrosxprocesodialogListResponse {
  content: RubrosxprocesodialogResponse[];
  totalElements: number;
  totalPages: number;
  number?: number;
  size?: number;
}

// ─── Response alias for pagination
export type RubroProcesoPageResponseDTO = RubrosxprocesodialogListResponse;
export type RubroProcesoResponseDTO = RubrosxprocesodialogResponse;
export type DeleteResponseDTO = { success: boolean; message: string };

// ─── API Error DTO ───

export interface RubrosxprocesodialogErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
