/**
 * DTOs para funcionalidad: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * API Endpoints: GET /api/v1/rubros-ido, GET /api/v1/rubros-ido/{id},
 *                POST /api/v1/rubros-ido, PUT /api/v1/rubros-ido/{id},
 *                DELETE /api/v1/rubros-ido/{id}
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */

// ─── Request DTOs ───

export interface CreateRubrosidomainRubrosidolistRubrosidodetailRequest {
  rubroId: string;
  colaboradorId: number;
  empresaId: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
}

export interface UpdateRubrosidomainRubrosidolistRubrosidodetailRequest {
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  estado?: string;
  fechaHasta?: string;
}

export interface RubrosidomainRubrosidolistRubrosidodetailFilterParams {
  page?: number;
  size?: number;
  rubroId?: string;
  colaboradorId?: number;
  empresaId?: number;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
}

// ─── Response DTOs ───

export interface RubrosidomainRubrosidolistRubrosidodetailResponse {
  id: number;
  rubroId: string;
  colaboradorId: number;
  empresaId: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
  nombreColaborador?: string;
  nombreRubro?: string;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export interface RubrosidomainRubrosidolistRubrosidodetailListResponse {
  content: RubrosidomainRubrosidolistRubrosidodetailResponse[];
  totalElements: number;
  totalPages: number;
  number?: number;
  size?: number;
}

// ─── Response alias for pagination
export type RubroIDOPageResponseDTO = RubrosidomainRubrosidolistRubrosidodetailListResponse;
export type RubroIDOResponseDTO = RubrosidomainRubrosidolistRubrosidodetailResponse;
export type DeleteResponseDTO = { success: boolean; message: string };

// ─── API Error DTO ───

export interface RubrosidomainRubrosidolistRubrosidodetailErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
