/**
 * DTOs para funcionalidad: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * API Endpoints: GET /api/v1/rubros-ido, GET /api/v1/rubros-ido/{id},
 *                POST /api/v1/rubros-ido, PUT /api/v1/rubros-ido/{id},
 *                DELETE /api/v1/rubros-ido/{id}
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */

// ─── Request DTOs ───

export interface CreateRubrosidomainRequest {
  dfechapagocaja?: string;
  rubroId: string;
  colaboradorId: number;
  empresaId: number;
  centroCostoId?: number;
  localidadId?: number;
  neroId?: number;
  rolId?: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  cartaImpresion?: number;
  flagEnvio?: number;
  generarCarta?: number;
  estadoCaja?: string;
  usuarioCaja?: string;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
}

export interface UpdateRubrosidomainRequest {
  dfechapagocaja?: string;
  rubroId?: string;
  colaboradorId?: number;
  empresaId?: number;
  centroCostoId?: number;
  localidadId?: number;
  neroId?: number;
  rolId?: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  cartaImpresion?: number;
  flagEnvio?: number;
  generarCarta?: number;
  estadoCaja?: string;
  usuarioCaja?: string;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
}

export interface RubrosidomainFilterParams {
  page?: number;
  size?: number;
  rubroId?: string;
  colaboradorId?: number;
  empresaId?: number;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
}

// ─── Response DTOs ───

export interface RubrosidomainResponse {
  id: number;
  dfechapagocaja?: string;
  rubroId: string;
  colaboradorId: number;
  empresaId: number;
  centroCostoId?: number;
  localidadId?: number;
  neroId?: number;
  rolId?: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  cartaImpresion?: number;
  flagEnvio?: number;
  generarCarta?: number;
  estadoCaja?: string;
  usuarioCaja?: string;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
  nombreColaborador?: string;
  nombreRubro?: string;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export interface RubrosidomainListResponse {
  content: RubrosidomainResponse[];
  totalElements: number;
  totalPages: number;
  number?: number;
  size?: number;
}

// ─── Response alias for pagination
export type RubroIDOPageResponseDTO = RubrosidomainListResponse;
export type RubroIDOResponseDTO = RubrosidomainResponse;
export type DeleteResponseDTO = { success: boolean; message: string };

// ─── API Error DTO ───

export interface RubrosidomainErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
