/**
 * DTOs para funcionalidad: rubrosIDOcargaxProceso.zul (rubrosIDOcargaxProceso)
 * API Endpoints: GET /api/v1/rubros-ido/cargar-proceso, GET /api/v1/rubros-ido/cargar-proceso/{id},
 *                POST /api/v1/rubros-ido/cargar-proceso, PUT /api/v1/rubros-ido/cargar-proceso/{id},
 *                DELETE /api/v1/rubros-ido/cargar-proceso/{id}
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */

// ─── Request DTOs ───

export interface CreateRubrosidocargaxprocesoRequest {
  iidempresa: number;
  vidrubro: string;
  accion: string;
  fechaAplica: string;
  ambito?: string;
  iidrubrosIdo?: number;
  procesoId?: number;
  descripcion?: string;
}

export interface UpdateRubrosidocargaxprocesoRequest {
  accion?: string;
  fechaAplica?: string;
  ambito?: string;
  estado?: string;
}

export interface RubrosidocargaxprocesoFilterParams {
  page?: number;
  size?: number;
  empresaId?: number;
  rubroId?: string;
  estado?: string;
}

// ─── Response DTOs ───

export interface RubrosidocargaxprocesoResponse {
  id: number;
  iidrubrosIdocp?: number;
  iidrubrosIdo?: number;
  iidempresa?: number;
  vidrubro?: string;
  vidambito?: string;
  dfechaaplica?: string;
  usuarioingresoAu?: string;
  empresa?: string;
  fechaCarga?: string;
  cargadoPor?: string;
  registrosProcesados?: number;
  mensaje?: string;
  procesoId: string;
  fechaEjecucion: string;
  estado: string;
  numeroRegistrosCargados: number;
  numeroErrores: number;
  usuarioEjecucion: string;
  empresaId: number;
  descripcion?: string;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export interface RubrosidocargaxprocesoListResponse {
  items: RubrosidocargaxprocesoResponse[];
  total: number;
  totalPages?: number;
  page?: number;
  size?: number;
}

// ─── Response alias
export type CargaProcesoListResponseDTO = RubrosidocargaxprocesoListResponse;
export type CargaProcesoResponseDTO = RubrosidocargaxprocesoResponse;
export type ProcesoResponseDTO = { success?: boolean; message?: string; id?: number; iidrubrosIdocp?: number; registrosProcesados?: number };
export type DeleteResponseDTO = { success: boolean; message: string };

// ─── API Error DTO ───

export interface RubrosidocargaxprocesoErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
