/**
 * DTOs para funcionalidad: rubros.zul / rubrosDialog.zul (rubros_rubrosDialog)
 * API Endpoints: GET /api/v1/rubros, GET /api/v1/rubros/{idRubro}, POST /api/v1/rubros,
 *                PUT /api/v1/rubros/{idRubro}, DELETE /api/v1/rubros/{idRubro}
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */

export type EfectoRubro = "ING" | "EGR" | "NA";

export type AmbitoRubro = "NA" | "IDO" | "PTM";

export interface AprobacionCargoDto {
  iiddimensionesl: number;
  iordenaprobacion: number;
}

// ─── Request DTOs ───

export interface CreateRubrosRubrosdialogRequest {
  idRubro: string;
  nombre: string;
  ambito?: AmbitoRubro;
  efecto?: EfectoRubro;
  observaciones?: string;
  procedimientoCalculo?: string;
  rubroHistorico?: number;
  secuenciaImpresion?: number;
  secuenciaSobregiro?: number;
  aplicaInterfaz?: boolean;
  insertaEnLote?: boolean;
  carta?: string;
  antiguedadMinima?: number;
  numAprobaciones?: number;
  numAprobacionesNoLocales?: number;
  plazoMaximo?: number;
  plazoMinimo?: number;
  montoMaximo?: number;
  verificaEndeudamiento?: boolean;
  acumulable?: boolean;
  vnomenclatura?: string;
  iidempresa?: number;
  cargosQueAplican?: number[];
  rolesQueAplican?: number[];
  cargosQueApruebanAlmacen?: AprobacionCargoDto[];
  cargosQueApruebanOficina?: AprobacionCargoDto[];
}

export interface UpdateRubrosRubrosdialogRequest {
  nombre?: string;
  ambito?: AmbitoRubro;
  efecto?: EfectoRubro;
  observaciones?: string;
  procedimientoCalculo?: string;
  rubroHistorico?: number;
  secuenciaImpresion?: number;
  secuenciaSobregiro?: number;
  aplicaInterfaz?: boolean;
  insertaEnLote?: boolean;
  carta?: string;
  antiguedadMinima?: number;
  numAprobaciones?: number;
  numAprobacionesNoLocales?: number;
  plazoMaximo?: number;
  plazoMinimo?: number;
  montoMaximo?: number;
  verificaEndeudamiento?: boolean;
  acumulable?: boolean;
  vnomenclatura?: string;
  iidempresa?: number;
  cargosQueAplican?: number[];
  rolesQueAplican?: number[];
  cargosQueApruebanAlmacen?: AprobacionCargoDto[];
  cargosQueApruebanOficina?: AprobacionCargoDto[];
}

export interface RubrosRubrosdialogFilterParams {
  page?: number;
  size?: number;
  vidrubro?: string;
  vrubro?: string;
  vobservaciones?: string;
  efecto?: EfectoRubro;
  ambito?: AmbitoRubro;
}

// ─── Response DTOs ───

export interface RubrosRubrosdialogResponse {
  idRubro: string;
  nombre: string;
  ambito?: AmbitoRubro;
  efecto?: EfectoRubro;
  observaciones?: string;
  procedimientoCalculo?: string;
  rubroHistorico?: number;
  secuenciaImpresion?: number;
  secuenciaSobregiro?: number;
  aplicaInterfaz?: boolean;
  insertaEnLote?: boolean;
  carta?: string;
  estado?: string;
  antiguedadMinima?: number;
  numAprobaciones?: number;
  numAprobacionesNoLocales?: number;
  plazoMaximo?: number;
  plazoMinimo?: number;
  montoMaximo?: number;
  verificaEndeudamiento?: boolean;
  usuarioCreacion?: string;
  fechaCreacion?: string;
  usuarioActualizacion?: string;
  fechaActualizacion?: string;
  acumulable?: boolean;
  vnomenclatura?: string;
  iidempresa?: number;
  cargosQueAplican?: number[];
  rolesQueAplican?: number[];
  cargosQueApruebanAlmacen?: AprobacionCargoDto[];
  cargosQueApruebanOficina?: AprobacionCargoDto[];
}

export interface RubrosRubrosdialogListResponse {
  content: RubrosRubrosdialogResponse[];
  totalElements: number;
  totalPages: number;
  number?: number;
  size?: number;
}

// ─── Response alias for page structured responses
export type RubrosRubrosdialogPageResponseDTO = RubrosRubrosdialogListResponse;
export type RubroPageResponseDTO = RubrosRubrosdialogListResponse;
export type DeleteResponseDTO = { success: boolean; message: string };

// ─── API Error DTO ───

export interface RubrosRubrosdialogErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
