// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import React from 'react';
import { Link } from 'react-router-dom';

/**
 * Página de Índice: Módulo Consultas
 * Punto de entrada del módulo - lista todas las funcionalidades disponibles
 */
export const ConsultasIndexPage: React.FC = () => {
  const funcionalidades = [
    {
      name: 'Nómina por Colaborador - Histórico',
      slug: 'nominaxcolablist',
      description: 'Listado histórico de nóminas por colaborador',
      icon: '📋',
    },
    {
      name: 'Nómina Preliquidación',
      slug: 'nominaxcolabprelist',
      description: 'Datos de preliquidación de nóminas',
      icon: '📊',
    },
    {
      name: 'Resumen General de Nómina',
      slug: 'nominaresumengeneral',
      description: 'Resumen consolidado de la nómina',
      icon: '📈',
    },
    {
      name: 'Resumen por Rubro',
      slug: 'nominaresumengralxrubro',
      description: 'Resumen del total de nómina discriminado por rubro',
      icon: '🏷️',
    },
    {
      name: 'Resumen por Clasificación', slug: 'nominaresumengralcxrubro',
      description: 'Resumen del total de nómina discriminado por clasificación de rubro',
      icon: '📑',
    },
    {
      name: 'Comparativo de Nóminas',
      slug: 'comparativonominas',
      description: 'Comparación entre períodos de nómina',
      icon: '🔄',
    },
    {
      name: 'Consulta de Sueldos',
      slug: 'consueldo',
      description: 'Consulta rápida de valores de sueldos',
      icon: '💰',
    },
    {
      name: 'Acumulados',
      slug: 'acumulados',
      description: 'Consulta de valores acumulados',
      icon: '📦',
    },
    {
      name: 'DTOs Compartidos Subrecursos',
      slug: 'dtoscompartidossubrecursos',
      description: 'Datos compartidos de subrecursos',
      icon: '🔗',
    },
  ];

  return (
    <div className="consultas-index-page" data-testid="consultas-index-page">
      <div className="page-header">
        <h1>👤 Módulo Consultas</h1>
        <p>Consulta de nóminas, acumulados y sueldos</p>
      </div>

      <div className="funcionalidades-grid">
        {funcionalidades.map((func) => (
          <div key={func.slug} className="funcionalidad-card" data-testid={`card-${func.slug}`}>
            <div className="card-icon">{func.icon}</div>
            <h3>{func.name}</h3>
            <p>{func.description}</p>
            <Link to={`/consultas/${func.slug}`} className="card-link" data-testid={`link-${func.slug}`}>
              Ir →
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
};
