// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useNominaxcolablist } from '../hooks/useNominaxcolablist';
import { NominaxcolablistList } from '../components/NominaxcolablistList';
import { NominaxcolablistForm } from '../components/NominaxcolablistForm';
import { CreateNominaxcolablistRequest, NominaxcolablistResponse } from '../dto/NominaxcolablistDto';

/**
 * Página principal: Nómina por Colaborador Histórica
 * Container que coordina List + Form
 * Usa: useNominaxcolablist hook
 */
export const NominaxcolablistPage: React.FC = () => {
  const navigate = useNavigate();
  const { items, loading, error, listarNominaHistorico } = useNominaxcolablist();

  const [showForm, setShowForm] = useState(false);
  const [editingItem, setEditingItem] = useState<NominaxcolablistResponse | undefined>(undefined);
  const [ejecucionIdFilter, setEjecucionIdFilter] = useState<number>(0);

  useEffect(() => {
    if (ejecucionIdFilter > 0) {
      listarNominaHistorico({ ejecucionId: ejecucionIdFilter, page: 0, size: 20 });
    }
  }, [ejecucionIdFilter, listarNominaHistorico]);

  const handleCreate = async (data: CreateNominaxcolablistRequest) => {
    // Create logic via service
    setShowForm(false);
    setEditingItem(undefined);
  };

  const handleEdit = (item: NominaxcolablistResponse) => {
    setEditingItem(item);
    setShowForm(true);
  };

  const handleDelete = (ejecucionId: number, colaboradorId: number) => {
    if (window.confirm('¿Está seguro de eliminar este registro?')) {
      // Delete logic via service
      console.log(`Deleting: ${ejecucionId}-${colaboradorId}`);
    }
  };

  const handleSelect = (item: NominaxcolablistResponse) => {
    navigate(`/consultas/nominaxcolablist/${item.ejecucionId}`, { state: { item } });
  };

  const handleCancel = () => {
    setShowForm(false);
    setEditingItem(undefined);
  };

  return (
    <div className="nominaxcolablist-page" data-testid="nominaxcolablist-page">
      <div className="page-header">
        <h1>Nómina por Colaborador - Histórico</h1>
        {!showForm && (
          <button onClick={() => setShowForm(true)} className="btn-primary" data-testid="new-btn">
            + Nuevo
          </button>
        )}
      </div>

      {error && (
        <div className="error-banner" data-testid="error-banner">
          <p>{error}</p>
        </div>
      )}

      {showForm ? (
        <div className="form-section" data-testid="form-section">
          <NominaxcolablistForm
            initialData={editingItem}
            onSubmit={handleCreate}
            onCancel={handleCancel}
            loading={loading}
          />
        </div>
      ) : (
        <>
          <div className="filter-section" data-testid="filter-section">
            <label>Filtrar por Ejecución:</label>
            <input
              type="number"
              value={ejecucionIdFilter}
              onChange={(e) => setEjecucionIdFilter(parseInt(e.target.value) || 0)}
              placeholder="Ingrese ID de ejecución"
              disabled={loading}
              data-testid="ejecucion-filter"
            />
            <button onClick={() => setEjecucionIdFilter(0)} disabled={loading} data-testid="clear-filter-btn">
              Limpiar
            </button>
          </div>

          <NominaxcolablistList
            items={items}
            loading={loading}
            onSelect={handleSelect}
            onEdit={handleEdit}
            onDelete={handleDelete}
          />
        </>
      )}
    </div>
  );
};
