// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useNominaxcolablist } from '../hooks/useNominaxcolablist';
import { NominaxcolablistDetail } from '../components/NominaxcolablistDetail';
import { NominaxcolablistResponse } from '../dto/NominaxcolablistDto';

/**
 * Página de detalle: Detalle de Nómina por Colaborador
 * Muestra un colaborador específico con todos sus datos financieros
 */
export const NominaxcolablistDetailPage: React.FC = () => {
  const { ejecucionId, colaboradorId } = useParams<{ ejecucionId: string; colaboradorId: string }>();
  const navigate = useNavigate();
  const { loading, error, obtenerNominaHistorico, eliminarNominaHistorico } = useNominaxcolablist();

  const [item, setItem] = useState<NominaxcolablistResponse | null>(null);

  useEffect(() => {
    if (ejecucionId && colaboradorId) {
      obtenerNominaHistorico(parseInt(ejecucionId), parseInt(colaboradorId)).then(setItem);
    }
  }, [ejecucionId, colaboradorId, obtenerNominaHistorico]);

  const handleEdit = (itemToEdit: NominaxcolablistResponse) => {
    navigate(`/consultas/nominaxcolablist/${itemToEdit.ejecucionId}/edit`, { state: { item: itemToEdit } });
  };

  const handleDelete = async (ejecucionId: number, colaboradorId: number) => {
    if (window.confirm('¿Está seguro de eliminar este registro?')) {
      await eliminarNominaHistorico(ejecucionId, colaboradorId);
      navigate('/consultas/nominaxcolablist');
    }
  };

  const handleBack = () => {
    navigate(-1);
  };

  if (loading) return <div className="loading">Cargando...</div>;
  if (error) return <div className="error">{error}</div>;
  if (!item) return <div className="not-found">Registro no encontrado</div>;

  return (
    <div className="nominaxcolablist-detail-page" data-testid="nominaxcolablist-detail-page">
      <NominaxcolablistDetail item={item} onEdit={handleEdit} onDelete={handleDelete} onBack={handleBack} />
    </div>
  );
};
