// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useNominaxcolablist } from '../hooks/useNominaxcolablist';
import { NominaxcolablistForm } from '../components/NominaxcolablistForm';
import { CreateNominaxcolablistRequest, NominaxcolablistResponse } from '../dto/NominaxcolablistDto';

/**
 * Página de creación/edición: Nómina por Colaborador
 * Modo: creación (sin parámetros) o edición (con :ejecucionId)
 */
export const NominaxcolablistCreatePage: React.FC = () => {
  const { ejecucionId } = useParams<{ ejecucionId: string }>();
  const navigate = useNavigate();
  const { loading, error, obtenerNominaHistorico } = useNominaxcolablist();

  const [initialData, setInitialData] = useState<NominaxcolablistResponse | undefined>(undefined);
  const isEditMode = !!ejecucionId;

  useEffect(() => {
    if (isEditMode && ejecucionId) {
      obtenerNominaHistorico(parseInt(ejecucionId), 0).then(setInitialData);
    }
  }, [ejecucionId, isEditMode, obtenerNominaHistorico]);

  const handleSubmit = async (data: CreateNominaxcolablistRequest) => {
    // Create/Update logic via service
    navigate('/consultas/nominaxcolablist');
  };

  const handleCancel = () => {
    navigate(-1);
  };

  if (loading) return <div className="loading">Cargando...</div>;
  if (error) return <div className="error">{error}</div>;

  return (
    <div className="nominaxcolablist-create-page" data-testid="nominaxcolablist-create-page">
      <div className="page-header">
        <h1>{isEditMode ? 'Editar' : 'Crear'} Nómina por Colaborador</h1>
      </div>

      <NominaxcolablistForm initialData={initialData} onSubmit={handleSubmit} onCancel={handleCancel} loading={loading} />
    </div>
  );
};
