// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

/**
 * DTOs para funcionalidad: nominaresumenGralCxRubro.zul
 * 5 endpoints REST relacionados
 */

// ─── Request DTOs ───

export interface CreateNominaresumengralcxrubroRequest {
  ejecucionId: number;
  claseId: string;
}

export interface UpdateNominaresumengralcxrubroRequest {
  ejecucionId?: number;
  claseId?: string;
}

export interface NominaresumengralcxrubroFilterParams {
  page?: number;
  size?: number;
  ejecucionId: number;
  empresaId?: number;
  tipo?: string;
  claseId?: string;
}

// ─── Response DTOs ───

export interface NominaresumengralcxrubroResponse {
  ejecucionId: number;
  claseId: string;
  claseNombre?: string;
  nivel?: string;
  clasePadreId?: string;
  ocultar?: string;
  reporteNomina?: string;
  idExterno?: string;
  totalValor?: number;
  cantidadRubros?: number;
  cantidadColaboradores?: number;
  rubros?: any[];
  tipo?: string;
}

export interface NominaresumengralcxrubroListResponse {
  data: NominaresumengralcxrubroResponse[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}

export interface ExportResponseDTO {
  success: boolean;
  archivoUrl?: string;
  totalRegistros?: number;
}

export interface DeleteResponseDTO {
  success: boolean;
  message: string;
}

// ─── API Error DTO ───

export interface NominaresumengralcxrubroErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
