// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

/**
 * DTOs para funcionalidad: nominaxColabPreList.zul / nominaxColabPreDialog.zul
 * 5 endpoints REST relacionados
 * Basados en: av_py_rubroslpretotales_v, av_py_rubroslpre
 */

// ─── Shared Interfaces ───

export interface RubroPreLiquidadoDTO {
  ejecucionId: number;
  colaboradorId: number;
  rubroId: string;
  rubroNombre?: string;
  efecto?: string;
  valorSalida01?: number;
  valorSalida02?: number;
  valorSalida03?: number;
  valorSalida04?: number;
  valorSalida05?: number;
  fechaInicioSalida?: string;
  fechaFinSalida?: string;
  rubrosIdoUplId?: number;
  flagEnvio?: number;
  usuarioIngreso?: string;
  fechaIngreso?: string;
}

export interface TotalesPreDTO {
  totalIngresos: number;
  totalEgresos: number;
  totalNeto: number;
  totalRubros: number;
  totalNoDeducible: number;
}

// ─── Request DTOs ───

export interface CreateNominaxcolabprelistNominaxcolabpredialogRequest {
  ejecucionId: number;
  empresaId?: number;
}

export interface UpdateNominaxcolabprelistNominaxcolabpredialogRequest {
  ejecucionId?: number;
  empresaId?: number;
}

export interface NominaxcolabprelistNominaxcolabpredialogFilterParams {
  page?: number;
  size?: number;
  ejecucionId: number;
  colaboradorId?: number;
  cedula?: string;
  empresaId?: number;
}

// ─── Response DTOs ───

export interface NominaxcolabprelistNominaxcolabpredialogResponse {
  ejecucionId: number;
  colaboradorId: number;
  cedula?: string;
  apellidosNombres?: string;
  empresaId?: number;
  totalIngresos?: number;
  totalEgresos?: number;
  totalNeto?: number;
  totalRubros?: number;
  totalNoDeducible?: number;
}

export interface DetallePreColabResponseDTO {
  ejecucionId: number;
  colaboradorId: number;
  cedula?: string;
  apellidosNombres?: string;
  empresaId?: number;
  sueldo?: number;
  fechaIngreso?: string;
  cargo?: string;
  localidad?: string;
  centroCosto?: string;
  totalesPre?: TotalesPreDTO;
  totalesHis?: TotalesPreDTO;
  rubrosPre?: RubroPreLiquidadoDTO[];
  rubrosHis?: any[];
}

export interface NominaxcolabprelistNominaxcolabpredialogListResponse {
  data: NominaxcolabprelistNominaxcolabpredialogResponse[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}

export interface DeleteResponseDTO {
  success: boolean;
  message: string;
}

// ─── API Error DTO ───

export interface NominaxcolabprelistNominaxcolabpredialogErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
