// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

/**
 * DTOs para funcionalidad: nominaresumenGeneral.zul / ResumenGralNominaDialog.zul
 * 5 endpoints REST relacionados
 */

export interface ClaseRubroResumenDTO {
  claseId: string;
  nombre?: string;
  nivel?: string;
  clasePadreId?: string;
  ocultar?: string;
  idExterno?: string;
  reporteNomina?: string;
  asignaRubro?: string;
  totalValor?: number;
  cantidadRubros?: number;
  cantidadColaboradores?: number;
}

// ─── Request DTOs ───

export interface CreateNominaresumengeneralResumengralnominadialogRequest {
  ejecucionId: number;
  empresaId: number;
  tipo?: string;
}

export interface UpdateNominaresumengeneralResumengralnominadialogRequest {
  ejecucionId?: number;
  empresaId?: number;
}

export interface NominaresumengeneralResumengralnominadialogFilterParams {
  ejecucionId: number;
  empresaId?: number;
  tipo?: string;
}

// ─── Response DTOs ───

export interface NominaresumengeneralResumengralnominadialogResponse {
  ejecucionId: number;
  procesoNombre?: string;
  empresaId?: number;
  empresaNombre?: string;
  tipo?: string;
  totalIngresos?: number;
  totalEgresos?: number;
  totalNeto?: number;
  totalRubros?: number;
  totalNoDeducible?: number;
  totalColaboradores?: number;
  periodo?: string;
  fechaInicio?: string;
  fechaFin?: string;
}

export interface ResumenDetalladoNominaDTO {
  ejecucionId: number;
  procesoId?: number;
  procesoNombre?: string;
  empresaId?: number;
  empresaNombre?: string;
  anio?: number;
  mes?: number;
  fechaInicio?: string;
  fechaFin?: string;
  cerrado?: number;
  totalIngresos?: number;
  totalEgresos?: number;
  totalNeto?: number;
  totalColaboradores?: number;
  clasesRubro?: ClaseRubroResumenDTO[];
}

export interface NominaresumengeneralResumengralnominadialogListResponse {
  data: NominaresumengeneralResumengralnominadialogResponse[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}

export interface ExportResponseDTO {
  success: boolean;
  archivoUrl?: string;
  totalRegistros?: number;
}

export interface DeleteResponseDTO {
  success: boolean;
  message: string;
}

// ─── API Error DTO ───

export interface NominaresumengeneralResumengralnominadialogErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
