// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

/**
 * DTOs para funcionalidad: nominaresumenGralxRubro.zul
 * 5 endpoints REST relacionados
 */

export interface ColaboradorRubroDTO {
  colaboradorId: number;
  cedula?: string;
  apellidosNombres?: string;
  valorSalida01?: number;
  valorSalida02?: number;
  valorSalida03?: number;
  valorSalida04?: number;
  valorSalida05?: number;
  totalValor?: number;
}

// ─── Request DTOs ───

export interface CreateNominaresumengralxrubroRequest {
  ejecucionId: number;
  rubroId: string;
}

export interface UpdateNominaresumengralxrubroRequest {
  ejecucionId?: number;
  rubroId?: string;
}

export interface NominaresumengralxrubroFilterParams {
  page?: number;
  size?: number;
  ejecucionId: number;
  empresaId?: number;
  tipo?: string;
  efecto?: string;
}

// ─── Response DTOs ───

export interface NominaresumengralxrubroResponse {
  ejecucionId: number;
  rubroId: string;
  rubroNombre?: string;
  efecto?: string;
  totalValor01?: number;
  totalValor02?: number;
  totalValor03?: number;
  totalValor04?: number;
  totalValor05?: number;
  cantidadColaboradores?: number;
  tipo?: string;
}

export interface NominaresumengralxrubroListResponse {
  data: NominaresumengralxrubroResponse[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}

export interface ExportResponseDTO {
  success: boolean;
  archivoUrl?: string;
  totalRegistros?: number;
}

export interface DeleteResponseDTO {
  success: boolean;
  message: string;
}

// ─── API Error DTO ───

export interface NominaresumengralxrubroErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
