// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

/**
 * DTOs para funcionalidad: nominaxColabList.zul
 * 5 endpoints REST relacionados
 * Basados en: av_py_rubroslhisttotales_v, av_py_rubroslhis
 */

// ─── Shared Interfaces ───

export interface RubroHistoricoDTO {
  ejecucionId: number;
  colaboradorId: number;
  rubroId: string;
  rubroNombre?: string;
  efecto?: string;
  valorSalida01?: number;
  valorSalida02?: number;
  valorSalida03?: number;
  valorSalida04?: number;
  valorSalida05?: number;
  fechaInicioSalida?: string;
  fechaFinSalida?: string;
  rubrosIdoUplId?: number;
  usuarioIngreso?: string;
  fechaIngreso?: string;
}

// ─── Request DTOs ───

export interface CreateNominaxcolablistRequest {
  ejecucionId: number;
  empresaId?: number;
  formato?: string;
}

export interface UpdateNominaxcolablistRequest {
  ejecucionId?: number;
  empresaId?: number;
}

export interface NominaxcolablistFilterParams {
  page?: number;
  size?: number;
  ejecucionId: number;
  colaboradorId?: number;
  cedula?: string;
  empresaId?: number;
}

// ─── Response DTOs ───

export interface NominaxcolablistResponse {
  ejecucionId: number;
  colaboradorId: number;
  cedula?: string;
  apellidosNombres?: string;
  empresaId?: number;
  totalIngresos?: number;
  totalEgresos?: number;
  totalNeto?: number;
  totalRubros?: number;
  totalNoDeducible?: number;
}

export interface NominaxcolablistListResponse {
  data: NominaxcolablistResponse[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}

export interface ExportResponseDTO {
  success: boolean;
  archivoUrl?: string;
  totalRegistros?: number;
}

export interface DeleteResponseDTO {
  success: boolean;
  message: string;
}

// ─── API Error DTO ───

export interface NominaxcolablistErrorResponse {
  timestamp: string;
  status: number;
  error: string;
  message: string;
  path?: string;
}
