// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27


export interface ProcesosModuleConfig {
  moduleName: string;
  route: string;
  description: string;
  functionalities: string[];
}

export const ProcesosConfig: ProcesosModuleConfig = {
  moduleName: 'Procesos',
  route: '/procesos',
  description: 'Procesos de Nómina',
  functionalities: ['2_procesos_nomina'],
};
