import { CargarubrosidoResponse, CargarubrosidoLineaResponse, CargarubrosidoListResponse, CargarubrosidoLineaListResponse, CreateCargarubrosidoRequest, UpdateCargarubrosidoRequest } from '../../../input/adapter/dto/CargarubrosidoDto';

/**
 * API Mapper: cargaRubrosIDO.zul
 * Transforma las respuestas raw de la API a los DTOs tipados del frontend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class CargarubrosidoApiMapper {

  static toResponse(raw: any): CargarubrosidoResponse {
    return {
      id: raw.id,
      nombreArchivo: raw.nombreArchivo,
      fechaCarga: raw.fechaCarga,
      estado: raw.estado,
      usuarioCarga: raw.usuarioCarga,
      numeroRegistros: raw.numeroRegistros || 0,
      numeroErrores: raw.numeroErrores || 0,
      numeroExitosos: raw.numeroExitosos || 0,
      empresaId: raw.empresaId,
      procesoId: raw.procesoId,
      descripcion: raw.descripcion,
      fechaActualizacion: raw.fechaActualizacion,
    };
  }

  static toLineaResponse(raw: any): CargarubrosidoLineaResponse {
    return {
      lineaId: raw.lineaId,
      rubroId: raw.rubroId,
      colaboradorId: raw.colaboradorId,
      valor: raw.valor,
      estado: raw.estado,
      mensaje: raw.mensaje,
    };
  }

  static toListResponse(raw: any): CargarubrosidoListResponse {
    const data = raw.content || raw.data || raw;
    const items = Array.isArray(data) ? data.map((item: any) => CargarubrosidoApiMapper.toResponse(item)) : [];
    return {
      content: items,
      totalElements: raw.totalElements || raw.total || items.length,
      totalPages: raw.totalPages || Math.ceil((raw.totalElements || items.length) / (raw.size || 10)),
      number: raw.number || raw.page || 0,
      size: raw.size || 10,
    };
  }

  static toLineaListResponse(raw: any): CargarubrosidoLineaListResponse {
    const data = raw.content || raw.data || raw;
    const items = Array.isArray(data) ? data.map((item: any) => CargarubrosidoApiMapper.toLineaResponse(item)) : [];
    return {
      content: items,
      totalElements: raw.totalElements || raw.total || items.length,
      totalPages: raw.totalPages || Math.ceil((raw.totalElements || items.length) / (raw.size || 10)),
      number: raw.number || raw.page || 0,
      size: raw.size || 10,
    };
  }

  static toCreatePayload(request: CreateCargarubrosidoRequest): FormData {
    const formData = new FormData();
    if (request.archivo) {
      formData.append('archivo', request.archivo);
    }
    formData.append('empresaId', request.empresaId.toString());
    if (request.rubroId) {
      formData.append('rubroId', request.rubroId);
    }
    if (request.descripcion) {
      formData.append('descripcion', request.descripcion);
    }
    return formData;
  }

  static toUpdatePayload(request: UpdateCargarubrosidoRequest): Record<string, unknown> {
    return {
      estado: request.estado,
      descripcion: request.descripcion,
    };
  }
}
