import { ConsultarubrosidolistResponse, ConsultarubrosidolistListResponse, ExportarResponseDTO, CreateConsultarubrosidolistRequest, UpdateConsultarubrosidolistRequest, ExportarConsultaIDORequest, CambiarEstadoIDORequest } from '../../../input/adapter/dto/ConsultarubrosidolistDto';

/**
 * API Mapper: consultaRubrosIdoList.zul
 * Transforma las respuestas raw de la API a los DTOs tipados del frontend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class ConsultarubrosidolistApiMapper {

  static toResponse(raw: any): ConsultarubrosidolistResponse {
    return {
      id: raw.id,
      dfechapagocaja: raw.dfechapagocaja,
      rubroId: raw.vidrubro ?? raw.rubroId,
      colaboradorId: raw.iidcolaborador ?? raw.colaboradorId,
      tipoComportamiento: raw.itcomporta ?? raw.tipoComportamiento ?? 0,
      valor01: raw.mvalor01 ?? raw.valor01 ?? 0,
      valor02: raw.mvalor02 ?? raw.valor02,
      empresaId: raw.iidempresa ?? raw.empresaId,
      localidadId: raw.iidlocalidad,
      centroCostoId: raw.iidcentrocosto ?? raw.centroCostoId,
      rolId: raw.iidrol,
      neroId: raw.inero,
      cartaImpresion: raw.icartaimpresion,
      flagEnvio: raw.iflagenvio,
      generarCarta: raw.igenerarcarta,
      estadoCaja: raw.vestadoCaja,
      usuarioCaja: raw.vusuarioCaja,
      vstts: raw.vstts,
      estado: raw.vstts ?? raw.estado,
      fechaDesde: raw.dfdesde ?? raw.fechaDesde,
      fechaHasta: raw.dfhasta ?? raw.fechaHasta,
      nombreColaborador: raw.nombreColaborador,
      nombreRubro: raw.nombreRubro,
      fechaCreacion: raw.fechaCreacion,
      fechaActualizacion: raw.fechaActualizacion,
    };
  }

  static toListResponse(raw: any): ConsultarubrosidolistListResponse {
    const data = raw.content || raw.data || raw;
    const items = Array.isArray(data) ? data.map((item: any) => ConsultarubrosidolistApiMapper.toResponse(item)) : [];
    return {
      content: items,
      totalElements: raw.totalElements || raw.total || items.length,
      totalPages: raw.totalPages || Math.ceil((raw.totalElements || items.length) / (raw.size || 10)),
      number: raw.number || raw.page || 0,
      size: raw.size || 10,
    };
  }

  static toExportResponse(raw: any): ExportarResponseDTO {
    return {
      success: raw.success ?? false,
      archivoUrl: raw.archivoUrl,
      message: raw.message,
    };
  }

  static toCreatePayload(request: CreateConsultarubrosidolistRequest): Record<string, unknown> {
    return {
      dfechapagocaja: request.dfechapagocaja,
      vidrubro: request.rubroId,
      iidcolaborador: request.colaboradorId,
      iidempresa: request.empresaId,
      iidlocalidad: request.localidadId,
      iidcentrocosto: request.centroCostoId,
      iidrol: request.rolId,
      inero: request.neroId,
      itcomporta: request.tipoComportamiento,
      mvalor01: request.valor01,
      mvalor02: request.valor02,
      icartaimpresion: request.cartaImpresion,
      iflagenvio: request.flagEnvio,
      igenerarcarta: request.generarCarta,
      vestadoCaja: request.estadoCaja,
      vusuarioCaja: request.usuarioCaja,
      estado: request.estado,
      dfdesde: request.fechaDesde,
      dfhasta: request.fechaHasta,
    };
  }

  static toUpdatePayload(request: UpdateConsultarubrosidolistRequest): Record<string, unknown> {
    return {
      estado: request.estado,
    };
  }

  static toExportPayload(request: ExportarConsultaIDORequest): Record<string, unknown> {
    return {
      vidrubro: request.rubroId,
      iidcolaborador: request.colaboradorId,
      iidempresa: request.empresaId,
      estado: request.estado,
      dfdesde: request.fechaDesde,
      dfhasta: request.fechaHasta,
      formato: request.formato || 'XLSX',
    };
  }

  static toCambiarEstadoPayload(request: CambiarEstadoIDORequest): Record<string, unknown> {
    return {
      vstts: request.vstts,
    };
  }
}
