import { ConsultarubrosidolistResponse, ConsultarubrosidolistListResponse, ExportarResponseDTO, CreateConsultarubrosidolistRequest, UpdateConsultarubrosidolistRequest, ExportarConsultaIDORequest, CambiarEstadoIDORequest } from '../../../input/adapter/dto/ConsultarubrosidolistDto';

/**
 * API Mapper: consultaRubrosIdoList.zul
 * Transforma las respuestas raw de la API a los DTOs tipados del frontend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class ConsultarubrosidolistApiMapper {

  static toResponse(raw: any): ConsultarubrosidolistResponse {
    return {
      id: raw.id,
      rubroId: raw.rubroId,
      colaboradorId: raw.colaboradorId,
      tipoComportamiento: raw.tipoComportamiento || 0,
      valor01: raw.valor01 || 0,
      empresaId: raw.empresaId,
      estado: raw.estado,
      fechaDesde: raw.fechaDesde,
      fechaHasta: raw.fechaHasta,
      nombreColaborador: raw.nombreColaborador,
      nombreRubro: raw.nombreRubro,
      fechaCreacion: raw.fechaCreacion,
      fechaActualizacion: raw.fechaActualizacion,
    };
  }

  static toListResponse(raw: any): ConsultarubrosidolistListResponse {
    const data = raw.content || raw.data || raw;
    const items = Array.isArray(data) ? data.map((item: any) => ConsultarubrosidolistApiMapper.toResponse(item)) : [];
    return {
      content: items,
      totalElements: raw.totalElements || raw.total || items.length,
      totalPages: raw.totalPages || Math.ceil((raw.totalElements || items.length) / (raw.size || 10)),
      number: raw.number || raw.page || 0,
      size: raw.size || 10,
    };
  }

  static toExportResponse(raw: any): ExportarResponseDTO {
    return {
      success: raw.success ?? false,
      archivoUrl: raw.archivoUrl,
      message: raw.message,
    };
  }

  static toCreatePayload(request: CreateConsultarubrosidolistRequest): Record<string, unknown> {
    return {
      rubroId: request.rubroId,
      colaboradorId: request.colaboradorId,
      empresaId: request.empresaId,
      estado: request.estado,
      fechaDesde: request.fechaDesde,
      fechaHasta: request.fechaHasta,
    };
  }

  static toUpdatePayload(request: UpdateConsultarubrosidolistRequest): Record<string, unknown> {
    return {
      estado: request.estado,
    };
  }

  static toExportPayload(request: ExportarConsultaIDORequest): Record<string, unknown> {
    return {
      rubroId: request.rubroId,
      colaboradorId: request.colaboradorId,
      empresaId: request.empresaId,
      estado: request.estado,
      fechaDesde: request.fechaDesde,
      fechaHasta: request.fechaHasta,
      formato: request.formato || 'XLSX',
    };
  }

  static toCambiarEstadoPayload(request: CambiarEstadoIDORequest): Record<string, unknown> {
    return {
      estado: request.estado,
    };
  }
}
