import { RubrosidomainResponse, RubrosidomainListResponse, CreateRubrosidomainRequest, UpdateRubrosidomainRequest } from '../../../input/adapter/dto/RubrosidomainDto';

/**
 * API Mapper: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Transforma las respuestas raw de la API a los DTOs tipados del frontend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosidomainApiMapper {

  static toResponse(raw: any): RubrosidomainResponse {
    return {
      id: raw.id,
      dfechapagocaja: raw.dfechapagocaja,
      rubroId: raw.rubroId,
      colaboradorId: raw.colaboradorId,
      empresaId: raw.empresaId,
      centroCostoId: raw.centroCostoId,
      localidadId: raw.localidadId,
      neroId: raw.neroId,
      rolId: raw.rolId,
      tipoComportamiento: raw.tipoComportamiento,
      valor01: raw.valor01,
      valor02: raw.valor02,
      valor03: raw.valor03,
      cartaImpresion: raw.cartaImpresion,
      flagEnvio: raw.flagEnvio,
      generarCarta: raw.generarCarta,
      estadoCaja: raw.estadoCaja,
      usuarioCaja: raw.usuarioCaja,
      estado: raw.estado,
      fechaDesde: raw.fechaDesde,
      fechaHasta: raw.fechaHasta,
      nombreColaborador: raw.nombreColaborador,
      nombreRubro: raw.nombreRubro,
      fechaCreacion: raw.fechaCreacion,
      fechaActualizacion: raw.fechaActualizacion,
    };
  }

  static toListResponse(raw: any): RubrosidomainListResponse {
    const data = raw.content || raw.data || raw;
    const items = Array.isArray(data) ? data.map((item: any) => RubrosidomainApiMapper.toResponse(item)) : [];
    return {
      content: items,
      totalElements: raw.totalElements || raw.total || items.length,
      totalPages: raw.totalPages || Math.ceil((raw.totalElements || items.length) / (raw.size || 10)),
      number: raw.number || raw.page || 0,
      size: raw.size || 10,
    };
  }

  static toCreatePayload(request: CreateRubrosidomainRequest): Record<string, unknown> {
    return {
      dfechapagocaja: request.dfechapagocaja,
      rubroId: request.rubroId,
      colaboradorId: request.colaboradorId,
      empresaId: request.empresaId,
      centroCostoId: request.centroCostoId,
      localidadId: request.localidadId,
      neroId: request.neroId,
      rolId: request.rolId,
      tipoComportamiento: request.tipoComportamiento,
      valor01: request.valor01,
      valor02: request.valor02,
      valor03: request.valor03,
      cartaImpresion: request.cartaImpresion,
      flagEnvio: request.flagEnvio,
      generarCarta: request.generarCarta,
      estadoCaja: request.estadoCaja,
      usuarioCaja: request.usuarioCaja,
      estado: request.estado,
      fechaDesde: request.fechaDesde,
      fechaHasta: request.fechaHasta,
    };
  }

  static toUpdatePayload(request: UpdateRubrosidomainRequest): Record<string, unknown> {
    return {
      dfechapagocaja: request.dfechapagocaja,
      rubroId: request.rubroId,
      colaboradorId: request.colaboradorId,
      empresaId: request.empresaId,
      centroCostoId: request.centroCostoId,
      localidadId: request.localidadId,
      neroId: request.neroId,
      rolId: request.rolId,
      tipoComportamiento: request.tipoComportamiento,
      valor01: request.valor01,
      valor02: request.valor02,
      valor03: request.valor03,
      cartaImpresion: request.cartaImpresion,
      flagEnvio: request.flagEnvio,
      generarCarta: request.generarCarta,
      estadoCaja: request.estadoCaja,
      usuarioCaja: request.usuarioCaja,
      estado: request.estado,
      fechaDesde: request.fechaDesde,
      fechaHasta: request.fechaHasta,
    };
  }
}
