import { RubrosidocargaxprocesoResponse, RubrosidocargaxprocesoListResponse, CreateRubrosidocargaxprocesoRequest, UpdateRubrosidocargaxprocesoRequest } from '../../../input/adapter/dto/RubrosidocargaxprocesoDto';

/**
 * API Mapper: rubrosIDOcargaxProceso.zul
 * Transforma las respuestas raw de la API a los DTOs tipados del frontend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosidocargaxprocesoApiMapper {

  static toResponse(raw: any): RubrosidocargaxprocesoResponse {
    return {
      id: raw.id ?? raw.iidrubrosIdocp,
      iidrubrosIdocp: raw.iidrubrosIdocp,
      iidrubrosIdo: raw.iidrubrosIdo,
      iidempresa: raw.iidempresa,
      vidrubro: raw.vidrubro,
      vidambito: raw.vidambito,
      dfechaaplica: raw.dfechaaplica,
      usuarioingresoAu: raw.usuarioingresoAu,
      empresa: raw.empresa,
      fechaCarga: raw.fechaCarga,
      cargadoPor: raw.cargadoPor,
      registrosProcesados: raw.registrosProcesados,
      mensaje: raw.mensaje,
      procesoId: raw.procesoId ?? String(raw.iidrubrosIdocp ?? raw.id ?? ''),
      fechaEjecucion: raw.fechaEjecucion ?? raw.fechaCarga,
      estado: raw.estado,
      numeroRegistrosCargados: raw.numeroRegistrosCargados ?? raw.registrosProcesados ?? 0,
      numeroErrores: raw.numeroErrores ?? 0,
      usuarioEjecucion: raw.usuarioEjecucion ?? raw.cargadoPor,
      empresaId: raw.empresaId ?? raw.iidempresa,
      descripcion: raw.descripcion,
      fechaCreacion: raw.fechaCreacion,
      fechaActualizacion: raw.fechaActualizacion,
    };
  }

  static toListResponse(raw: any): RubrosidocargaxprocesoListResponse {
    const data = raw.items || raw.content || raw.data || raw;
    const items = Array.isArray(data) ? data.map((item: any) => RubrosidocargaxprocesoApiMapper.toResponse(item)) : [];
    return {
      items,
      total: raw.total || raw.totalElements || items.length,
      totalPages: raw.totalPages || Math.ceil((raw.total || raw.totalElements || items.length) / (raw.size || 10)),
      page: raw.page || raw.number || 0,
      size: raw.size || 10,
    };
  }

  static toCreatePayload(request: CreateRubrosidocargaxprocesoRequest): Record<string, unknown> {
    return {
      iidempresa: request.iidempresa,
      vidrubro: request.vidrubro,
      accion: request.accion,
      fechaAplica: request.fechaAplica,
      ambito: request.ambito,
      iidrubrosIdo: request.iidrubrosIdo,
      procesoId: request.procesoId,
      descripcion: request.descripcion,
    };
  }

  static toUpdatePayload(request: UpdateRubrosidocargaxprocesoRequest): Record<string, unknown> {
    return {
      accion: request.accion,
      fechaAplica: request.fechaAplica,
      ambito: request.ambito,
      estado: request.estado,
    };
  }
}
