import { RubrosxprocesodialogResponse, RubrosxprocesodialogListResponse, CreateRubrosxprocesodialogRequest, UpdateRubrosxprocesodialogRequest } from '../../../input/adapter/dto/RubrosxprocesodialogDto';

/**
 * API Mapper: rubrosxprocesoDialog.zul
 * Transforma las respuestas raw de la API a los DTOs tipados del frontend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosxprocesodialogApiMapper {

  static toResponse(raw: any): RubrosxprocesodialogResponse {
    return {
      id: raw.id,
      rubroId: raw.rubroId,
      procesoId: raw.procesoId,
      secuencia: raw.secuencia,
      frecuenciaEjecucion: raw.frecuenciaEjecucion,
      activo: raw.activo ?? true,
      fechaCreacion: raw.fechaCreacion,
      fechaActualizacion: raw.fechaActualizacion,
    };
  }

  static toListResponse(raw: any): RubrosxprocesodialogListResponse {
    const data = raw.content || raw.data || raw;
    const items = Array.isArray(data) ? data.map((item: any) => RubrosxprocesodialogApiMapper.toResponse(item)) : [];
    return {
      content: items,
      totalElements: raw.totalElements || raw.total || items.length,
      totalPages: raw.totalPages || Math.ceil((raw.totalElements || items.length) / (raw.size || 10)),
      number: raw.number || raw.page || 0,
      size: raw.size || 10,
    };
  }

  static toCreatePayload(request: CreateRubrosxprocesodialogRequest): Record<string, unknown> {
    return {
      rubroId: request.rubroId,
      procesoId: request.procesoId,
      secuencia: request.secuencia,
      frecuenciaEjecucion: request.frecuenciaEjecucion,
      activo: request.activo ?? true,
    };
  }

  static toUpdatePayload(request: UpdateRubrosxprocesodialogRequest): Record<string, unknown> {
    return {
      secuencia: request.secuencia,
      frecuenciaEjecucion: request.frecuenciaEjecucion,
      activo: request.activo,
    };
  }
}
