import { RubrosidomainRubrosidolistRubrosidodetailResponse, RubrosidomainRubrosidolistRubrosidodetailListResponse, CreateRubrosidomainRubrosidolistRubrosidodetailRequest, UpdateRubrosidomainRubrosidolistRubrosidodetailRequest } from '../../../input/adapter/dto/RubrosidomainRubrosidolistRubrosidodetailDto';

/**
 * API Mapper: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Transforma las respuestas raw de la API a los DTOs tipados del frontend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosidomainRubrosidolistRubrosidodetailApiMapper {

  static toResponse(raw: any): RubrosidomainRubrosidolistRubrosidodetailResponse {
    return {
      id: raw.id,
      rubroId: raw.rubroId,
      colaboradorId: raw.colaboradorId,
      empresaId: raw.empresaId,
      tipoComportamiento: raw.tipoComportamiento,
      valor01: raw.valor01,
      valor02: raw.valor02,
      valor03: raw.valor03,
      estado: raw.estado,
      fechaDesde: raw.fechaDesde,
      fechaHasta: raw.fechaHasta,
      nombreColaborador: raw.nombreColaborador,
      nombreRubro: raw.nombreRubro,
      fechaCreacion: raw.fechaCreacion,
      fechaActualizacion: raw.fechaActualizacion,
    };
  }

  static toListResponse(raw: any): RubrosidomainRubrosidolistRubrosidodetailListResponse {
    const data = raw.content || raw.data || raw;
    const items = Array.isArray(data) ? data.map((item: any) => RubrosidomainRubrosidolistRubrosidodetailApiMapper.toResponse(item)) : [];
    return {
      content: items,
      totalElements: raw.totalElements || raw.total || items.length,
      totalPages: raw.totalPages || Math.ceil((raw.totalElements || items.length) / (raw.size || 10)),
      number: raw.number || raw.page || 0,
      size: raw.size || 10,
    };
  }

  static toCreatePayload(request: CreateRubrosidomainRubrosidolistRubrosidodetailRequest): Record<string, unknown> {
    return {
      rubroId: request.rubroId,
      colaboradorId: request.colaboradorId,
      empresaId: request.empresaId,
      tipoComportamiento: request.tipoComportamiento,
      valor01: request.valor01,
      valor02: request.valor02,
      valor03: request.valor03,
      estado: request.estado,
      fechaDesde: request.fechaDesde,
      fechaHasta: request.fechaHasta,
    };
  }

  static toUpdatePayload(request: UpdateRubrosidomainRubrosidolistRubrosidodetailRequest): Record<string, unknown> {
    return {
      tipoComportamiento: request.tipoComportamiento,
      valor01: request.valor01,
      valor02: request.valor02,
      valor03: request.valor03,
      estado: request.estado,
      fechaHasta: request.fechaHasta,
    };
  }
}
