import {
  RubrosRubrosdialogResponse,
  RubrosRubrosdialogListResponse,
  CreateRubrosRubrosdialogRequest,
  UpdateRubrosRubrosdialogRequest,
} from "../../../input/adapter/dto/RubrosRubrosdialogDto";
import { AmbitoRubro, EfectoRubro } from "../../../../domain/model/RubrosRubrosdialog";

/**
 * API Mapper: rubros.zul / rubrosDialog.zul
 * Transforma las respuestas raw de la API a los DTOs tipados del frontend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosRubrosdialogApiMapper {
  private static parseAmbito(value: unknown): AmbitoRubro | undefined {
    if (value === "NA" || value === "IDO" || value === "PTM") {
      return value;
    }
    return undefined;
  }

  private static parseEfecto(value: unknown): EfectoRubro | undefined {
    if (value === "ING" || value === "EGR" || value === "NA") {
      return value;
    }
    return undefined;
  }

  static toResponse(raw: any): RubrosRubrosdialogResponse {
    return {
      idRubro: raw.idRubro || raw.id,
      nombre: raw.nombre,
      ambito: RubrosRubrosdialogApiMapper.parseAmbito(raw.ambito),
      efecto: RubrosRubrosdialogApiMapper.parseEfecto(raw.efecto),
      observaciones: raw.observaciones,
      tipoCalculo: raw.tipoCalculo,
      acumulable: raw.acumulable ?? false,
      rubroHistorico: raw.rubroHistorico,
      secuenciaImpresion: raw.secuenciaImpresion,
      secuenciaSobregiro: raw.secuenciaSobregiro,
      aplicaInterfaz: raw.aplicaInterfaz,
      insertaEnLote: raw.insertaEnLote,
      carta: raw.carta,
      estado: raw.estado,
      antiguedadMinima: raw.antiguedadMinima,
      numAprobaciones: raw.numAprobaciones,
      numAprobacionesNoLocales: raw.numAprobacionesNoLocales,
      plazoMaximo: raw.plazoMaximo,
      plazoMinimo: raw.plazoMinimo,
      montoMaximo: raw.montoMaximo,
      verificaEndeudamiento: raw.verificaEndeudamiento,
      usuarioCreacion: raw.usuarioCreacion,
      fechaCreacion: raw.fechaCreacion,
      usuarioActualizacion: raw.usuarioActualizacion,
      fechaActualizacion: raw.fechaActualizacion,
    };
  }

  static toListResponse(raw: any): RubrosRubrosdialogListResponse {
    const data = raw.content || raw.data || raw;
    const items = Array.isArray(data)
      ? data.map((item: any) => RubrosRubrosdialogApiMapper.toResponse(item))
      : [];
    console.log("API Response for findAll:", items); // Debug log
    return {
      content: items,
      totalElements: raw.totalElements || raw.total || items.length,
      totalPages:
        raw.totalPages ||
        Math.ceil((raw.totalElements || items.length) / (raw.size || 10)),
      number: raw.number || raw.page || 0,
      size: raw.size || 10,
    };
  }

  static toCreatePayload(
    request: CreateRubrosRubrosdialogRequest,
  ): Record<string, unknown> {
    return {
      idRubro: request.idRubro,
      nombre: request.nombre,
      ambito: request.ambito,
      efecto: request.efecto,
      observaciones: request.observaciones,
      tipoCalculo: request.tipoCalculo,
      acumulable: request.acumulable ?? false,
      rubroHistorico: request.rubroHistorico,
      secuenciaImpresion: request.secuenciaImpresion,
      secuenciaSobregiro: request.secuenciaSobregiro,
      aplicaInterfaz: request.aplicaInterfaz,
      insertaEnLote: request.insertaEnLote,
      carta: request.carta,
      antiguedadMinima: request.antiguedadMinima,
      numAprobaciones: request.numAprobaciones,
      numAprobacionesNoLocales: request.numAprobacionesNoLocales,
      plazoMaximo: request.plazoMaximo,
      plazoMinimo: request.plazoMinimo,
      montoMaximo: request.montoMaximo,
      verificaEndeudamiento: request.verificaEndeudamiento,
    };
  }

  static toUpdatePayload(
    request: UpdateRubrosRubrosdialogRequest,
  ): Record<string, unknown> {
    return {
      nombre: request.nombre,
      ambito: request.ambito,
      efecto: request.efecto,
      observaciones: request.observaciones,
      tipoCalculo: request.tipoCalculo,
      acumulable: request.acumulable ?? false,
      rubroHistorico: request.rubroHistorico,
      secuenciaImpresion: request.secuenciaImpresion,
      secuenciaSobregiro: request.secuenciaSobregiro,
      aplicaInterfaz: request.aplicaInterfaz,
      insertaEnLote: request.insertaEnLote,
      carta: request.carta,
      antiguedadMinima: request.antiguedadMinima,
      numAprobaciones: request.numAprobaciones,
      numAprobacionesNoLocales: request.numAprobacionesNoLocales,
      plazoMaximo: request.plazoMaximo,
      plazoMinimo: request.plazoMinimo,
      montoMaximo: request.montoMaximo,
      verificaEndeudamiento: request.verificaEndeudamiento,
    };
  }
}
