// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Cargarubrosido, CargarubrosidoLinea, CreateCargarubrosido, UpdateCargarubrosido, CargarubrosidoFilter, CargarubrosidoPageResult, CargarubrosidoLineaPageResult } from '../../../../domain/model/Cargarubrosido';
import { CargarubrosidoResponse, CargarubrosidoLineaResponse, CargarubrosidoListResponse, CargarubrosidoLineaListResponse, CreateCargarubrosidoRequest, UpdateCargarubrosidoRequest, CargarubrosidoFilterParams } from '../dto/CargarubrosidoDto';

export class CargarubrosidoViewMapper {

  static toDomain(response: CargarubrosidoResponse): Cargarubrosido {
    return {
      id: response.id,
      bancoId: response.iidbanco,
      usuarioModificacion: response.usuariomodificacionAu,
      fechaModificacion: response.horamodificacionAu,
      rubroId: response.rubroId ?? '',
      ambito: response.ambito,
      fechaAplica: response.fechaAplica,
      usuarioIngreso: response.usuarioIngreso,
      nombreArchivo: response.nombreArchivo,
      fechaCarga: response.fechaCarga,
      estado: response.estado,
      usuarioCarga: response.usuarioCarga,
      numeroRegistros: response.numeroRegistros,
      numeroErrores: response.numeroErrores,
      numeroExitosos: response.numeroExitosos,
      empresaId: response.empresaId,
      procesoId: response.procesoId,
      descripcion: response.descripcion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toLineaDomain(response: CargarubrosidoLineaResponse): CargarubrosidoLinea {
    return {
      iidrubrosIdoUpl: response.iidrubrosIdoUpl,
      iidrubrosIdoUp: response.iidrubrosIdoUp,
      dfdesde: response.dfdesde,
      dfhasta: response.dfhasta,
      mvalor01: response.mvalor01,
      mvalor02: response.mvalor02,
      vidrubro: response.vidrubro,
      vcedula: response.vcedula,
      itcomporta: response.itcomporta,
      vcuentabanco: response.vcuentabanco,
      lineaId: response.lineaId,
      rubroId: response.rubroId,
      colaboradorId: response.colaboradorId,
      valor: response.valor ?? response.mvalor01,
      estado: response.estado,
      mensaje: response.mensaje,
    };
  }

  static toPageResult(listResponse: CargarubrosidoListResponse): CargarubrosidoPageResult {
    return {
      items: listResponse.content.map(CargarubrosidoViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toLineaPageResult(listResponse: CargarubrosidoLineaListResponse): CargarubrosidoLineaPageResult {
    return {
      items: listResponse.content.map(CargarubrosidoViewMapper.toLineaDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateCargarubrosido): CreateCargarubrosidoRequest {
    return {
      archivo: model.archivo,
      iidempresa: model.empresaId,
      vidrubro: model.rubroId ?? '',
      vidambito: model.ambito,
      dfechaaplica: model.fechaAplica,
      tipoAP: model.tipoAP,
      iidBanco: model.bancoId,
      vidTipoCta: model.tipoCuenta,
      viTipoColaborador: model.tipoColaborador,
      dtbFInicio: model.periodoInicio,
      dtbFFin: model.periodoFin,
      descripcion: model.descripcion,
      observaciones: model.observaciones,
    };
  }

  static toUpdateRequest(model: UpdateCargarubrosido): UpdateCargarubrosidoRequest {
    return {
      estado: model.estado,
      descripcion: model.descripcion,
    };
  }

  static toFilterParams(filter: CargarubrosidoFilter): CargarubrosidoFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      empresaId: filter.empresaId,
      rubroId: filter.rubroId,
      estado: filter.estado,
      sort: filter.sort,
    };
  }
}
