// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Cargarubrosido, CargarubrosidoLinea, CreateCargarubrosido, UpdateCargarubrosido, CargarubrosidoFilter, CargarubrosidoPageResult, CargarubrosidoLineaPageResult } from '../../../../domain/model/Cargarubrosido';
import { CargarubrosidoResponse, CargarubrosidoLineaResponse, CargarubrosidoListResponse, CargarubrosidoLineaListResponse, CreateCargarubrosidoRequest, UpdateCargarubrosidoRequest, CargarubrosidoFilterParams } from '../dto/CargarubrosidoDto';

export class CargarubrosidoViewMapper {

  static toDomain(response: CargarubrosidoResponse): Cargarubrosido {
    return {
      id: response.id,
      nombreArchivo: response.nombreArchivo,
      fechaCarga: response.fechaCarga,
      estado: response.estado,
      usuarioCarga: response.usuarioCarga,
      numeroRegistros: response.numeroRegistros,
      numeroErrores: response.numeroErrores,
      numeroExitosos: response.numeroExitosos,
      empresaId: response.empresaId,
      procesoId: response.procesoId,
      descripcion: response.descripcion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toLineaDomain(response: CargarubrosidoLineaResponse): CargarubrosidoLinea {
    return {
      lineaId: response.lineaId,
      rubroId: response.rubroId,
      colaboradorId: response.colaboradorId,
      valor: response.valor,
      estado: response.estado,
      mensaje: response.mensaje,
    };
  }

  static toPageResult(listResponse: CargarubrosidoListResponse): CargarubrosidoPageResult {
    return {
      items: listResponse.content.map(CargarubrosidoViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toLineaPageResult(listResponse: CargarubrosidoLineaListResponse): CargarubrosidoLineaPageResult {
    return {
      items: listResponse.content.map(CargarubrosidoViewMapper.toLineaDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateCargarubrosido): CreateCargarubrosidoRequest {
    return {
      archivo: model.archivo,
      empresaId: model.empresaId,
      rubroId: model.rubroId,
      descripcion: model.descripcion,
    };
  }

  static toUpdateRequest(model: UpdateCargarubrosido): UpdateCargarubrosidoRequest {
    return {
      estado: model.estado,
      descripcion: model.descripcion,
    };
  }

  static toFilterParams(filter: CargarubrosidoFilter): CargarubrosidoFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      empresaId: filter.empresaId,
      rubroId: filter.rubroId,
      estado: filter.estado,
      sort: filter.sort,
    };
  }
}
