// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Consultarubrosidolist, CreateConsultarubrosidolist, UpdateConsultarubrosidolist, ConsultarubrosidolistFilter, ConsultarubrosidolistPageResult } from '../../../../domain/model/Consultarubrosidolist';
import { ConsultarubrosidolistResponse, ConsultarubrosidolistListResponse, CreateConsultarubrosidolistRequest, UpdateConsultarubrosidolistRequest, ConsultarubrosidolistFilterParams, ExportarConsultaIDORequest } from '../dto/ConsultarubrosidolistDto';

export class ConsultarubrosidolistViewMapper {

  static toDomain(response: ConsultarubrosidolistResponse): Consultarubrosidolist {
    return {
      id: response.id,
      rubroId: response.rubroId,
      colaboradorId: response.colaboradorId,
      tipoComportamiento: response.tipoComportamiento,
      valor01: response.valor01,
      empresaId: response.empresaId,
      estado: response.estado,
      fechaDesde: response.fechaDesde,
      fechaHasta: response.fechaHasta,
      nombreColaborador: response.nombreColaborador,
      nombreRubro: response.nombreRubro,
      fechaCreacion: response.fechaCreacion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toPageResult(listResponse: ConsultarubrosidolistListResponse): ConsultarubrosidolistPageResult {
    return {
      items: listResponse.content.map(ConsultarubrosidolistViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateConsultarubrosidolist): CreateConsultarubrosidolistRequest {
    return {
      rubroId: model.rubroId,
      colaboradorId: model.colaboradorId,
      empresaId: model.empresaId,
      estado: model.estado,
      fechaDesde: model.fechaDesde,
      fechaHasta: model.fechaHasta,
    };
  }

  static toUpdateRequest(model: UpdateConsultarubrosidolist): UpdateConsultarubrosidolistRequest {
    return {
      estado: model.estado,
    };
  }

  static toFilterParams(filter: ConsultarubrosidolistFilter): ConsultarubrosidolistFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      rubroId: filter.rubroId,
      colaboradorId: filter.colaboradorId,
      empresaId: filter.empresaId,
      estado: filter.estado,
      fechaDesde: filter.fechaDesde,
      fechaHasta: filter.fechaHasta,
      localidadId: filter.localidadId,
      centroCostoId: filter.centroCostoId,
    };
  }

  static toExportarRequest(filter: ConsultarubrosidolistFilter): ExportarConsultaIDORequest {
    return {
      rubroId: filter.rubroId,
      colaboradorId: filter.colaboradorId,
      empresaId: filter.empresaId,
      estado: filter.estado,
      fechaDesde: filter.fechaDesde,
      fechaHasta: filter.fechaHasta,
    };
  }
}
