// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Consultarubrosidolist, CreateConsultarubrosidolist, UpdateConsultarubrosidolist, ConsultarubrosidolistFilter, ConsultarubrosidolistPageResult } from '../../../../domain/model/Consultarubrosidolist';
import { ConsultarubrosidolistResponse, ConsultarubrosidolistListResponse, CreateConsultarubrosidolistRequest, UpdateConsultarubrosidolistRequest, ConsultarubrosidolistFilterParams, ExportarConsultaIDORequest } from '../dto/ConsultarubrosidolistDto';

export class ConsultarubrosidolistViewMapper {

  static toDomain(response: ConsultarubrosidolistResponse): Consultarubrosidolist {
    return {
      id: response.id,
      dfechapagocaja: response.dfechapagocaja,
      rubroId: response.rubroId,
      colaboradorId: response.colaboradorId,
      tipoComportamiento: response.tipoComportamiento,
      valor01: response.valor01,
      valor02: response.valor02,
      empresaId: response.empresaId,
      localidadId: response.localidadId,
      centroCostoId: response.centroCostoId,
      rolId: response.rolId,
      neroId: response.neroId,
      cartaImpresion: response.cartaImpresion,
      flagEnvio: response.flagEnvio,
      generarCarta: response.generarCarta,
      estadoCaja: response.estadoCaja,
      usuarioCaja: response.usuarioCaja,
      vstts: response.vstts,
      estado: response.estado,
      fechaDesde: response.fechaDesde,
      fechaHasta: response.fechaHasta,
      nombreColaborador: response.nombreColaborador,
      nombreRubro: response.nombreRubro,
      fechaCreacion: response.fechaCreacion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toPageResult(listResponse: ConsultarubrosidolistListResponse): ConsultarubrosidolistPageResult {
    return {
      items: listResponse.content.map(ConsultarubrosidolistViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateConsultarubrosidolist): CreateConsultarubrosidolistRequest {
    return {
      rubroId: model.rubroId,
      dfechapagocaja: model.fechaDesde,
      colaboradorId: model.colaboradorId,
      empresaId: model.empresaId,
      localidadId: model.localidadId,
      centroCostoId: model.centroCostoId,
      rolId: model.rolId,
      neroId: model.neroId,
      tipoComportamiento: model.tipoComportamiento,
      valor01: model.valor01,
      valor02: model.valor02,
      cartaImpresion: model.cartaImpresion,
      flagEnvio: model.flagEnvio,
      generarCarta: model.generarCarta,
      estadoCaja: model.estadoCaja,
      usuarioCaja: model.usuarioCaja,
      estado: model.estado,
      fechaDesde: model.fechaDesde,
      fechaHasta: model.fechaHasta,
    };
  }

  static toUpdateRequest(model: UpdateConsultarubrosidolist): UpdateConsultarubrosidolistRequest {
    return {
      estado: model.estado,
    };
  }

  static toFilterParams(filter: ConsultarubrosidolistFilter): ConsultarubrosidolistFilterParams {
    return {
      pagina: filter.pagina ?? filter.page,
      tamanio: filter.tamanio ?? filter.size,
      vidrubro: filter.vidrubro ?? filter.rubroId,
      iidcolaborador: filter.iidcolaborador ?? filter.colaboradorId,
      iidempresa: filter.iidempresa ?? filter.empresaId,
      estado: filter.estado,
      dfdesde: filter.dfdesde ?? filter.fechaDesde,
      fechaHasta: filter.fechaHasta,
      iidlocalidad: filter.iidlocalidad ?? filter.localidadId,
      centroCostoId: filter.centroCostoId,
    };
  }

  static toExportarRequest(filter: ConsultarubrosidolistFilter): ExportarConsultaIDORequest {
    return {
      rubroId: filter.rubroId,
      colaboradorId: filter.colaboradorId,
      empresaId: filter.empresaId,
      estado: filter.estado,
      fechaDesde: filter.fechaDesde,
      fechaHasta: filter.fechaHasta,
    };
  }
}
