// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosxprocesodialog, CreateRubrosxprocesodialog, UpdateRubrosxprocesodialog, RubrosxprocesodialogFilter, RubrosxprocesodialogPageResult } from '../../../../domain/model/Rubrosxprocesodialog';
import { RubrosxprocesodialogResponse, RubrosxprocesodialogListResponse, CreateRubrosxprocesodialogRequest, UpdateRubrosxprocesodialogRequest, RubrosxprocesodialogFilterParams } from '../dto/RubrosxprocesodialogDto';

export class RubrosxprocesodialogViewMapper {

  static toDomain(response: RubrosxprocesodialogResponse): Rubrosxprocesodialog {
    return {
      id: response.id,
      rubroId: response.rubroId,
      rubroNombre: response.rubroNombre,
      procesoId: response.procesoId,
      procesoNombre: response.procesoNombre,
      secuencia: response.secuencia,
      frecuenciaEjecucion: response.frecuenciaEjecucion,
      procedimientoCalculo: response.procedimientoCalculo,
      ambitoEjecucion: response.ambitoEjecucion,
      insertaEnLote: response.insertaEnLote,
      validaPlantillaContable: response.validaPlantillaContable,
      estado: response.estado,
      usuarioIngreso: response.usuarioIngreso,
      fechaIngreso: response.fechaIngreso,
      usuarioModificacion: response.usuarioModificacion,
      fechaModificacion: response.fechaModificacion,
      activo: response.activo,
      fechaCreacion: response.fechaCreacion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toPageResult(listResponse: RubrosxprocesodialogListResponse): RubrosxprocesodialogPageResult {
    return {
      items: listResponse.content.map(RubrosxprocesodialogViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateRubrosxprocesodialog): CreateRubrosxprocesodialogRequest {
    return {
      rubroId: model.rubroId,
      procesoId: model.procesoId,
      secuencia: model.secuencia,
      frecuenciaEjecucion: model.frecuenciaEjecucion,
      procedimientoCalculo: model.procedimientoCalculo,
      ambitoEjecucion: model.ambitoEjecucion,
      insertaEnLote: model.insertaEnLote,
      validaPlantillaContable: model.validaPlantillaContable,
      estado: model.estado,
      activo: model.activo,
    };
  }

  static toUpdateRequest(model: UpdateRubrosxprocesodialog): UpdateRubrosxprocesodialogRequest {
    return {
      secuencia: model.secuencia,
      frecuenciaEjecucion: model.frecuenciaEjecucion,
      procedimientoCalculo: model.procedimientoCalculo,
      ambitoEjecucion: model.ambitoEjecucion,
      insertaEnLote: model.insertaEnLote,
      validaPlantillaContable: model.validaPlantillaContable,
      estado: model.estado,
      activo: model.activo,
    };
  }

  static toFilterParams(filter: RubrosxprocesodialogFilter): RubrosxprocesodialogFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      rubroId: filter.rubroId,
      procesoId: filter.procesoId,
    };
  }
}
