// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { RubrosRubrosdialog, CreateRubrosRubrosdialog, UpdateRubrosRubrosdialog, RubrosRubrosdialogFilter, RubrosRubrosdialogPageResult } from '../../../../domain/model/RubrosRubrosdialog';
import { RubrosRubrosdialogResponse, RubrosRubrosdialogListResponse, CreateRubrosRubrosdialogRequest, UpdateRubrosRubrosdialogRequest, RubrosRubrosdialogFilterParams } from '../dto/RubrosRubrosdialogDto';

export class RubrosRubrosdialogViewMapper {

  static toDomain(response: RubrosRubrosdialogResponse): RubrosRubrosdialog {
    return {
      idRubro: response.idRubro,
      nombre: response.nombre,
      ambito: response.ambito,
      efecto: response.efecto,
      observaciones: response.observaciones,
      procedimientoCalculo: response.procedimientoCalculo,
      acumulable: response.acumulable,
      rubroHistorico: response.rubroHistorico,
      secuenciaImpresion: response.secuenciaImpresion,
      secuenciaSobregiro: response.secuenciaSobregiro,
      aplicaInterfaz: response.aplicaInterfaz,
      insertaEnLote: response.insertaEnLote,
      carta: response.carta,
      estado: response.estado,
      antiguedadMinima: response.antiguedadMinima,
      numAprobaciones: response.numAprobaciones,
      numAprobacionesNoLocales: response.numAprobacionesNoLocales,
      plazoMaximo: response.plazoMaximo,
      plazoMinimo: response.plazoMinimo,
      montoMaximo: response.montoMaximo,
      verificaEndeudamiento: response.verificaEndeudamiento,
      usuarioCreacion: response.usuarioCreacion,
      fechaCreacion: response.fechaCreacion,
      usuarioActualizacion: response.usuarioActualizacion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toPageResult(listResponse: RubrosRubrosdialogListResponse): RubrosRubrosdialogPageResult {
    return {
      items: listResponse.content.map(RubrosRubrosdialogViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateRubrosRubrosdialog): CreateRubrosRubrosdialogRequest {
    return {
      idRubro: model.idRubro,
      nombre: model.nombre,
      ambito: model.ambito,
      efecto: model.efecto,
      observaciones: model.observaciones,
      procedimientoCalculo: model.procedimientoCalculo,
      acumulable: model.acumulable,
      rubroHistorico: model.rubroHistorico,
      secuenciaImpresion: model.secuenciaImpresion,
      secuenciaSobregiro: model.secuenciaSobregiro,
      aplicaInterfaz: model.aplicaInterfaz,
      insertaEnLote: model.insertaEnLote,
      carta: model.carta,
      antiguedadMinima: model.antiguedadMinima,
      numAprobaciones: model.numAprobaciones,
      numAprobacionesNoLocales: model.numAprobacionesNoLocales,
      plazoMaximo: model.plazoMaximo,
      plazoMinimo: model.plazoMinimo,
      montoMaximo: model.montoMaximo,
      verificaEndeudamiento: model.verificaEndeudamiento,
    };
  }

  static toUpdateRequest(model: UpdateRubrosRubrosdialog): UpdateRubrosRubrosdialogRequest {
    return {
      nombre: model.nombre,
      ambito: model.ambito,
      efecto: model.efecto,
      observaciones: model.observaciones,
      procedimientoCalculo: model.procedimientoCalculo,
      acumulable: model.acumulable,
      rubroHistorico: model.rubroHistorico,
      secuenciaImpresion: model.secuenciaImpresion,
      secuenciaSobregiro: model.secuenciaSobregiro,
      aplicaInterfaz: model.aplicaInterfaz,
      insertaEnLote: model.insertaEnLote,
      carta: model.carta,
      antiguedadMinima: model.antiguedadMinima,
      numAprobaciones: model.numAprobaciones,
      numAprobacionesNoLocales: model.numAprobacionesNoLocales,
      plazoMaximo: model.plazoMaximo,
      plazoMinimo: model.plazoMinimo,
      montoMaximo: model.montoMaximo,
      verificaEndeudamiento: model.verificaEndeudamiento,
    };
  }

  static toFilterParams(filter: RubrosRubrosdialogFilter): RubrosRubrosdialogFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      idRubro: filter.idRubro,
      nombre: filter.nombre,
      efecto: filter.efecto,
      ambito: filter.ambito,
    };
  }
}
