// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosidomain, CreateRubrosidomain, UpdateRubrosidomain, RubrosidomainFilter, RubrosidomainPageResult } from '../../../../domain/model/Rubrosidomain';
import { RubrosidomainResponse, RubrosidomainListResponse, CreateRubrosidomainRequest, UpdateRubrosidomainRequest, RubrosidomainFilterParams } from '../dto/RubrosidomainDto';

export class RubrosidomainViewMapper {

  static toDomain(response: RubrosidomainResponse): Rubrosidomain {
    return {
      id: response.id,
      dfechapagocaja: response.dfechapagocaja,
      rubroId: response.rubroId,
      colaboradorId: response.colaboradorId,
      empresaId: response.empresaId,
      centroCostoId: response.centroCostoId,
      localidadId: response.localidadId,
      neroId: response.neroId,
      rolId: response.rolId,
      tipoComportamiento: response.tipoComportamiento,
      valor01: response.valor01,
      valor02: response.valor02,
      valor03: response.valor03,
      cartaImpresion: response.cartaImpresion,
      flagEnvio: response.flagEnvio,
      generarCarta: response.generarCarta,
      estadoCaja: response.estadoCaja,
      usuarioCaja: response.usuarioCaja,
      estado: response.estado,
      fechaDesde: response.fechaDesde,
      fechaHasta: response.fechaHasta,
      nombreColaborador: response.nombreColaborador,
      nombreRubro: response.nombreRubro,
      fechaCreacion: response.fechaCreacion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toPageResult(listResponse: RubrosidomainListResponse): RubrosidomainPageResult {
    return {
      items: listResponse.content.map(RubrosidomainViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateRubrosidomain): CreateRubrosidomainRequest {
    return {
      dfechapagocaja: model.dfechapagocaja,
      rubroId: model.rubroId,
      colaboradorId: model.colaboradorId,
      empresaId: model.empresaId,
      centroCostoId: model.centroCostoId,
      localidadId: model.localidadId,
      neroId: model.neroId,
      rolId: model.rolId,
      tipoComportamiento: model.tipoComportamiento,
      valor01: model.valor01,
      valor02: model.valor02,
      valor03: model.valor03,
      cartaImpresion: model.cartaImpresion,
      flagEnvio: model.flagEnvio,
      generarCarta: model.generarCarta,
      estadoCaja: model.estadoCaja,
      usuarioCaja: model.usuarioCaja,
      estado: model.estado,
      fechaDesde: model.fechaDesde,
      fechaHasta: model.fechaHasta,
    };
  }

  static toUpdateRequest(model: UpdateRubrosidomain): UpdateRubrosidomainRequest {
    return {
      dfechapagocaja: model.dfechapagocaja,
      rubroId: model.rubroId,
      colaboradorId: model.colaboradorId,
      empresaId: model.empresaId,
      centroCostoId: model.centroCostoId,
      localidadId: model.localidadId,
      neroId: model.neroId,
      rolId: model.rolId,
      tipoComportamiento: model.tipoComportamiento,
      valor01: model.valor01,
      valor02: model.valor02,
      valor03: model.valor03,
      cartaImpresion: model.cartaImpresion,
      flagEnvio: model.flagEnvio,
      generarCarta: model.generarCarta,
      estadoCaja: model.estadoCaja,
      usuarioCaja: model.usuarioCaja,
      estado: model.estado,
      fechaDesde: model.fechaDesde,
      fechaHasta: model.fechaHasta,
    };
  }

  static toFilterParams(filter: RubrosidomainFilter): RubrosidomainFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      rubroId: filter.rubroId,
      colaboradorId: filter.colaboradorId,
      empresaId: filter.empresaId,
      estado: filter.estado,
      fechaDesde: filter.fechaDesde,
      fechaHasta: filter.fechaHasta,
    };
  }
}
