// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { RubrosidomainRubrosidolistRubrosidodetail, CreateRubrosidomainRubrosidolistRubrosidodetail, UpdateRubrosidomainRubrosidolistRubrosidodetail, RubrosidomainRubrosidolistRubrosidodetailFilter, RubrosidomainRubrosidolistRubrosidodetailPageResult } from '../../../../domain/model/RubrosidomainRubrosidolistRubrosidodetail';
import { RubrosidomainRubrosidolistRubrosidodetailResponse, RubrosidomainRubrosidolistRubrosidodetailListResponse, CreateRubrosidomainRubrosidolistRubrosidodetailRequest, UpdateRubrosidomainRubrosidolistRubrosidodetailRequest, RubrosidomainRubrosidolistRubrosidodetailFilterParams } from '../dto/RubrosidomainRubrosidolistRubrosidodetailDto';

export class RubrosidomainRubrosidolistRubrosidodetailViewMapper {

  static toDomain(response: RubrosidomainRubrosidolistRubrosidodetailResponse): RubrosidomainRubrosidolistRubrosidodetail {
    return {
      id: response.id,
      rubroId: response.rubroId,
      colaboradorId: response.colaboradorId,
      empresaId: response.empresaId,
      tipoComportamiento: response.tipoComportamiento,
      valor01: response.valor01,
      valor02: response.valor02,
      valor03: response.valor03,
      estado: response.estado,
      fechaDesde: response.fechaDesde,
      fechaHasta: response.fechaHasta,
      nombreColaborador: response.nombreColaborador,
      nombreRubro: response.nombreRubro,
      fechaCreacion: response.fechaCreacion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toPageResult(listResponse: RubrosidomainRubrosidolistRubrosidodetailListResponse): RubrosidomainRubrosidolistRubrosidodetailPageResult {
    return {
      items: listResponse.content.map(RubrosidomainRubrosidolistRubrosidodetailViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateRubrosidomainRubrosidolistRubrosidodetail): CreateRubrosidomainRubrosidolistRubrosidodetailRequest {
    return {
      rubroId: model.rubroId,
      colaboradorId: model.colaboradorId,
      empresaId: model.empresaId,
      tipoComportamiento: model.tipoComportamiento,
      valor01: model.valor01,
      valor02: model.valor02,
      valor03: model.valor03,
      estado: model.estado,
      fechaDesde: model.fechaDesde,
      fechaHasta: model.fechaHasta,
    };
  }

  static toUpdateRequest(model: UpdateRubrosidomainRubrosidolistRubrosidodetail): UpdateRubrosidomainRubrosidolistRubrosidodetailRequest {
    return {
      tipoComportamiento: model.tipoComportamiento,
      valor01: model.valor01,
      valor02: model.valor02,
      valor03: model.valor03,
      estado: model.estado,
      fechaHasta: model.fechaHasta,
    };
  }

  static toFilterParams(filter: RubrosidomainRubrosidolistRubrosidodetailFilter): RubrosidomainRubrosidolistRubrosidodetailFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      rubroId: filter.rubroId,
      colaboradorId: filter.colaboradorId,
      empresaId: filter.empresaId,
      estado: filter.estado,
      fechaDesde: filter.fechaDesde,
      fechaHasta: filter.fechaHasta,
    };
  }
}
