// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosxprocesodialog, CreateRubrosxprocesodialog, UpdateRubrosxprocesodialog, RubrosxprocesodialogFilter, RubrosxprocesodialogPageResult } from '../../../../domain/model/Rubrosxprocesodialog';
import { RubrosxprocesodialogResponse, RubrosxprocesodialogListResponse, CreateRubrosxprocesodialogRequest, UpdateRubrosxprocesodialogRequest, RubrosxprocesodialogFilterParams } from '../dto/RubrosxprocesodialogDto';

export class RubrosxprocesodialogViewMapper {

  static toDomain(response: RubrosxprocesodialogResponse): Rubrosxprocesodialog {
    return {
      id: response.id,
      rubroId: response.rubroId,
      procesoId: response.procesoId,
      secuencia: response.secuencia,
      frecuenciaEjecucion: response.frecuenciaEjecucion,
      activo: response.activo,
      fechaCreacion: response.fechaCreacion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toPageResult(listResponse: RubrosxprocesodialogListResponse): RubrosxprocesodialogPageResult {
    return {
      items: listResponse.content.map(RubrosxprocesodialogViewMapper.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      currentPage: listResponse.number ?? 0,
    };
  }

  static toCreateRequest(model: CreateRubrosxprocesodialog): CreateRubrosxprocesodialogRequest {
    return {
      rubroId: model.rubroId,
      procesoId: model.procesoId,
      secuencia: model.secuencia,
      frecuenciaEjecucion: model.frecuenciaEjecucion,
      activo: model.activo,
    };
  }

  static toUpdateRequest(model: UpdateRubrosxprocesodialog): UpdateRubrosxprocesodialogRequest {
    return {
      secuencia: model.secuencia,
      frecuenciaEjecucion: model.frecuenciaEjecucion,
      activo: model.activo,
    };
  }

  static toFilterParams(filter: RubrosxprocesodialogFilter): RubrosxprocesodialogFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      rubroId: filter.rubroId,
      procesoId: filter.procesoId,
    };
  }
}
