// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosidocargaxproceso, CreateRubrosidocargaxproceso, UpdateRubrosidocargaxproceso, RubrosidocargaxprocesoFilter, RubrosidocargaxprocesoPageResult } from '../../../../domain/model/Rubrosidocargaxproceso';
import { RubrosidocargaxprocesoResponse, RubrosidocargaxprocesoListResponse, CreateRubrosidocargaxprocesoRequest, UpdateRubrosidocargaxprocesoRequest, RubrosidocargaxprocesoFilterParams } from '../dto/RubrosidocargaxprocesoDto';

export class RubrosidocargaxprocesoViewMapper {

  static toDomain(response: RubrosidocargaxprocesoResponse): Rubrosidocargaxproceso {
    return {
      id: response.id,
      procesoId: response.procesoId,
      fechaEjecucion: response.fechaEjecucion,
      estado: response.estado,
      numeroRegistrosCargados: response.numeroRegistrosCargados,
      numeroErrores: response.numeroErrores,
      usuarioEjecucion: response.usuarioEjecucion,
      empresaId: response.empresaId,
      descripcion: response.descripcion,
      fechaCreacion: response.fechaCreacion,
      fechaActualizacion: response.fechaActualizacion,
    };
  }

  static toPageResult(listResponse: RubrosidocargaxprocesoListResponse): RubrosidocargaxprocesoPageResult {
    return {
      items: listResponse.items.map(RubrosidocargaxprocesoViewMapper.toDomain),
      totalElements: listResponse.total,
      totalPages: listResponse.totalPages ?? 0,
      currentPage: listResponse.page ?? 0,
    };
  }

  static toCreateRequest(model: CreateRubrosidocargaxproceso): CreateRubrosidocargaxprocesoRequest {
    return {
      empresaId: model.empresaId,
      rubroId: model.rubroId,
      procesoId: model.procesoId,
      descripcion: model.descripcion,
    };
  }

  static toUpdateRequest(model: UpdateRubrosidocargaxproceso): UpdateRubrosidocargaxprocesoRequest {
    return {
      accion: model.accion,
      fechaAplica: model.fechaAplica,
      estado: model.estado,
    };
  }

  static toFilterParams(filter: RubrosidocargaxprocesoFilter): RubrosidocargaxprocesoFilterParams {
    return {
      page: filter.page,
      size: filter.size,
      empresaId: filter.empresaId,
      rubroId: filter.rubroId,
      estado: filter.estado,
    };
  }
}
