// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { EjecucionproccierreUseCase } from '../port/input/EjecucionproccierreUseCase';
import { EjecucionproccierreGatewayPort } from '../port/output/EjecucionproccierreGatewayPort';
import { CreateEjecucionproccierre, Ejecucionproccierre, EjecucionproccierreFilter, EjecucionproccierrePageResult, UpdateEjecucionproccierre } from '../../domain/model/Ejecucionproccierre';
import { EjecucionproccierreViewMapper } from '@modules/procesos/infrastructure/input/adapter/mapper/EjecucionproccierreViewMapper';

export class EjecucionproccierreApplicationService implements EjecucionproccierreUseCase {
  constructor(private readonly gateway: EjecucionproccierreGatewayPort) {}
  async findById(id: string): Promise<Ejecucionproccierre> { return EjecucionproccierreViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: EjecucionproccierreFilter): Promise<EjecucionproccierrePageResult> { return EjecucionproccierreViewMapper.toPageResult(await this.gateway.findAll(filter ? EjecucionproccierreViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateEjecucionproccierre): Promise<Ejecucionproccierre> { return EjecucionproccierreViewMapper.toDomain(await this.gateway.create(EjecucionproccierreViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateEjecucionproccierre): Promise<Ejecucionproccierre> { return EjecucionproccierreViewMapper.toDomain(await this.gateway.update(id, EjecucionproccierreViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { await this.gateway.remove(id); }
  async cerrar(id: string, request: CreateEjecucionproccierre): Promise<{ success: boolean; message: string }> { return this.gateway.cerrar(id, EjecucionproccierreViewMapper.toCreateRequest(request)); }
  async reabrir(id: string, request: UpdateEjecucionproccierre): Promise<{ success: boolean; message: string }> { return this.gateway.reabrir(id, EjecucionproccierreViewMapper.toUpdateRequest(request)); }
}
