// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { EjecucionbotUseCase } from '../port/input/EjecucionbotUseCase';
import { EjecucionbotGatewayPort } from '../port/output/EjecucionbotGatewayPort';
import { CreateEjecucionbot, Ejecucionbot, EjecucionbotFilter, EjecucionbotPageResult, UpdateEjecucionbot } from '../../domain/model/Ejecucionbot';
import { EjecucionbotViewMapper } from '../../infrastructure/input/adapter/mapper/EjecucionbotViewMapper';

export class EjecucionbotApplicationService implements EjecucionbotUseCase {
  constructor(private readonly gateway: EjecucionbotGatewayPort) {}
  async findById(id: string): Promise<Ejecucionbot> { return EjecucionbotViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: EjecucionbotFilter): Promise<EjecucionbotPageResult> { return EjecucionbotViewMapper.toPageResult(await this.gateway.findAll(filter ? EjecucionbotViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateEjecucionbot): Promise<Ejecucionbot> { return EjecucionbotViewMapper.toDomain(await this.gateway.create(EjecucionbotViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateEjecucionbot): Promise<Ejecucionbot> { return EjecucionbotViewMapper.toDomain(await this.gateway.update(id, EjecucionbotViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { await this.gateway.remove(id); }
}
