// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { InstanciasprocesosInstanciasprocesosdialogUseCase } from '../port/input/InstanciasprocesosInstanciasprocesosdialogUseCase';
import { InstanciasprocesosInstanciasprocesosdialogGatewayPort } from '../port/output/InstanciasprocesosInstanciasprocesosdialogGatewayPort';
import { CreateInstanciasprocesosInstanciasprocesosdialog, InstanciasprocesosInstanciasprocesosdialog, InstanciasprocesosInstanciasprocesosdialogFilter, InstanciasprocesosInstanciasprocesosdialogPageResult, UpdateInstanciasprocesosInstanciasprocesosdialog } from '../../domain/model/InstanciasprocesosInstanciasprocesosdialog';
import { InstanciasprocesosInstanciasprocesosdialogViewMapper } from '../../infrastructure/input/adapter/mapper/InstanciasprocesosInstanciasprocesosdialogViewMapper';

export class InstanciasprocesosInstanciasprocesosdialogApplicationService implements InstanciasprocesosInstanciasprocesosdialogUseCase {
  constructor(private readonly gateway: InstanciasprocesosInstanciasprocesosdialogGatewayPort) {}
  async findById(id: string): Promise<InstanciasprocesosInstanciasprocesosdialog> { return InstanciasprocesosInstanciasprocesosdialogViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: InstanciasprocesosInstanciasprocesosdialogFilter): Promise<InstanciasprocesosInstanciasprocesosdialogPageResult> { return InstanciasprocesosInstanciasprocesosdialogViewMapper.toPageResult(await this.gateway.findAll(filter ? InstanciasprocesosInstanciasprocesosdialogViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateInstanciasprocesosInstanciasprocesosdialog): Promise<InstanciasprocesosInstanciasprocesosdialog> { return InstanciasprocesosInstanciasprocesosdialogViewMapper.toDomain(await this.gateway.create(InstanciasprocesosInstanciasprocesosdialogViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateInstanciasprocesosInstanciasprocesosdialog): Promise<InstanciasprocesosInstanciasprocesosdialog> { return InstanciasprocesosInstanciasprocesosdialogViewMapper.toDomain(await this.gateway.update(id, InstanciasprocesosInstanciasprocesosdialogViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { await this.gateway.remove(id); }
}
