// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { LogderegistrosdeprocesosubrecursoUseCase } from '../port/input/LogderegistrosdeprocesosubrecursoUseCase';
import { LogderegistrosdeprocesosubrecursoGatewayPort } from '../port/output/LogderegistrosdeprocesosubrecursoGatewayPort';
import { CreateLogderegistrosdeprocesosubrecurso, Logderegistrosdeprocesosubrecurso, LogderegistrosdeprocesosubrecursoFilter, LogderegistrosdeprocesosubrecursoPageResult, UpdateLogderegistrosdeprocesosubrecurso } from '../../domain/model/Logderegistrosdeprocesosubrecurso';
import { LogderegistrosdeprocesosubrecursoViewMapper } from '../../infrastructure/input/adapter/mapper/LogderegistrosdeprocesosubrecursoViewMapper';

export class LogderegistrosdeprocesosubrecursoApplicationService implements LogderegistrosdeprocesosubrecursoUseCase {
  constructor(private readonly gateway: LogderegistrosdeprocesosubrecursoGatewayPort) {}
  async findById(id: string): Promise<Logderegistrosdeprocesosubrecurso> { return LogderegistrosdeprocesosubrecursoViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter: LogderegistrosdeprocesosubrecursoFilter): Promise<LogderegistrosdeprocesosubrecursoPageResult> { return LogderegistrosdeprocesosubrecursoViewMapper.toPageResult(await this.gateway.findAll(LogderegistrosdeprocesosubrecursoViewMapper.toFilterParams(filter))); }
  async create(model: CreateLogderegistrosdeprocesosubrecurso): Promise<Logderegistrosdeprocesosubrecurso> { return LogderegistrosdeprocesosubrecursoViewMapper.toDomain(await this.gateway.create(LogderegistrosdeprocesosubrecursoViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateLogderegistrosdeprocesosubrecurso): Promise<Logderegistrosdeprocesosubrecurso> { return LogderegistrosdeprocesosubrecursoViewMapper.toDomain(await this.gateway.update(id, LogderegistrosdeprocesosubrecursoViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { await this.gateway.remove(id); }
  async clear(ejecucionId: string): Promise<void> { await this.gateway.clear(ejecucionId); }
}
