// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { ProcesosejecucionreversionProcesosejecucionreversiondialogUseCase } from '../port/input/ProcesosejecucionreversionProcesosejecucionreversiondialogUseCase';
import { ProcesosejecucionreversionProcesosejecucionreversiondialogGatewayPort } from '../port/output/ProcesosejecucionreversionProcesosejecucionreversiondialogGatewayPort';
import { CreateProcesosejecucionreversionProcesosejecucionreversiondialog, ProcesosejecucionreversionProcesosejecucionreversiondialog, ProcesosejecucionreversionProcesosejecucionreversiondialogFilter, ProcesosejecucionreversionProcesosejecucionreversiondialogPageResult, UpdateProcesosejecucionreversionProcesosejecucionreversiondialog } from '../../domain/model/ProcesosejecucionreversionProcesosejecucionreversiondialog';
import { ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper } from '@modules/procesos/infrastructure/input/adapter/mapper/ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper';
import { ProcesosejecucionreversionProcesosejecucionreversiondialogValidationError } from '../../domain/exception/ProcesosejecucionreversionProcesosejecucionreversiondialogError';

export class ProcesosejecucionreversionProcesosejecucionreversiondialogApplicationService implements ProcesosejecucionreversionProcesosejecucionreversiondialogUseCase {
  constructor(private readonly gateway: ProcesosejecucionreversionProcesosejecucionreversiondialogGatewayPort) {}
  async findById(id: string): Promise<ProcesosejecucionreversionProcesosejecucionreversiondialog> { if (!id.trim()) throw new ProcesosejecucionreversionProcesosejecucionreversiondialogValidationError('id requerido'); return ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: ProcesosejecucionreversionProcesosejecucionreversiondialogFilter): Promise<ProcesosejecucionreversionProcesosejecucionreversiondialogPageResult> { return ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper.toPageResult(await this.gateway.findAll(filter ? ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateProcesosejecucionreversionProcesosejecucionreversiondialog): Promise<ProcesosejecucionreversionProcesosejecucionreversiondialog> { return ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper.toDomain(await this.gateway.create(ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateProcesosejecucionreversionProcesosejecucionreversiondialog): Promise<ProcesosejecucionreversionProcesosejecucionreversiondialog> { if (!id.trim()) throw new ProcesosejecucionreversionProcesosejecucionreversiondialogValidationError('id requerido'); return ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper.toDomain(await this.gateway.update(id, ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { if (!id.trim()) throw new ProcesosejecucionreversionProcesosejecucionreversiondialogValidationError('id requerido'); await this.gateway.remove(id); }
  async revertir(id: string, request: { motivo?: string; empresaId?: number }): Promise<{ success: boolean; message: string }> { return this.gateway.revertir(id, request); }
  async listSobregiros(id: string, colaboradorId?: number, rubroId?: string): Promise<{ items: Array<{ ejecucionId: number; colaboradorId: number; rubroId: string; valor?: number; descripcion?: string }>; total: number }> { return this.gateway.listSobregiros(id, colaboradorId, rubroId); }
}
