// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { ProcesosejeccolaboradoresUseCase } from '../port/input/ProcesosejeccolaboradoresUseCase';
import { ProcesosejeccolaboradoresGatewayPort } from '../port/output/ProcesosejeccolaboradoresGatewayPort';
import { CreateProcesosejeccolaboradores, Procesosejeccolaboradores, ProcesosejeccolaboradoresFilter, ProcesosejeccolaboradoresPageResult, UpdateProcesosejeccolaboradores } from '../../domain/model/Procesosejeccolaboradores';
import { ProcesosejeccolaboradoresViewMapper } from '@modules/procesos/infrastructure/input/adapter/mapper/ProcesosejeccolaboradoresViewMapper';
import { ProcesosejeccolaboradoresValidationError } from '../../domain/exception/ProcesosejeccolaboradoresError';

export class ProcesosejeccolaboradoresApplicationService implements ProcesosejeccolaboradoresUseCase {
  constructor(private readonly gateway: ProcesosejeccolaboradoresGatewayPort) {}
  async findById(id: string): Promise<Procesosejeccolaboradores> { if (!id.trim()) throw new ProcesosejeccolaboradoresValidationError('id requerido'); return ProcesosejeccolaboradoresViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter: ProcesosejeccolaboradoresFilter): Promise<ProcesosejeccolaboradoresPageResult> { return ProcesosejeccolaboradoresViewMapper.toPageResult(await this.gateway.findAll(ProcesosejeccolaboradoresViewMapper.toFilterParams(filter))); }
  async create(model: CreateProcesosejeccolaboradores): Promise<Procesosejeccolaboradores> { return ProcesosejeccolaboradoresViewMapper.toDomain(await this.gateway.create(ProcesosejeccolaboradoresViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateProcesosejeccolaboradores): Promise<Procesosejeccolaboradores> { if (!id.trim()) throw new ProcesosejeccolaboradoresValidationError('id requerido'); return ProcesosejeccolaboradoresViewMapper.toDomain(await this.gateway.update(id, ProcesosejeccolaboradoresViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { if (!id.trim()) throw new ProcesosejeccolaboradoresValidationError('id requerido'); await this.gateway.remove(id); }
  async listRubros(ejecucionId: string, colaboradorId: string): Promise<{ items: Array<{ rubroId: string; valor?: number; descripcion?: string }>; total: number }> { return this.gateway.listRubros(ejecucionId, colaboradorId); }
  async ejecutarColaborador(ejecucionId: string, request: { colaboradorId: number; empresaId: number }): Promise<{ success: boolean; message: string }> { return this.gateway.ejecutarColaborador(ejecucionId, request); }
}
