// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { ProcesosejecucionProcesosejecdialogUseCase } from '../port/input/ProcesosejecucionProcesosejecdialogUseCase';
import { ProcesosejecucionProcesosejecdialogGatewayPort } from '../port/output/ProcesosejecucionProcesosejecdialogGatewayPort';
import { CreateProcesosejecucionProcesosejecdialog, ProcesosejecucionProcesosejecdialog, ProcesosejecucionProcesosejecdialogFilter, ProcesosejecucionProcesosejecdialogPageResult, UpdateProcesosejecucionProcesosejecdialog } from '../../domain/model/ProcesosejecucionProcesosejecdialog';
import { ProcesosejecucionProcesosejecdialogViewMapper } from '@modules/procesos/infrastructure/input/adapter/mapper/ProcesosejecucionProcesosejecdialogViewMapper';
import { ProcesosejecucionProcesosejecdialogValidationError } from '../../domain/exception/ProcesosejecucionProcesosejecdialogError';

export class ProcesosejecucionProcesosejecdialogApplicationService implements ProcesosejecucionProcesosejecdialogUseCase {
  constructor(private readonly gateway: ProcesosejecucionProcesosejecdialogGatewayPort) {}
  async findById(id: string): Promise<ProcesosejecucionProcesosejecdialog> { if (!id.trim()) throw new ProcesosejecucionProcesosejecdialogValidationError('id requerido'); return ProcesosejecucionProcesosejecdialogViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: ProcesosejecucionProcesosejecdialogFilter): Promise<ProcesosejecucionProcesosejecdialogPageResult> { return ProcesosejecucionProcesosejecdialogViewMapper.toPageResult(await this.gateway.findAll(filter ? ProcesosejecucionProcesosejecdialogViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateProcesosejecucionProcesosejecdialog): Promise<ProcesosejecucionProcesosejecdialog> { return ProcesosejecucionProcesosejecdialogViewMapper.toDomain(await this.gateway.create(ProcesosejecucionProcesosejecdialogViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateProcesosejecucionProcesosejecdialog): Promise<ProcesosejecucionProcesosejecdialog> { if (!id.trim()) throw new ProcesosejecucionProcesosejecdialogValidationError('id requerido'); return ProcesosejecucionProcesosejecdialogViewMapper.toDomain(await this.gateway.update(id, ProcesosejecucionProcesosejecdialogViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { if (!id.trim()) throw new ProcesosejecucionProcesosejecdialogValidationError('id requerido'); await this.gateway.remove(id); }
  async ejecutar(id: string, request: { entornoEjecucionId?: number; empresaId?: number }): Promise<{ success: boolean; message: string }> { if (!id.trim()) throw new ProcesosejecucionProcesosejecdialogValidationError('id requerido'); return this.gateway.ejecutar(id, request); }
}
