// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { ProcesosProcesosdialogUseCase } from "../port/input/ProcesosProcesosdialogUseCase";
import { ProcesosProcesosdialogGatewayPort } from "../port/output/ProcesosProcesosdialogGatewayPort";
import {
  CreateProcesosProcesosdialog,
  ProcesosProcesosdialog,
  ProcesosProcesosdialogFilter,
  ProcesosProcesosdialogPageResult,
  UpdateProcesosProcesosdialog,
} from "../../domain/model/ProcesosProcesosdialog";
import { ProcesosProcesosdialogViewMapper } from "@modules/procesos/infrastructure/input/adapter/mapper/ProcesosProcesosdialogViewMapper";
import { ProcesosProcesosdialogValidationError } from "../../domain/exception/ProcesosProcesosdialogError";

export class ProcesosProcesosdialogApplicationService implements ProcesosProcesosdialogUseCase {
  constructor(private readonly gateway: ProcesosProcesosdialogGatewayPort) {}
  async findById(id: string): Promise<ProcesosProcesosdialog> {
    if (!id.trim())
      throw new ProcesosProcesosdialogValidationError("id requerido");
    return ProcesosProcesosdialogViewMapper.toDomain(
      await this.gateway.findById(id),
    );
  }
  async findAll(
    filter?: ProcesosProcesosdialogFilter,
  ): Promise<ProcesosProcesosdialogPageResult> {
    return ProcesosProcesosdialogViewMapper.toPageResult(
      await this.gateway.findAll(
        filter
          ? ProcesosProcesosdialogViewMapper.toFilterParams(filter)
          : undefined,
      ),
    );
  }
  async create(
    model: CreateProcesosProcesosdialog,
  ): Promise<ProcesosProcesosdialog> {
    if (!model.empresaId)
      throw new ProcesosProcesosdialogValidationError("empresaId requerido");
    if (!model.tipoProceso?.trim())
      throw new ProcesosProcesosdialogValidationError("tipoProceso requerido");
    return ProcesosProcesosdialogViewMapper.toDomain(
      await this.gateway.create(
        ProcesosProcesosdialogViewMapper.toCreateRequest(model),
      ),
    );
  }
  async update(
    id: string,
    model: UpdateProcesosProcesosdialog,
  ): Promise<ProcesosProcesosdialog> {
    if (!id.trim())
      throw new ProcesosProcesosdialogValidationError("id requerido");
    return ProcesosProcesosdialogViewMapper.toDomain(
      await this.gateway.update(
        id,
        ProcesosProcesosdialogViewMapper.toUpdateRequest(model),
      ),
    );
  }
  async remove(id: string): Promise<void> {
    if (!id.trim())
      throw new ProcesosProcesosdialogValidationError("id requerido");
    await this.gateway.remove(id);
  }
}
