// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { ProcesosejecaprobarlqUseCase } from '../port/input/ProcesosejecaprobarlqUseCase';
import { ProcesosejecaprobarlqGatewayPort } from '../port/output/ProcesosejecaprobarlqGatewayPort';
import { CreateProcesosejecaprobarlq, Procesosejecaprobarlq, ProcesosejecaprobarlqFilter, ProcesosejecaprobarlqPageResult, UpdateProcesosejecaprobarlq } from '../../domain/model/Procesosejecaprobarlq';
import { ProcesosejecaprobarlqViewMapper } from '@modules/procesos/infrastructure/input/adapter/mapper/ProcesosejecaprobarlqViewMapper';

export class ProcesosejecaprobarlqApplicationService implements ProcesosejecaprobarlqUseCase {
  constructor(private readonly gateway: ProcesosejecaprobarlqGatewayPort) {}
  async findById(id: string): Promise<Procesosejecaprobarlq> { return ProcesosejecaprobarlqViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: ProcesosejecaprobarlqFilter): Promise<ProcesosejecaprobarlqPageResult> { return ProcesosejecaprobarlqViewMapper.toPageResult(await this.gateway.findAll(filter ? ProcesosejecaprobarlqViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateProcesosejecaprobarlq): Promise<{ success: boolean; message: string }> { return this.gateway.create(ProcesosejecaprobarlqViewMapper.toCreateRequest(model)); }
  async update(id: string, model: UpdateProcesosejecaprobarlq): Promise<Procesosejecaprobarlq> { return ProcesosejecaprobarlqViewMapper.toDomain(await this.gateway.update(id, ProcesosejecaprobarlqViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { await this.gateway.remove(id); }
  async rechazar(request: { ejecucionId: number; colaboradorIds: number[] }): Promise<{ success: boolean; message: string }> { return this.gateway.rechazar(request); }
}
