// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { ProcesosejecabrirlqUseCase } from '../port/input/ProcesosejecabrirlqUseCase';
import { ProcesosejecabrirlqGatewayPort } from '../port/output/ProcesosejecabrirlqGatewayPort';
import { CreateProcesosejecabrirlq, Procesosejecabrirlq, ProcesosejecabrirlqFilter, ProcesosejecabrirlqPageResult, UpdateProcesosejecabrirlq } from '../../domain/model/Procesosejecabrirlq';
import { ProcesosejecabrirlqViewMapper } from '@modules/procesos/infrastructure/input/adapter/mapper/ProcesosejecabrirlqViewMapper';

export class ProcesosejecabrirlqApplicationService implements ProcesosejecabrirlqUseCase {
  constructor(private readonly gateway: ProcesosejecabrirlqGatewayPort) {}
  async findById(id: string): Promise<Procesosejecabrirlq> { return ProcesosejecabrirlqViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: ProcesosejecabrirlqFilter): Promise<ProcesosejecabrirlqPageResult> { return ProcesosejecabrirlqViewMapper.toPageResult(await this.gateway.findAll(filter ? ProcesosejecabrirlqViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateProcesosejecabrirlq): Promise<{ success: boolean; message: string }> { return this.gateway.create(ProcesosejecabrirlqViewMapper.toCreateRequest(model)); }
  async update(id: string, model: UpdateProcesosejecabrirlq): Promise<Procesosejecabrirlq> { return ProcesosejecabrirlqViewMapper.toDomain(await this.gateway.update(id, ProcesosejecabrirlqViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { await this.gateway.remove(id); }
}
