// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { RubrospreliquidadossubrecursoUseCase } from '../port/input/RubrospreliquidadossubrecursoUseCase';
import { RubrospreliquidadossubrecursoGatewayPort } from '../port/output/RubrospreliquidadossubrecursoGatewayPort';
import { CreateRubrospreliquidadossubrecurso, Rubrospreliquidadossubrecurso, RubrospreliquidadossubrecursoFilter, RubrospreliquidadossubrecursoPageResult, UpdateRubrospreliquidadossubrecurso } from '../../domain/model/Rubrospreliquidadossubrecurso';
import { RubrospreliquidadossubrecursoViewMapper } from '../../infrastructure/input/adapter/mapper/RubrospreliquidadossubrecursoViewMapper';

export class RubrospreliquidadossubrecursoApplicationService implements RubrospreliquidadossubrecursoUseCase {
  constructor(private readonly gateway: RubrospreliquidadossubrecursoGatewayPort) {}
  async findById(id: string): Promise<Rubrospreliquidadossubrecurso> { return RubrospreliquidadossubrecursoViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: RubrospreliquidadossubrecursoFilter): Promise<RubrospreliquidadossubrecursoPageResult> { return RubrospreliquidadossubrecursoViewMapper.toPageResult(await this.gateway.findAll(filter ? RubrospreliquidadossubrecursoViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateRubrospreliquidadossubrecurso): Promise<Rubrospreliquidadossubrecurso> { return RubrospreliquidadossubrecursoViewMapper.toDomain(await this.gateway.create(RubrospreliquidadossubrecursoViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateRubrospreliquidadossubrecurso): Promise<Rubrospreliquidadossubrecurso> { return RubrospreliquidadossubrecursoViewMapper.toDomain(await this.gateway.update(id, RubrospreliquidadossubrecursoViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { await this.gateway.remove(id); }
}
