// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { SobregiroshistricossubrecursoUseCase } from '../port/input/SobregiroshistricossubrecursoUseCase';
import { SobregiroshistricossubrecursoGatewayPort } from '../port/output/SobregiroshistricossubrecursoGatewayPort';
import { CreateSobregiroshistricossubrecurso, Sobregiroshistricossubrecurso, SobregiroshistricossubrecursoFilter, SobregiroshistricossubrecursoPageResult, UpdateSobregiroshistricossubrecurso } from '../../domain/model/Sobregiroshistricossubrecurso';
import { SobregiroshistricossubrecursoViewMapper } from '../../infrastructure/input/adapter/mapper/SobregiroshistricossubrecursoViewMapper';

export class SobregiroshistricossubrecursoApplicationService implements SobregiroshistricossubrecursoUseCase {
  constructor(private readonly gateway: SobregiroshistricossubrecursoGatewayPort) {}
  async findById(id: string): Promise<Sobregiroshistricossubrecurso> { return SobregiroshistricossubrecursoViewMapper.toDomain(await this.gateway.findById(id)); }
  async findAll(filter?: SobregiroshistricossubrecursoFilter): Promise<SobregiroshistricossubrecursoPageResult> { return SobregiroshistricossubrecursoViewMapper.toPageResult(await this.gateway.findAll(filter ? SobregiroshistricossubrecursoViewMapper.toFilterParams(filter) : undefined)); }
  async create(model: CreateSobregiroshistricossubrecurso): Promise<Sobregiroshistricossubrecurso> { return SobregiroshistricossubrecursoViewMapper.toDomain(await this.gateway.create(SobregiroshistricossubrecursoViewMapper.toCreateRequest(model))); }
  async update(id: string, model: UpdateSobregiroshistricossubrecurso): Promise<Sobregiroshistricossubrecurso> { return SobregiroshistricossubrecursoViewMapper.toDomain(await this.gateway.update(id, SobregiroshistricossubrecursoViewMapper.toUpdateRequest(model))); }
  async remove(id: string): Promise<void> { await this.gateway.remove(id); }
}
