import { CargarubrosidoResponse, CargarubrosidoListResponse, CargarubrosidoLineaListResponse, CreateCargarubrosidoRequest, UpdateCargarubrosidoRequest, CargarubrosidoFilterParams, DeleteResponseDTO, ProcesoResponseDTO, CargaMasivaIDOResultDTO } from '@modules/rubros/infrastructure/input/adapter/dto/CargarubrosidoDto';

/**
 * Gateway Port (Output Port): cargaRubrosIDO.zul
 * Define el contrato de comunicación con la API REST del backend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Endpoints relacionados:
 *   GET /api/v1/rubros-ido/cargas-masivas — Listar cargas masivas IDO
 *   GET /api/v1/rubros-ido/cargas-masivas/{id} — Obtener carga masiva IDO por ID
 *   GET /api/v1/rubros-ido/cargas-masivas/{id}/lineas — Obtener líneas de carga masiva
 *   POST /api/v1/rubros-ido/cargas-masivas — Crear carga masiva IDO
 *   POST /api/v1/rubros-ido/cargas-masivas/{id}/aprobar — Aprobar carga masiva
 *   DELETE /api/v1/rubros-ido/cargas-masivas/{id} — Eliminar carga masiva IDO
 */
export interface CargarubrosidoGatewayPort {
  findById(id: string): Promise<CargarubrosidoResponse>;
  findAll(params?: CargarubrosidoFilterParams): Promise<CargarubrosidoListResponse>;
  create(request: CreateCargarubrosidoRequest): Promise<CargaMasivaIDOResultDTO>;
  update(id: string, request: UpdateCargarubrosidoRequest): Promise<CargarubrosidoResponse>;
  remove(id: string): Promise<DeleteResponseDTO>;
  getLineas(id: string, page?: number, size?: number): Promise<CargarubrosidoLineaListResponse>;
  aprobar(id: string): Promise<ProcesoResponseDTO>;
}
