import { ConsultarubrosidolistResponse, ConsultarubrosidolistListResponse, CreateConsultarubrosidolistRequest, UpdateConsultarubrosidolistRequest, ConsultarubrosidolistFilterParams, DeleteResponseDTO, ExportarConsultaIDORequest, CambiarEstadoIDORequest, ExportarResponseDTO } from '@modules/rubros/infrastructure/input/adapter/dto/ConsultarubrosidolistDto';

/**
 * Gateway Port (Output Port): consultaRubrosIdoList.zul
 * Define el contrato de comunicación con la API REST del backend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Endpoints relacionados:
 *   GET /api/v1/rubros-ido/consulta — Consultar rubros IDO
 *   GET /api/v1/rubros-ido/consulta/{id} — Obtener rubro IDO de consulta por ID
 *   POST /api/v1/rubros-ido/consulta/exportar — Exportar consulta a Excel
 *   PUT /api/v1/rubros-ido/consulta/{id}/estado — Cambiar estado de rubro IDO
 *   DELETE /api/v1/rubros-ido/consulta/{id} — Eliminar rubro IDO desde consulta
 */
export interface ConsultarubrosidolistGatewayPort {
  findById(id: string): Promise<ConsultarubrosidolistResponse>;
  findAll(params?: ConsultarubrosidolistFilterParams): Promise<ConsultarubrosidolistListResponse>;
  create(request: CreateConsultarubrosidolistRequest): Promise<ConsultarubrosidolistResponse>;
  update(id: string, request: UpdateConsultarubrosidolistRequest): Promise<ConsultarubrosidolistResponse>;
  remove(id: string): Promise<DeleteResponseDTO>;
  exportar(request: ExportarConsultaIDORequest): Promise<ExportarResponseDTO>;
  cambiarEstado(id: string, request: CambiarEstadoIDORequest): Promise<ConsultarubrosidolistResponse>;
  findAdvanced(params?: ConsultarubrosidolistFilterParams): Promise<ConsultarubrosidolistListResponse>;
}
