import { RubrosidocargaxprocesoResponse, RubrosidocargaxprocesoListResponse, CreateRubrosidocargaxprocesoRequest, UpdateRubrosidocargaxprocesoRequest, RubrosidocargaxprocesoFilterParams, DeleteResponseDTO, ProcesoResponseDTO } from '@modules/rubros/infrastructure/input/adapter/dto/RubrosidocargaxprocesoDto';

/**
 * Gateway Port (Output Port): rubrosIDOcargaxProceso.zul
 * Define el contrato de comunicación con la API REST del backend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Endpoints relacionados:
 *   GET /api/v1/rubros-ido/cargar-proceso — Listar cargas por proceso
 *   GET /api/v1/rubros-ido/cargar-proceso/{id} — Obtener carga por proceso por ID
 *   POST /api/v1/rubros-ido/cargar-proceso — Ejecutar carga por proceso
 *   PUT /api/v1/rubros-ido/cargar-proceso/{id} — Actualizar carga por proceso
 *   DELETE /api/v1/rubros-ido/cargar-proceso/{id} — Eliminar carga por proceso
 */
export interface RubrosidocargaxprocesoGatewayPort {
  findById(id: string): Promise<RubrosidocargaxprocesoResponse>;
  findAll(params?: RubrosidocargaxprocesoFilterParams): Promise<RubrosidocargaxprocesoListResponse>;
  create(request: CreateRubrosidocargaxprocesoRequest): Promise<RubrosidocargaxprocesoResponse | ProcesoResponseDTO>;
  update(id: string, request: UpdateRubrosidocargaxprocesoRequest): Promise<RubrosidocargaxprocesoResponse>;
  remove(id: string): Promise<DeleteResponseDTO>;
}
