import { RubrosidomainResponse, RubrosidomainListResponse, CreateRubrosidomainRequest, UpdateRubrosidomainRequest, RubrosidomainFilterParams, DeleteResponseDTO } from '@modules/rubros/infrastructure/input/adapter/dto/RubrosidomainDto';

/**
 * Gateway Port (Output Port): rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Define el contrato de comunicación con la API REST del backend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Endpoints relacionados:
 *   GET /api/v1/rubros-ido —Listar rubros IDO
 *   GET /api/v1/rubros-ido/{id} — Obtener rubro IDO por ID
 *   POST /api/v1/rubros-ido — Crear rubro IDO
 *   PUT /api/v1/rubros-ido/{id} — Actualizar rubro IDO
 *   DELETE /api/v1/rubros-ido/{id} — Eliminar rubro IDO
 */
export interface RubrosidomainGatewayPort {
  findById(id: string): Promise<RubrosidomainResponse>;
  findAll(params?: RubrosidomainFilterParams): Promise<RubrosidomainListResponse>;
  create(request: CreateRubrosidomainRequest): Promise<RubrosidomainResponse>;
  update(id: string, request: UpdateRubrosidomainRequest): Promise<RubrosidomainResponse>;
  remove(id: string): Promise<DeleteResponseDTO>;
}
