import { RubrosxprocesodialogResponse, RubrosxprocesodialogListResponse, CreateRubrosxprocesodialogRequest, UpdateRubrosxprocesodialogRequest, RubrosxprocesodialogFilterParams, DeleteResponseDTO } from '@modules/rubros/infrastructure/input/adapter/dto/RubrosxprocesodialogDto';

/**
 * Gateway Port (Output Port): rubrosxprocesoDialog.zul
 * Define el contrato de comunicación con la API REST del backend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Endpoints relacionados:
 *   GET /api/v1/rubros-proceso — Listar asignaciones rubro-proceso
 *   GET /api/v1/rubros-proceso/{id} — Obtener asignación rubro-proceso por ID
 *   POST /api/v1/rubros-proceso — Crear asignación rubro-proceso
 *   PUT /api/v1/rubros-proceso/{id} — Actualizar asignación rubro-proceso
 *   DELETE /api/v1/rubros-proceso/{id} — Eliminar asignación rubro-proceso
 */
export interface RubrosxprocesodialogGatewayPort {
  findById(id: string): Promise<RubrosxprocesodialogResponse>;
  findAll(params?: RubrosxprocesodialogFilterParams): Promise<RubrosxprocesodialogListResponse>;
  create(request: CreateRubrosxprocesodialogRequest): Promise<RubrosxprocesodialogResponse>;
  update(id: string, request: UpdateRubrosxprocesodialogRequest): Promise<RubrosxprocesodialogResponse>;
  remove(id: string): Promise<DeleteResponseDTO>;
}
