import { RubrosRubrosdialogResponse, RubrosRubrosdialogListResponse, CreateRubrosRubrosdialogRequest, UpdateRubrosRubrosdialogRequest, RubrosRubrosdialogFilterParams, DeleteResponseDTO } from '@modules/rubros/infrastructure/input/adapter/dto/RubrosRubrosdialogDto';

/**
 * Gateway Port (Output Port): rubros.zul / rubrosDialog.zul
 * Define el contrato de comunicación con la API REST del backend.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Endpoints relacionados:
 *   GET /api/v1/rubros — Listar rubros
 *   GET /api/v1/rubros/{idRubro} — Obtener rubro por ID
 *   POST /api/v1/rubros — Crear rubro
 *   PUT /api/v1/rubros/{idRubro} — Actualizar rubro
 *   DELETE /api/v1/rubros/{idRubro} — Eliminar rubro
 */
export interface RubrosRubrosdialogGatewayPort {
  findById(id: string): Promise<RubrosRubrosdialogResponse>;
  findAll(params?: RubrosRubrosdialogFilterParams): Promise<RubrosRubrosdialogListResponse>;
  create(request: CreateRubrosRubrosdialogRequest): Promise<RubrosRubrosdialogResponse>;
  update(id: string, request: UpdateRubrosRubrosdialogRequest): Promise<RubrosRubrosdialogResponse>;
  remove(id: string): Promise<DeleteResponseDTO>;
}
