// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Cargarubrosido, CreateCargarubrosido, UpdateCargarubrosido, CargarubrosidoFilter, CargarubrosidoPageResult, CargarubrosidoLineaPageResult } from '@modules/rubros/domain/model/Cargarubrosido';

export interface CargarubrosidoUseCase {
  findById(id: string): Promise<Cargarubrosido>;
  findAll(filter?: CargarubrosidoFilter): Promise<CargarubrosidoPageResult>;
  create(model: CreateCargarubrosido): Promise<Cargarubrosido>;
  update(id: string, model: UpdateCargarubrosido): Promise<Cargarubrosido>;
  remove(id: string): Promise<void>;
  getLineas(id: string, page?: number, size?: number): Promise<CargarubrosidoLineaPageResult>;
  aprobar(id: string): Promise<Cargarubrosido>;
}
