// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Consultarubrosidolist, CreateConsultarubrosidolist, UpdateConsultarubrosidolist, ConsultarubrosidolistFilter, ConsultarubrosidolistPageResult } from '@modules/rubros/domain/model/Consultarubrosidolist';

export interface ConsultarubrosidolistUseCase {
  findById(id: string): Promise<Consultarubrosidolist>;
  findAll(filter?: ConsultarubrosidolistFilter): Promise<ConsultarubrosidolistPageResult>;
  create(model: CreateConsultarubrosidolist): Promise<Consultarubrosidolist>;
  update(id: string, model: UpdateConsultarubrosidolist): Promise<Consultarubrosidolist>;
  remove(id: string): Promise<void>;
  exportar(filter: ConsultarubrosidolistFilter): Promise<Blob>;
  cambiarEstado(id: string, estado: string): Promise<Consultarubrosidolist>;
}

/**
 * Input Port (Use Case): consultaRubrosIdoList.zul
 * Define las operaciones que la capa de aplicación expone a la UI.
 *
 * Casos de uso del slice:
 *   - Crear rubros
 *   - Rubros IDO
 *   - Config cálculo
 *
 * Endpoints API relacionados:
 *   GET /api/v1/rubros-ido/consulta — Consultar rubros IDO
 *   GET /api/v1/rubros-ido/consulta/{id} — Obtener rubro IDO de consulta por ID
 *   POST /api/v1/rubros-ido/consulta/exportar — Exportar consulta a Excel
 *   PUT /api/v1/rubros-ido/consulta/{id}/estado — Cambiar estado de rubro IDO
 *   DELETE /api/v1/rubros-ido/consulta/{id} — Eliminar rubro IDO desde consulta
 *
 * TODO: Copilot — Agrega métodos específicos de negocio basándote en los casos de uso y endpoints.
 */
export interface ConsultarubrosidolistUseCase {

  /**
   * Buscar por ID
   */
  findById(id: string): Promise<Consultarubrosidolist>;

  /**
   * Listar con filtros y paginación
   */
  findAll(filter?: ConsultarubrosidolistFilter): Promise<ConsultarubrosidolistPageResult>;

  /**
   * Crear nuevo
   */
  create(model: CreateConsultarubrosidolist): Promise<Consultarubrosidolist>;

  /**
   * Actualizar existente
   */
  update(id: string, model: UpdateConsultarubrosidolist): Promise<Consultarubrosidolist>;

  /**
   * Eliminar por ID
   */
  remove(id: string): Promise<void>;

  // TODO: Agregar métodos específicos del caso de uso
  // Ejemplo: activar, desactivar, aprobar, rechazar, procesar, etc.
}
