// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosidomain, CreateRubrosidomain, UpdateRubrosidomain, RubrosidomainFilter, RubrosidomainPageResult } from '@modules/rubros/domain/model/Rubrosidomain';

export interface RubrosidomainUseCase {
  findById(id: string): Promise<Rubrosidomain>;
  findAll(filter?: RubrosidomainFilter): Promise<RubrosidomainPageResult>;
  create(model: CreateRubrosidomain): Promise<Rubrosidomain>;
  update(id: string, model: UpdateRubrosidomain): Promise<Rubrosidomain>;
  remove(id: string): Promise<void>;
}

/**
 * Input Port (Use Case): rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Define las operaciones que la capa de aplicación expone a la UI.
 *
 * Casos de uso del slice:
 *   - Crear rubros
 *   - Rubros IDO
 *   - Config cálculo
 *
 * Endpoints API relacionados:
 *
 * TODO: Copilot — Agrega métodos específicos de negocio basándote en los casos de uso y endpoints.
 */
export interface RubrosidomainUseCase {

  /**
   * Buscar por ID
   */
  findById(id: string): Promise<Rubrosidomain>;

  /**
   * Listar con filtros y paginación
   */
  findAll(filter?: RubrosidomainFilter): Promise<RubrosidomainPageResult>;

  /**
   * Crear nuevo
   */
  create(model: CreateRubrosidomain): Promise<Rubrosidomain>;

  /**
   * Actualizar existente
   */
  update(id: string, model: UpdateRubrosidomain): Promise<Rubrosidomain>;

  /**
   * Eliminar por ID
   */
  remove(id: string): Promise<void>;

  // TODO: Agregar métodos específicos del caso de uso
  // Ejemplo: activar, desactivar, aprobar, rechazar, procesar, etc.
}
