// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosxprocesodialog, CreateRubrosxprocesodialog, UpdateRubrosxprocesodialog, RubrosxprocesodialogFilter, RubrosxprocesodialogPageResult } from '@modules/rubros/domain/model/Rubrosxprocesodialog';

export interface RubrosxprocesodialogUseCase {
  findById(id: string): Promise<Rubrosxprocesodialog>;
  findAll(filter?: RubrosxprocesodialogFilter): Promise<RubrosxprocesodialogPageResult>;
  create(model: CreateRubrosxprocesodialog): Promise<Rubrosxprocesodialog>;
  update(id: string, model: UpdateRubrosxprocesodialog): Promise<Rubrosxprocesodialog>;
  remove(id: string): Promise<void>;
}

/**
 * Input Port (Use Case): rubrosxprocesoDialog.zul
 * Define las operaciones que la capa de aplicación expone a la UI.
 *
 * Casos de uso del slice:
 *   - Crear rubros
 *   - Rubros IDO
 *   - Config cálculo
 *
 * Endpoints API relacionados:
 *   GET /api/v1/rubros-proceso — Listar asignaciones rubro-proceso
 *   GET /api/v1/rubros-proceso/{id} — Obtener asignación rubro-proceso por ID
 *   POST /api/v1/rubros-proceso — Crear asignación rubro-proceso
 *   PUT /api/v1/rubros-proceso/{id} — Actualizar asignación rubro-proceso
 *   DELETE /api/v1/rubros-proceso/{id} — Eliminar asignación rubro-proceso
 *
 * TODO: Copilot — Agrega métodos específicos de negocio basándote en los casos de uso y endpoints.
 */
export interface RubrosxprocesodialogUseCase {

  /**
   * Buscar por ID
   */
  findById(id: string): Promise<Rubrosxprocesodialog>;

  /**
   * Listar con filtros y paginación
   */
  findAll(filter?: RubrosxprocesodialogFilter): Promise<RubrosxprocesodialogPageResult>;

  /**
   * Crear nuevo
   */
  create(model: CreateRubrosxprocesodialog): Promise<Rubrosxprocesodialog>;

  /**
   * Actualizar existente
   */
  update(id: string, model: UpdateRubrosxprocesodialog): Promise<Rubrosxprocesodialog>;

  /**
   * Eliminar por ID
   */
  remove(id: string): Promise<void>;

  // TODO: Agregar métodos específicos del caso de uso
  // Ejemplo: activar, desactivar, aprobar, rechazar, procesar, etc.
}
