// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { RubrosRubrosdialog, CreateRubrosRubrosdialog, UpdateRubrosRubrosdialog, RubrosRubrosdialogFilter, RubrosRubrosdialogPageResult } from '@modules/rubros/domain/model/RubrosRubrosdialog';

export interface RubrosRubrosdialogUseCase {
  findById(id: string): Promise<RubrosRubrosdialog>;
  findAll(filter?: RubrosRubrosdialogFilter): Promise<RubrosRubrosdialogPageResult>;
  create(model: CreateRubrosRubrosdialog): Promise<RubrosRubrosdialog>;
  update(id: string, model: UpdateRubrosRubrosdialog): Promise<RubrosRubrosdialog>;
  remove(id: string): Promise<void>;
}
