// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosidocargaxproceso, CreateRubrosidocargaxproceso, UpdateRubrosidocargaxproceso, RubrosidocargaxprocesoFilter, RubrosidocargaxprocesoPageResult } from '@modules/rubros/domain/model/Rubrosidocargaxproceso';

export interface RubrosidocargaxprocesoUseCase {
  findById(id: string): Promise<Rubrosidocargaxproceso>;
  findAll(filter?: RubrosidocargaxprocesoFilter): Promise<RubrosidocargaxprocesoPageResult>;
  create(model: CreateRubrosidocargaxproceso): Promise<Rubrosidocargaxproceso>;
  update(id: string, model: UpdateRubrosidocargaxproceso): Promise<Rubrosidocargaxproceso>;
  remove(id: string): Promise<void>;
  ejecutarCarga(model: CreateRubrosidocargaxproceso): Promise<{ success: boolean; message: string }>;
}

/**
 * Input Port (Use Case): rubrosIDOcargaxProceso.zul
 * Define las operaciones que la capa de aplicación expone a la UI.
 *
 * Casos de uso del slice:
 *   - Crear rubros
 *   - Rubros IDO
 *   - Config cálculo
 *
 * Endpoints API relacionados:
 *   GET /api/v1/rubros-ido/cargar-proceso — Listar cargas por proceso
 *   GET /api/v1/rubros-ido/cargar-proceso/{id} — Obtener carga por proceso por ID
 *   POST /api/v1/rubros-ido/cargar-proceso — Ejecutar carga por proceso
 *   PUT /api/v1/rubros-ido/cargar-proceso/{id} — Actualizar carga por proceso
 *   DELETE /api/v1/rubros-ido/cargar-proceso/{id} — Eliminar carga por proceso
 *
 * TODO: Copilot — Agrega métodos específicos de negocio basándote en los casos de uso y endpoints.
 */
export interface RubrosidocargaxprocesoUseCase {

  /**
   * Buscar por ID
   */
  findById(id: string): Promise<Rubrosidocargaxproceso>;

  /**
   * Listar con filtros y paginación
   */
  findAll(filter?: RubrosidocargaxprocesoFilter): Promise<RubrosidocargaxprocesoPageResult>;

  /**
   * Crear nuevo
   */
  create(model: CreateRubrosidocargaxproceso): Promise<Rubrosidocargaxproceso>;

  /**
   * Actualizar existente
   */
  update(id: string, model: UpdateRubrosidocargaxproceso): Promise<Rubrosidocargaxproceso>;

  /**
   * Eliminar por ID
   */
  remove(id: string): Promise<void>;

  // TODO: Agregar métodos específicos del caso de uso
  // Ejemplo: activar, desactivar, aprobar, rechazar, procesar, etc.
}
