// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { RubrosidomainRubrosidolistRubrosidodetail, CreateRubrosidomainRubrosidolistRubrosidodetail, UpdateRubrosidomainRubrosidolistRubrosidodetail, RubrosidomainRubrosidolistRubrosidodetailFilter, RubrosidomainRubrosidolistRubrosidodetailPageResult } from '@modules/rubros/domain/model/RubrosidomainRubrosidolistRubrosidodetail';

export interface RubrosidomainRubrosidolistRubrosidodetailUseCase {
  findById(id: string): Promise<RubrosidomainRubrosidolistRubrosidodetail>;
  findAll(filter?: RubrosidomainRubrosidolistRubrosidodetailFilter): Promise<RubrosidomainRubrosidolistRubrosidodetailPageResult>;
  create(model: CreateRubrosidomainRubrosidolistRubrosidodetail): Promise<RubrosidomainRubrosidolistRubrosidodetail>;
  update(id: string, model: UpdateRubrosidomainRubrosidolistRubrosidodetail): Promise<RubrosidomainRubrosidolistRubrosidodetail>;
  remove(id: string): Promise<void>;
}

/**
 * Input Port (Use Case): rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Define las operaciones que la capa de aplicación expone a la UI.
 *
 * Casos de uso del slice:
 *   - Crear rubros
 *   - Rubros IDO
 *   - Config cálculo
 *
 * Endpoints API relacionados:
 *
 * TODO: Copilot — Agrega métodos específicos de negocio basándote en los casos de uso y endpoints.
 */
export interface RubrosidomainRubrosidolistRubrosidodetailUseCase {

  /**
   * Buscar por ID
   */
  findById(id: string): Promise<RubrosidomainRubrosidolistRubrosidodetail>;

  /**
   * Listar con filtros y paginación
   */
  findAll(filter?: RubrosidomainRubrosidolistRubrosidodetailFilter): Promise<RubrosidomainRubrosidolistRubrosidodetailPageResult>;

  /**
   * Crear nuevo
   */
  create(model: CreateRubrosidomainRubrosidolistRubrosidodetail): Promise<RubrosidomainRubrosidolistRubrosidodetail>;

  /**
   * Actualizar existente
   */
  update(id: string, model: UpdateRubrosidomainRubrosidolistRubrosidodetail): Promise<RubrosidomainRubrosidolistRubrosidodetail>;

  /**
   * Eliminar por ID
   */
  remove(id: string): Promise<void>;

  // TODO: Agregar métodos específicos del caso de uso
  // Ejemplo: activar, desactivar, aprobar, rechazar, procesar, etc.
}
