// Components barrel — auto-generated
export { ParametrosParametrosdialogList } from './ParametrosParametrosdialogList';
export { ParametrosParametrosdialogForm } from './ParametrosParametrosdialogForm';
export { ParametrosParametrosdialogDetail } from './ParametrosParametrosdialogDetail';
export { ParametrosParametrosdialogCard } from './ParametrosParametrosdialogCard';
export { GestiontablairGestiontablairdialogList } from './GestiontablairGestiontablairdialogList';
export { GestiontablairGestiontablairdialogForm } from './GestiontablairGestiontablairdialogForm';
export { GestiontablairGestiontablairdialogDetail } from './GestiontablairGestiontablairdialogDetail';
export { GestiontablairGestiontablairdialogCard } from './GestiontablairGestiontablairdialogCard';
export { GastospersonalesdialogList } from './GastospersonalesdialogList';
export { GastospersonalesdialogForm } from './GastospersonalesdialogForm';
export { GastospersonalesdialogDetail } from './GastospersonalesdialogDetail';
export { GastospersonalesdialogCard } from './GastospersonalesdialogCard';
export { GeningproyectadosList } from './GeningproyectadosList';
export { GeningproyectadosForm } from './GeningproyectadosForm';
export { GeningproyectadosDetail } from './GeningproyectadosDetail';
export { GeningproyectadosCard } from './GeningproyectadosCard';
export { ReporteirinecdialogList } from './ReporteirinecdialogList';
export { ReporteirinecdialogForm } from './ReporteirinecdialogForm';
export { ReporteirinecdialogDetail } from './ReporteirinecdialogDetail';
export { ReporteirinecdialogCard } from './ReporteirinecdialogCard';
export { PlantillacontablePlantillacontabledialogList } from './PlantillacontablePlantillacontabledialogList';
export { PlantillacontablePlantillacontabledialogForm } from './PlantillacontablePlantillacontabledialogForm';
export { PlantillacontablePlantillacontabledialogDetail } from './PlantillacontablePlantillacontabledialogDetail';
export { PlantillacontablePlantillacontabledialogCard } from './PlantillacontablePlantillacontabledialogCard';
export { RubroplantillacontabledialogList } from './RubroplantillacontabledialogList';
export { RubroplantillacontabledialogForm } from './RubroplantillacontabledialogForm';
export { RubroplantillacontabledialogDetail } from './RubroplantillacontabledialogDetail';
export { RubroplantillacontabledialogCard } from './RubroplantillacontabledialogCard';
export { ContratoplantillaContratoplantilladialogList } from './ContratoplantillaContratoplantilladialogList';
export { ContratoplantillaContratoplantilladialogForm } from './ContratoplantillaContratoplantilladialogForm';
export { ContratoplantillaContratoplantilladialogDetail } from './ContratoplantillaContratoplantilladialogDetail';
export { ContratoplantillaContratoplantilladialogCard } from './ContratoplantillaContratoplantilladialogCard';
export * from './SetupForm';
export * from './SetupList';
