/**
 * Domain Exceptions: Ejecucionbot
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class EjecucionbotNotFoundError extends AppError {
  constructor(id: string) {
    super('EJECUCIONBOT_NOT_FOUND', 404, `Bot de ejecución con ID ${id} no encontrado`);
  }
}

export class EjecucionbotValidationError extends AppError {
  constructor(message: string) {
    super('EJECUCIONBOT_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class EjecucionbotDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('EJECUCIONBOT_DUPLICATE', 409, `Ya existe un bot con ${field}: ${value}`);
  }
}

export class EjecucionbotBusinessRuleError extends AppError {
  constructor(message: string) {
    super('EJECUCIONBOT_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
