/**
 * Domain Exceptions: Ejecucionproccierre
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class EjecucionproccierreNotFoundError extends AppError {
  constructor(id: string) {
    super('EJECUCIONPROCCIERRE_NOT_FOUND', 404, `Cierre de proceso con ID ${id} no encontrado`);
  }
}

export class EjecucionproccierreValidationError extends AppError {
  constructor(message: string) {
    super('EJECUCIONPROCCIERRE_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class EjecucionproccierreDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('EJECUCIONPROCCIERRE_DUPLICATE', 409, `Ya existe un cierre con ${field}: ${value}`);
  }
}

export class EjecucionproccierreBusinessRuleError extends AppError {
  constructor(message: string) {
    super('EJECUCIONPROCCIERRE_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
