/**
 * Domain Exceptions: InstanciasprocesosInstanciasprocesosdialog
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class InstanciasprocesosInstanciasprocesosdialogNotFoundError extends AppError {
  constructor(id: string) {
    super('INSTANCIASPROCESOS_NOT_FOUND', 404, `Instancia de proceso con ID ${id} no encontrada`);
  }
}

export class InstanciasprocesosInstanciasprocesosdialogValidationError extends AppError {
  constructor(message: string) {
    super('INSTANCIASPROCESOS_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class InstanciasprocesosInstanciasprocesosdialogDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('INSTANCIASPROCESOS_DUPLICATE', 409, `Ya existe una instancia con ${field}: ${value}`);
  }
}

export class InstanciasprocesosInstanciasprocesosdialogBusinessRuleError extends AppError {
  constructor(message: string) {
    super('INSTANCIASPROCESOS_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
