/**
 * Domain Exceptions: Logderegistrosdeprocesosubrecurso
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class LogderegistrosdeprocesosubrecursoNotFoundError extends AppError {
  constructor(id: string) {
    super('LOGDEREGISTROS_NOT_FOUND', 404, `Registro de log con ID ${id} no encontrado`);
  }
}

export class LogderegistrosdeprocesosubrecursoValidationError extends AppError {
  constructor(message: string) {
    super('LOGDEREGISTROS_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class LogderegistrosdeprocesosubrecursoDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('LOGDEREGISTROS_DUPLICATE', 409, `Ya existe un registro con ${field}: ${value}`);
  }
}

export class LogderegistrosdeprocesosubrecursoBusinessRuleError extends AppError {
  constructor(message: string) {
    super('LOGDEREGISTROS_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
