/**
 * Domain Exceptions: Procesosejeccolaboradores
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class ProcesosejeccolaboradoresNotFoundError extends AppError {
  constructor(id: string) {
    super('PROCESOSEJECCOLABORADORES_NOT_FOUND', 404, `Ejecución de colaborador con ID ${id} no encontrada`);
  }
}

export class ProcesosejeccolaboradoresValidationError extends AppError {
  constructor(message: string) {
    super('PROCESOSEJECCOLABORADORES_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class ProcesosejeccolaboradoresDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('PROCESOSEJECCOLABORADORES_DUPLICATE', 409, `Ya existe un registro con ${field}: ${value}`);
  }
}

export class ProcesosejeccolaboradoresBusinessRuleError extends AppError {
  constructor(message: string) {
    super('PROCESOSEJECCOLABORADORES_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
