/**
 * Domain Exceptions: ProcesosejecucionProcesosejecdialog
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class ProcesosejecucionProcesosejecdialogNotFoundError extends AppError {
  constructor(id: string) {
    super('PROCESOS_EJECUCION_NOT_FOUND', 404, `Ejecución de proceso con ID ${id} no encontrada`);
  }
}

export class ProcesosejecucionProcesosejecdialogValidationError extends AppError {
  constructor(message: string) {
    super('PROCESOS_EJECUCION_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class ProcesosejecucionProcesosejecdialogDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('PROCESOS_EJECUCION_DUPLICATE', 409, `Ya existe una ejecución con ${field}: ${value}`);
  }
}

export class ProcesosejecucionProcesosejecdialogBusinessRuleError extends AppError {
  constructor(message: string) {
    super('PROCESOS_EJECUCION_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
