/**
 * Domain Exceptions: ProcesosejecucionreversionProcesosejecucionreversiondialog
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class ProcesosejecucionreversionProcesosejecucionreversiondialogNotFoundError extends AppError {
  constructor(id: string) {
    super('PROCESOSEJECUCIONREVERSION_NOT_FOUND', 404, `Reversión con ID ${id} no encontrada`);
  }
}

export class ProcesosejecucionreversionProcesosejecucionreversiondialogValidationError extends AppError {
  constructor(message: string) {
    super('PROCESOSEJECUCIONREVERSION_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class ProcesosejecucionreversionProcesosejecucionreversiondialogDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('PROCESOSEJECUCIONREVERSION_DUPLICATE', 409, `Ya existe una reversión con ${field}: ${value}`);
  }
}

export class ProcesosejecucionreversionProcesosejecucionreversiondialogBusinessRuleError extends AppError {
  constructor(message: string) {
    super('PROCESOSEJECUCIONREVERSION_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
