/**
 * Domain Exceptions: Procesosejecabrirlq
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class ProcesosejecabrirlqNotFoundError extends AppError {
  constructor(id: string) {
    super('PROCESOSEJECABRIRLQ_NOT_FOUND', 404, `Apertura de liquidación con ID ${id} no encontrada`);
  }
}

export class ProcesosejecabrirlqValidationError extends AppError {
  constructor(message: string) {
    super('PROCESOSEJECABRIRLQ_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class ProcesosejecabrirlqDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('PROCESOSEJECABRIRLQ_DUPLICATE', 409, `Ya existe una apertura con ${field}: ${value}`);
  }
}

export class ProcesosejecabrirlqBusinessRuleError extends AppError {
  constructor(message: string) {
    super('PROCESOSEJECABRIRLQ_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
