/**
 * Domain Exceptions: ProcesosProcesosdialog
 * Errores de negocio específicos para Procesos
 * 
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class ProcesosProcesosdialogNotFoundError extends AppError {
  constructor(id: string) {
    super('PROCESOS_PROCESOSDIALOG_NOT_FOUND', 404, `Proceso con ID ${id} no encontrado`);
  }
}

export class ProcesosProcesosdialogValidationError extends AppError {
  constructor(message: string) {
    super('PROCESOS_PROCESOSDIALOG_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class ProcesosProcesosdialogDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('PROCESOS_PROCESOSDIALOG_DUPLICATE', 409, `Ya existe un proceso con ${field}: ${value}`);
  }
}

export class ProcesosProcesosdialogBusinessRuleError extends AppError {
  constructor(message: string) {
    super('PROCESOS_PROCESOSDIALOG_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
