/**
 * Domain Exceptions: Procesosejecaprobarlq
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class ProcesosejecaprobarlqNotFoundError extends AppError {
  constructor(id: string) {
    super('PROCESOSEJECAPROBARLQ_NOT_FOUND', 404, `Aprobación de liquidación con ID ${id} no encontrada`);
  }
}

export class ProcesosejecaprobarlqValidationError extends AppError {
  constructor(message: string) {
    super('PROCESOSEJECAPROBARLQ_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class ProcesosejecaprobarlqDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('PROCESOSEJECAPROBARLQ_DUPLICATE', 409, `Ya existe una aprobación con ${field}: ${value}`);
  }
}

export class ProcesosejecaprobarlqBusinessRuleError extends AppError {
  constructor(message: string) {
    super('PROCESOSEJECAPROBARLQ_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
