/**
 * Domain Exceptions: Rubrospreliquidadossubrecurso
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class RubrospreliquidadossubrecursoNotFoundError extends AppError {
  constructor(id: string) {
    super('RUBROSPRELIQUIDADOS_NOT_FOUND', 404, `Rubro preliquidado con ID ${id} no encontrado`);
  }
}

export class RubrospreliquidadossubrecursoValidationError extends AppError {
  constructor(message: string) {
    super('RUBROSPRELIQUIDADOS_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class RubrospreliquidadossubrecursoDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('RUBROSPRELIQUIDADOS_DUPLICATE', 409, `Ya existe un rubro con ${field}: ${value}`);
  }
}

export class RubrospreliquidadossubrecursoBusinessRuleError extends AppError {
  constructor(message: string) {
    super('RUBROSPRELIQUIDADOS_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
