/**
 * Domain Exceptions: Sobregiroshistricossubrecurso
 * Generated by migration-flow - GeneratedAt: 2024-04-01
 */

export abstract class AppError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = this.constructor.name;
  }
}

export class SobregiroshistricossubrecursoNotFoundError extends AppError {
  constructor(id: string) {
    super('SOBREGIROS_NOT_FOUND', 404, `Sobregiro con ID ${id} no encontrado`);
  }
}

export class SobregiroshistricossubrecursoValidationError extends AppError {
  constructor(message: string) {
    super('SOBREGIROS_VALIDATION_ERROR', 422, `Validación fallida: ${message}`);
  }
}

export class SobregiroshistricossubrecursoDuplicateError extends AppError {
  constructor(field: string, value: string) {
    super('SOBREGIROS_DUPLICATE', 409, `Ya existe un sobregiro con ${field}: ${value}`);
  }
}

export class SobregiroshistricossubrecursoBusinessRuleError extends AppError {
  constructor(message: string) {
    super('SOBREGIROS_BUSINESS_RULE_ERROR', 422, `Violación de regla de negocio: ${message}`);
  }
}
