import { useState, useEffect, useCallback } from 'react';
import { CargarubrosidoApplicationService } from '../../../../application/service/CargarubrosidoApplicationService';
import { CargarubrosidoGatewayAdapter } from '@modules/rubros/infrastructure/output/adapter/api/CargarubrosidoGatewayAdapter';
import { Cargarubrosido, CargarubrosidoLinea, CreateCargarubrosido, UpdateCargarubrosido, CargarubrosidoFilter } from '../../../../domain/model/Cargarubrosido';

// ─── Inyección manual: Gateway Adapter → Application Service ───
const gatewayAdapter = new CargarubrosidoGatewayAdapter();
const cargarubrosidoService = new CargarubrosidoApplicationService(gatewayAdapter);

/**
 * Custom Hook: useCargarubrosido
 * Conecta la UI con el Application Service de cargaRubrosIDO.zul.
 * Maneja estado de carga, errores y datos.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export function useCargarubrosido() {
  const [items, setItems] = useState<Cargarubrosido[]>([]);
  const [selectedItem, setSelectedItem] = useState<Cargarubrosido | null>(null);
  const [lineas, setLineas] = useState<CargarubrosidoLinea[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [totalElements, setTotalElements] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [page, setPage] = useState(0);

  const fetchAll = useCallback(async (params?: CargarubrosidoFilter) => {
    try {
      setLoading(true);
      setError(null);
      const response = await cargarubrosidoService.findAll(params);
      setItems(response.items);
      setTotalElements(response.totalElements);
      setTotalPages(response.totalPages);
      setPage(response.currentPage || 0);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar datos');
    } finally {
      setLoading(false);
    }
  }, []);

  const fetchById = useCallback(async (id: string) => {
    try {
      setLoading(true);
      setError(null);
      const item = await cargarubrosidoService.findById(id);
      setSelectedItem(item);
      return item;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar detalle');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  const create = useCallback(async (request: CreateCargarubrosido) => {
    try {
      setLoading(true);
      setError(null);
      const result = await cargarubrosidoService.create(request);
      // Actualizar lista después de la creación
      await fetchAll();
      return result;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al crear');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [fetchAll]);

  const update = useCallback(async (id: string, request: UpdateCargarubrosido) => {
    try {
      setLoading(true);
      setError(null);
      const updated = await cargarubrosidoService.update(id, request);
      setItems(prev => prev.map(item => item.id === Number(id) ? updated : item));
      if (selectedItem?.id === Number(id)) {
        setSelectedItem(updated);
      }
      return updated;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al actualizar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  const remove = useCallback(async (id: string) => {
    try {
      setLoading(true);
      setError(null);
      await cargarubrosidoService.remove(id);
      setItems(prev => prev.filter(item => item.id !== Number(id)));
      if (selectedItem?.id === Number(id)) {
        setSelectedItem(null);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al eliminar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  const fetchLineas = useCallback(async (id: string, pageNum?: number, size?: number) => {
    try {
      setLoading(true);
      setError(null);
      const response = await cargarubrosidoService.getLineas(id, pageNum, size);
      setLineas(response.items);
      return response;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar líneas');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  const aprobar = useCallback(async (id: string) => {
    try {
      setLoading(true);
      setError(null);
      const result = await cargarubrosidoService.aprobar(id);
      // Actualizar el estado después de aprobar
      await fetchById(id);
      return result;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al aprobar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [fetchById]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  return {
    items,
    selectedItem,
    lineas,
    loading,
    error,
    totalElements,
    totalPages,
    page,
    fetchAll,
    fetchById,
    fetchLineas,
    create,
    update,
    remove,
    aprobar,
    clearError: () => setError(null),
  };
}

