import { useState, useEffect, useCallback } from 'react';
import { CargarubrosidoService } from '../../../../application/service/CargarubrosidoService';
import { CargarubrosidoGatewayAdapter } from '@modules/rubros/infrastructure/output/adapter/api/CargarubrosidoGatewayAdapter';
import { CargarubrosidoResponse, CargarubrosidoLineaResponse, CreateCargarubrosidoRequest, UpdateCargarubrosidoRequest, CargarubrosidoFilterParams } from '../dto/CargarubrosidoDto';

// ─── Inyección manual: Gateway Adapter → Service ───
const gatewayAdapter = new CargarubrosidoGatewayAdapter();
const cargarubrosidoService = new CargarubrosidoService(gatewayAdapter);

/**
 * Custom Hook: useCargarubrosido
 * Conecta la UI con el Application Service de cargaRubrosIDO.zul.
 * Maneja estado de carga, errores y datos.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export function useCargarubrosido() {
  const [items, setItems] = useState<CargarubrosidoResponse[]>([]);
  const [selectedItem, setSelectedItem] = useState<CargarubrosidoResponse | null>(null);
  const [lineas, setLineas] = useState<CargarubrosidoLineaResponse[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [totalElements, setTotalElements] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [page, setPage] = useState(0);

  const fetchAll = useCallback(async (params?: CargarubrosidoFilterParams) => {
    try {
      setLoading(true);
      setError(null);
      const response = await cargarubrosidoService.findAll(params);
      setItems(response.content);
      setTotalElements(response.totalElements);
      setTotalPages(response.totalPages);
      setPage(response.number || 0);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar datos');
    } finally {
      setLoading(false);
    }
  }, []);

  const fetchById = useCallback(async (id: string) => {
    try {
      setLoading(true);
      setError(null);
      const item = await cargarubrosidoService.findById(id);
      setSelectedItem(item);
      return item;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar detalle');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  const create = useCallback(async (request: CreateCargarubrosidoRequest) => {
    try {
      setLoading(true);
      setError(null);
      const result = await cargarubrosidoService.create(request);
      // Actualizar lista después de la creación
      await fetchAll();
      return result;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al crear');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [fetchAll]);

  const update = useCallback(async (id: string, request: UpdateCargarubrosidoRequest) => {
    try {
      setLoading(true);
      setError(null);
      const updated = await cargarubrosidoService.update(id, request);
      setItems(prev => prev.map(item => item.id === Number(id) ? updated : item));
      if (selectedItem?.id === Number(id)) {
        setSelectedItem(updated);
      }
      return updated;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al actualizar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  const remove = useCallback(async (id: string) => {
    try {
      setLoading(true);
      setError(null);
      await cargarubrosidoService.remove(id);
      setItems(prev => prev.filter(item => item.id !== Number(id)));
      if (selectedItem?.id === Number(id)) {
        setSelectedItem(null);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al eliminar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  const fetchLineas = useCallback(async (id: string, pageNum?: number, size?: number) => {
    try {
      setLoading(true);
      setError(null);
      const response = await cargarubrosidoService.getLineas(id, pageNum, size);
      setLineas(response.content);
      return response;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar líneas');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  const aprobar = useCallback(async (id: string) => {
    try {
      setLoading(true);
      setError(null);
      const result = await cargarubrosidoService.aprobar(id);
      // Actualizar el estado después de aprobar
      await fetchById(id);
      return result;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al aprobar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [fetchById]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  return {
    items,
    selectedItem,
    lineas,
    loading,
    error,
    totalElements,
    totalPages,
    page,
    fetchAll,
    fetchById,
    fetchLineas,
    create,
    update,
    remove,
    aprobar,
    clearError: () => setError(null),
  };
}

