import { useState, useEffect, useCallback } from 'react';
import { ConsultarubrosidolistService } from '@modules/rubros/application/service/ConsultarubrosidolistService';
import { ConsultarubrosidolistGatewayAdapter } from '@modules/rubros/infrastructure/output/adapter/api/ConsultarubrosidolistGatewayAdapter';
import { ConsultarubrosidolistResponse, CreateConsultarubrosidolistRequest, UpdateConsultarubrosidolistRequest, ConsultarubrosidolistFilterParams, ExportarConsultaIDORequest, CambiarEstadoIDORequest } from '../dto/ConsultarubrosidolistDto';

// ─── Inyección manual: Gateway Adapter → Service ───
const gatewayAdapter = new ConsultarubrosidolistGatewayAdapter();
const consultarubrosidolistService = new ConsultarubrosidolistService(gatewayAdapter);

/**
 * Custom Hook: useConsultarubrosidolist
 * Conecta la UI con el Application Service de consultaRubrosIdoList.zul.
 * Maneja estado de carga, errores y datos.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export function useConsultarubrosidolist() {
  const [items, setItems] = useState<ConsultarubrosidolistResponse[]>([]);
  const [selectedItem, setSelectedItem] = useState<ConsultarubrosidolistResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [totalElements, setTotalElements] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [page, setPage] = useState(0);

  const fetchAll = useCallback(async (params?: ConsultarubrosidolistFilterParams) => {
    try {
      setLoading(true);
      setError(null);
      const response = await consultarubrosidolistService.findAll(params);
      setItems(response.content);
      setTotalElements(response.totalElements);
      setTotalPages(response.totalPages);
      setPage(response.number || 0);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar datos');
    } finally {
      setLoading(false);
    }
  }, []);

  const fetchById = useCallback(async (id: string) => {
    try {
      setLoading(true);
      setError(null);
      const item = await consultarubrosidolistService.findById(id);
      setSelectedItem(item);
      return item;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar detalle');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  const create = useCallback(async (request: CreateConsultarubrosidolistRequest) => {
    try {
      setLoading(true);
      setError(null);
      const created = await consultarubrosidolistService.create(request);
      setItems(prev => [...prev, created]);
      return created;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al crear');
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  const update = useCallback(async (id: string | number, request: UpdateConsultarubrosidolistRequest) => {
    try {
      setLoading(true);
      setError(null);
      const updated = await consultarubrosidolistService.update(String(id), request);
      setItems(prev => prev.map(item => item.id === Number(id) ? updated : item));
      if (selectedItem?.id === Number(id)) {
        setSelectedItem(updated);
      }
      return updated;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al actualizar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  const remove = useCallback(async (id: string | number) => {
    try {
      setLoading(true);
      setError(null);
      await consultarubrosidolistService.remove(String(id));
      setItems(prev => prev.filter(item => item.id !== Number(id)));
      if (selectedItem?.id === Number(id)) {
        setSelectedItem(null);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al eliminar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  const exportar = useCallback(async (request: ExportarConsultaIDORequest) => {
    try {
      setLoading(true);
      setError(null);
      const result = await consultarubrosidolistService.exportar(request);
      return result;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al exportar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  const cambiarEstado = useCallback(async (id: string | number, request: CambiarEstadoIDORequest) => {
    try {
      setLoading(true);
      setError(null);
      const updated = await consultarubrosidolistService.cambiarEstado(String(id), request);
      setItems(prev => prev.map(item => item.id === Number(id) ? updated : item));
      if (selectedItem?.id === Number(id)) {
        setSelectedItem(updated);
      }
      return updated;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cambiar estado');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  return {
    items,
    selectedItem,
    loading,
    error,
    totalElements,
    totalPages,
    page,
    fetchAll,
    fetchById,
    create,
    update,
    remove,
    exportar,
    cambiarEstado,
    clearError: () => setError(null),
  };
}
