import { useState, useEffect, useCallback } from 'react';
import { RubrosRubrosdialogApplicationService } from '@modules/rubros/application/service/RubrosRubrosdialogApplicationService';
import { RubrosRubrosdialogGatewayAdapter } from '@modules/rubros/infrastructure/output/adapter/api/RubrosRubrosdialogGatewayAdapter';
import { RubrosRubrosdialog, CreateRubrosRubrosdialog, UpdateRubrosRubrosdialog, RubrosRubrosdialogFilter } from '@modules/rubros/domain/model/RubrosRubrosdialog';

// ─── Inyección manual: Gateway Adapter → Application Service ───
const gatewayAdapter = new RubrosRubrosdialogGatewayAdapter();
const rubrosRubrosdialogService = new RubrosRubrosdialogApplicationService(gatewayAdapter);

/**
 * Custom Hook: useRubrosRubrosdialog
 * Conecta la UI con el Application Service de rubros.zul / rubrosDialog.zul.
 * Maneja estado de carga, errores y datos.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export function useRubrosRubrosdialog() {
  const [items, setItems] = useState<RubrosRubrosdialog[]>([]);
  const [selectedItem, setSelectedItem] = useState<RubrosRubrosdialog | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [totalElements, setTotalElements] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [page, setPage] = useState(0);

  const fetchAll = useCallback(async (params?: RubrosRubrosdialogFilter) => {
    try {
      setLoading(true);
      setError(null);
      const response = await rubrosRubrosdialogService.findAll(params);
      setItems(response.items);
      setTotalElements(response.totalElements);
      setTotalPages(response.totalPages);
      setPage(response.currentPage || 0);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar datos');
    } finally {
      setLoading(false);
    }
  }, []);

  const fetchById = useCallback(async (id: string | number) => {
    try {
      setLoading(true);
      setError(null);
      const item = await rubrosRubrosdialogService.findById(String(id));
      setSelectedItem(item);
      return item;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al cargar detalle');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  const create = useCallback(async (request: CreateRubrosRubrosdialog) => {
    try {
      setLoading(true);
      setError(null);
      const created = await rubrosRubrosdialogService.create(request);
      setItems(prev => [...prev, created]);
      return created;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al crear');
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  const update = useCallback(async (id: string | number, request: UpdateRubrosRubrosdialog) => {
    try {
      setLoading(true);
      setError(null);
      const updated = await rubrosRubrosdialogService.update(String(id), request);
      setItems(prev => prev.map(item => item.idRubro === String(id) ? updated : item));
      if (selectedItem?.idRubro === String(id)) {
        setSelectedItem(updated);
      }
      return updated;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al actualizar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  const remove = useCallback(async (id: string | number) => {
    try {
      setLoading(true);
      setError(null);
      await rubrosRubrosdialogService.remove(String(id));
      setItems(prev => prev.filter(item => item.idRubro !== String(id)));
      if (selectedItem?.idRubro === String(id)) {
        setSelectedItem(null);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al eliminar');
      throw err;
    } finally {
      setLoading(false);
    }
  }, [selectedItem]);

  useEffect(() => {
    fetchAll();
  }, [fetchAll]);

  return {
    items,
    selectedItem,
    loading,
    error,
    totalElements,
    totalPages,
    page,
    fetchAll,
    fetchById,
    create,
    update,
    remove,
    clearError: () => setError(null),
  };
}
