// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import React from 'react';
import { NominaxcolablistResponse } from '../dto/NominaxcolablistDto';

interface NominaxcolablistDetailProps {
  item: NominaxcolablistResponse;
  onEdit?: (item: NominaxcolablistResponse) => void;
  onDelete?: (ejecucionId: number, colaboradorId: number) => void;
  onBack?: () => void;
}

export const NominaxcolablistDetail: React.FC<NominaxcolablistDetailProps> = ({
  item,
  onEdit,
  onDelete,
  onBack,
}) => {
  return (
    <div className="nominaxcolablist-detail" data-testid="nominaxcolablist-detail">
      <div className="detail-header">
        <h2>Detalle de Nómina por Colaborador</h2>
        {onBack && (
          <button onClick={onBack} className="back-btn" data-testid="back-btn">
            ← Volver
          </button>
        )}
      </div>

      <div className="detail-content">
        <div className="detail-section">
          <h3>Información General</h3>
          <div className="detail-row">
            <span className="label">Ejecución ID:</span>
            <span className="value">{item.ejecucionId}</span>
          </div>
          <div className="detail-row">
            <span className="label">Colaborador ID:</span>
            <span className="value">{item.colaboradorId}</span>
          </div>
          <div className="detail-row">
            <span className="label">Cédula:</span>
            <span className="value">{item.cedula || '-'}</span>
          </div>
          <div className="detail-row">
            <span className="label">Nombres y Apellidos:</span>
            <span className="value">{item.apellidosNombres || '-'}</span>
          </div>
          <div className="detail-row">
            <span className="label">Empresa ID:</span>
            <span className="value">{item.empresaId || '-'}</span>
          </div>
        </div>

        <div className="detail-section">
          <h3>Resumen Financiero</h3>
          <div className="detail-row">
            <span className="label">Total Ingresos:</span>
            <span className="value amount">
              {typeof item.totalIngresos === 'number' ? item.totalIngresos.toFixed(2) : '-'}
            </span>
          </div>
          <div className="detail-row">
            <span className="label">Total Egresos:</span>
            <span className="value amount">
              {typeof item.totalEgresos === 'number' ? item.totalEgresos.toFixed(2) : '-'}
            </span>
          </div>
          <div className="detail-row highlight">
            <span className="label">Total Neto:</span>
            <span className="value total-neto">
              {typeof item.totalNeto === 'number' ? item.totalNeto.toFixed(2) : '-'}
            </span>
          </div>
          {typeof item.totalRubros === 'number' && (
            <div className="detail-row">
              <span className="label">Total Rubros:</span>
              <span className="value">{item.totalRubros}</span>
            </div>
          )}
          {typeof item.totalNoDeducible === 'number' && (
            <div className="detail-row">
              <span className="label">Total No Deducible:</span>
              <span className="value amount">{item.totalNoDeducible.toFixed(2)}</span>
            </div>
          )}
        </div>
      </div>

      <div className="detail-actions">
        {onEdit && (
          <button onClick={() => onEdit(item)} className="action-btn edit-btn" data-testid="detail-edit-btn">
            Editar
          </button>
        )}
        {onDelete && (
          <button
            onClick={() => onDelete(item.ejecucionId, item.colaboradorId)}
            className="action-btn delete-btn"
            data-testid="detail-delete-btn"
          >
            Eliminar
          </button>
        )}
        {onBack && (
          <button onClick={onBack} className="action-btn cancel-btn" data-testid="detail-back-btn">
            Volver
          </button>
        )}
      </div>
    </div>
  );
};
