// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import React from 'react';
import { NominaxcolablistResponse } from '../dto/NominaxcolablistDto';

interface NominaxcolablistCardProps {
  item: NominaxcolablistResponse;
  onSelect?: (item: NominaxcolablistResponse) => void;
  onEdit?: (item: NominaxcolablistResponse) => void;
  onDelete?: (ejecucionId: number, colaboradorId: number) => void;
}

export const NominaxcolablistCard: React.FC<NominaxcolablistCardProps> = ({
  item,
  onSelect,
  onEdit,
  onDelete,
}) => {
  return (
    <div className="nominaxcolablist-card" data-testid="nominaxcolablist-card">
      <div className="card-header">
        <h3>{item.apellidosNombres || 'Sin nombre'}</h3>
        <span className="card-id">Ejecutor: {item.ejecucionId}</span>
      </div>

      <div className="card-body">
        <div className="card-row">
          <span className="label">Cédula:</span>
          <span className="value">{item.cedula || '-'}</span>
        </div>
        <div className="card-row">
          <span className="label">Colaborador ID:</span>
          <span className="value">{item.colaboradorId}</span>
        </div>
        <div className="card-row">
          <span className="label">Empresa:</span>
          <span className="value">{item.empresaId || '-'}</span>
        </div>
        <div className="card-row">
          <span className="label">Total Ingresos:</span>
          <span className="value amount">
            {typeof item.totalIngresos === 'number' ? item.totalIngresos.toFixed(2) : '-'}
          </span>
        </div>
        <div className="card-row">
          <span className="label">Total Egresos:</span>
          <span className="value amount">
            {typeof item.totalEgresos === 'number' ? item.totalEgresos.toFixed(2) : '-'}
          </span>
        </div>
        <div className="card-row highlight">
          <span className="label">Total Neto:</span>
          <span className="value total-neto">
            {typeof item.totalNeto === 'number' ? item.totalNeto.toFixed(2) : '-'}
          </span>
        </div>
        {typeof item.totalRubros === 'number' && (
          <div className="card-row">
            <span className="label">Total Rubros:</span>
            <span className="value">{item.totalRubros}</span>
          </div>
        )}
        {typeof item.totalNoDeducible === 'number' && (
          <div className="card-row">
            <span className="label">Total No Deducible:</span>
            <span className="value amount">{item.totalNoDeducible.toFixed(2)}</span>
          </div>
        )}
      </div>

      <div className="card-footer">
        <button onClick={() => onSelect?.(item)} className="action-btn view-btn" data-testid="card-view-btn">
          Ver Detalle
        </button>
        <button onClick={() => onEdit?.(item)} className="action-btn edit-btn" data-testid="card-edit-btn">
          Editar
        </button>
        <button
          onClick={() => onDelete?.(item.ejecucionId, item.colaboradorId)}
          className="action-btn delete-btn"
          data-testid="card-delete-btn"
        >
          Eliminar
        </button>
      </div>
    </div>
  );
};
