// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import React, { useState, useEffect } from 'react';
import { CreateNominaxcolablistRequest, NominaxcolablistResponse } from '../dto/NominaxcolablistDto';

interface NominaxcolablistFormProps {
  initialData?: NominaxcolablistResponse;
  onSubmit: (data: CreateNominaxcolablistRequest) => Promise<void>;
  onCancel: () => void;
  loading?: boolean;
}

export const NominaxcolablistForm: React.FC<NominaxcolablistFormProps> = ({
  initialData,
  onSubmit,
  onCancel,
  loading = false,
}) => {
  const [formData, setFormData] = useState<CreateNominaxcolablistRequest>({
    ejecucionId: initialData?.ejecucionId || 0,
    empresaId: initialData?.empresaId,
    formato: 'PDF',
  });

  const [errors, setErrors] = useState<{ [key: string]: string }>({});
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (initialData) {
      setFormData({
        ejecucionId: initialData.ejecucionId,
        empresaId: initialData.empresaId,
        formato: 'PDF',
      });
    }
  }, [initialData]);

  const validateForm = (): boolean => {
    const newErrors: { [key: string]: string } = {};

    if (!formData.ejecucionId) {
      newErrors.ejecucionId = 'La ejecución es requerida';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: name === 'ejecucionId' || name === 'empresaId' ? (value ? parseInt(value) : undefined) : value,
    }));
    // Clear error for this field
    if (errors[name]) {
      setErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[name];
        return newErrors;
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setSubmitting(true);
    try {
      await onSubmit(formData);
    } catch (error) {
      console.error('Error submitiendo formulario:', error);
    } finally {
      setSubmitting(false);
    }
  };

  const isSubmitDisabled = submitting || loading;

  return (
    <form className="nominaxcolablist-form" onSubmit={handleSubmit} data-testid="nominaxcolablist-form">
      <div className="form-group">
        <label htmlFor="ejecucionId">Ejecución *</label>
        <input
          type="number"
          id="ejecucionId"
          name="ejecucionId"
          value={formData.ejecucionId}
          onChange={handleChange}
          disabled={loading}
          required
          data-testid="ejecucionId-input"
        />
        {errors.ejecucionId && <span className="error-message">{errors.ejecucionId}</span>}
      </div>

      <div className="form-group">
        <label htmlFor="empresaId">Empresa</label>
        <input
          type="number"
          id="empresaId"
          name="empresaId"
          value={formData.empresaId || ''}
          onChange={handleChange}
          disabled={loading}
          data-testid="empresaId-input"
        />
        {errors.empresaId && <span className="error-message">{errors.empresaId}</span>}
      </div>

      <div className="form-group">
        <label htmlFor="formato">Formato</label>
        <select
          id="formato"
          name="formato"
          value={formData.formato || ''}
          onChange={handleChange}
          disabled={loading}
          data-testid="formato-select"
        >
          <option value="">-- Seleccionar --</option>
          <option value="PDF">PDF</option>
          <option value="EXCEL">Excel</option>
          <option value="CSV">CSV</option>
        </select>
        {errors.formato && <span className="error-message">{errors.formato}</span>}
      </div>

      <div className="form-actions">
        <button type="submit" disabled={isSubmitDisabled} data-testid="submit-btn">
          {submitting ? 'Guardando...' : 'Guardar'}
        </button>
        <button type="button" onClick={onCancel} disabled={isSubmitDisabled} data-testid="cancel-btn">
          Cancelar
        </button>
      </div>
    </form>
  );
};
