// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import React from 'react';
import { NominaxcolablistResponse } from '../dto/NominaxcolablistDto';

interface NominaxcolablistListProps {
  items: NominaxcolablistResponse[];
  onSelect?: (item: NominaxcolablistResponse) => void;
  onEdit?: (item: NominaxcolablistResponse) => void;
  onDelete?: (ejecucionId: number, colaboradorId: number) => void;
  loading?: boolean;
}

export const NominaxcolablistList: React.FC<NominaxcolablistListProps> = ({
  items,
  onSelect,
  onEdit,
  onDelete,
  loading,
}) => {
  if (loading) {
    return (
      <div className="nominaxcolablist-list-loading" data-testid="nominaxcolablist-list-loading">
        <p>Cargando nóminas...</p>
      </div>
    );
  }

  if (items.length === 0) {
    return (
      <div className="nominaxcolablist-list-empty" data-testid="nominaxcolablist-list-empty">
        <p>No se encontraron registros de nóminas</p>
      </div>
    );
  }

  return (
    <div className="nominaxcolablist-list" data-testid="nominaxcolablist-list">
      <table className="nominaxcolablist-table" data-testid="nominaxcolablist-table">
        <thead>
          <tr>
            <th>Ejecución</th>
            <th>Colaborador</th>
            <th>Cédula</th>
            <th>Nombres y Apellidos</th>
            <th>Total Ingresos</th>
            <th>Total Egresos</th>
            <th>Total Neto</th>
            <th>Empresa</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item) => (
            <tr key={`${item.ejecucionId}-${item.colaboradorId}`} data-testid="nominaxcolablist-row">
              <td>{item.ejecucionId}</td>
              <td>{item.colaboradorId}</td>
              <td>{item.cedula || '-'}</td>
              <td>{item.apellidosNombres || '-'}</td>
              <td>{typeof item.totalIngresos === 'number' ? item.totalIngresos.toFixed(2) : '-'}</td>
              <td>{typeof item.totalEgresos === 'number' ? item.totalEgresos.toFixed(2) : '-'}</td>
              <td className="total-neto">{typeof item.totalNeto === 'number' ? item.totalNeto.toFixed(2) : '-'}</td>
              <td>{item.empresaId || '-'}</td>
              <td className="actions">
                <button
                  onClick={() => onSelect?.(item)}
                  className="action-btn view-btn"
                  data-testid="view-btn"
                >
                  Ver
                </button>
                <button
                  onClick={() => onEdit?.(item)}
                  className="action-btn edit-btn"
                  data-testid="edit-btn"
                >
                  Editar
                </button>
                <button
                  onClick={() => onDelete?.(item.ejecucionId, item.colaboradorId)}
                  className="action-btn delete-btn"
                  data-testid="delete-btn"
                >
                  Eliminar
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};
