import { CargarubrosidoGatewayPort } from '../../../../application/port/output/CargarubrosidoGatewayPort';
import { CargarubrosidoResponse, CargarubrosidoListResponse, CargarubrosidoLineaListResponse, CreateCargarubrosidoRequest, UpdateCargarubrosidoRequest, CargarubrosidoFilterParams, DeleteResponseDTO, ProcesoResponseDTO, CargaMasivaIDOResultDTO } from '../../../input/adapter/dto/CargarubrosidoDto';
import { CargarubrosidoApiMapper } from '../mapper/CargarubrosidoApiMapper';
import { httpClient } from '@shared/infrastructure/output/adapter/api/httpClient';

const BASE_PATH = '/api/v1/rubros-ido/cargas-masivas';

/**
 * API Gateway Adapter: cargaRubrosIDO.zul
 * Implementa los endpoints de cargas masivas de rubros IDO.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class CargarubrosidoGatewayAdapter implements CargarubrosidoGatewayPort {

  async findById(id: string): Promise<CargarubrosidoResponse> {
    const { data } = await httpClient.get(`${BASE_PATH}/${id}`);
    return CargarubrosidoApiMapper.toResponse(data);
  }

  async findAll(params?: CargarubrosidoFilterParams): Promise<CargarubrosidoListResponse> {
    const { data } = await httpClient.get(BASE_PATH, { params });
    return CargarubrosidoApiMapper.toListResponse(data);
  }

  async create(request: CreateCargarubrosidoRequest): Promise<CargaMasivaIDOResultDTO> {
    const payload = CargarubrosidoApiMapper.toCreatePayload(request);
    const { data } = await httpClient.post(BASE_PATH, payload, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return data;
  }

  async update(id: string, request: UpdateCargarubrosidoRequest): Promise<CargarubrosidoResponse> {
    const payload = CargarubrosidoApiMapper.toUpdatePayload(request);
    const { data } = await httpClient.put(`${BASE_PATH}/${id}`, payload);
    return CargarubrosidoApiMapper.toResponse(data);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    const { data } = await httpClient.delete(`${BASE_PATH}/${id}`);
    return data;
  }

  // Operaciones específicas de cargas masivas
  async getLineas(id: string, page?: number, size?: number): Promise<CargarubrosidoLineaListResponse> {
    const { data } = await httpClient.get(`${BASE_PATH}/${id}/lineas`, {
      params: { page, size },
    });
    return CargarubrosidoApiMapper.toLineaListResponse(data);
  }

  async aprobar(id: string): Promise<ProcesoResponseDTO> {
    const { data } = await httpClient.post(`${BASE_PATH}/${id}/aprobar`);
    return data;
  }
}
