import { ConsultarubrosidolistGatewayPort } from '../../../../application/port/output/ConsultarubrosidolistGatewayPort';
import { ConsultarubrosidolistResponse, ConsultarubrosidolistListResponse, CreateConsultarubrosidolistRequest, UpdateConsultarubrosidolistRequest, ConsultarubrosidolistFilterParams, DeleteResponseDTO, ExportarConsultaIDORequest, CambiarEstadoIDORequest, ExportarResponseDTO } from '../../../input/adapter/dto/ConsultarubrosidolistDto';
import { ConsultarubrosidolistApiMapper } from '../mapper/ConsultarubrosidolistApiMapper';
import { httpClient } from '@shared/infrastructure/output/adapter/api/httpClient';

const BASE_PATH = '/api/v1/rubros-ido/consulta';

/**
 * API Gateway Adapter: consultaRubrosIdoList.zul
 * Implementa los endpoints de consulta de rubros IDO.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class ConsultarubrosidolistGatewayAdapter implements ConsultarubrosidolistGatewayPort {

  async findById(id: string): Promise<ConsultarubrosidolistResponse> {
    const { data } = await httpClient.get(`${BASE_PATH}/${id}`);
    return ConsultarubrosidolistApiMapper.toResponse(data);
  }

  async findAll(params?: ConsultarubrosidolistFilterParams): Promise<ConsultarubrosidolistListResponse> {
    const { data } = await httpClient.get(BASE_PATH, { params });
    return ConsultarubrosidolistApiMapper.toListResponse(data);
  }

  async create(request: CreateConsultarubrosidolistRequest): Promise<ConsultarubrosidolistResponse> {
    const payload = ConsultarubrosidolistApiMapper.toCreatePayload(request);
    const { data } = await httpClient.post(BASE_PATH, payload);
    return ConsultarubrosidolistApiMapper.toResponse(data);
  }

  async update(id: string, request: UpdateConsultarubrosidolistRequest): Promise<ConsultarubrosidolistResponse> {
    const payload = ConsultarubrosidolistApiMapper.toUpdatePayload(request);
    const { data } = await httpClient.put(`${BASE_PATH}/${id}/estado`, payload);
    return ConsultarubrosidolistApiMapper.toResponse(data);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    const { data } = await httpClient.delete(`${BASE_PATH}/${id}`);
    return data;
  }

  // Operaciones específicas de consulta
  async exportar(request: ExportarConsultaIDORequest): Promise<ExportarResponseDTO> {
    const payload = ConsultarubrosidolistApiMapper.toExportPayload(request);
    const { data } = await httpClient.post(`${BASE_PATH}/exportar`, payload, {
      responseType: 'blob',
    });
    return data;
  }

  async cambiarEstado(id: string, request: CambiarEstadoIDORequest): Promise<ConsultarubrosidolistResponse> {
    const payload = ConsultarubrosidolistApiMapper.toCambiarEstadoPayload(request);
    const { data } = await httpClient.put(`${BASE_PATH}/${id}/estado`, payload);
    return ConsultarubrosidolistApiMapper.toResponse(data);
  }
}
