import { RubrosidocargaxprocesoGatewayPort } from '../../../../application/port/output/RubrosidocargaxprocesoGatewayPort';
import { RubrosidocargaxprocesoResponse, RubrosidocargaxprocesoListResponse, CreateRubrosidocargaxprocesoRequest, UpdateRubrosidocargaxprocesoRequest, RubrosidocargaxprocesoFilterParams, DeleteResponseDTO, ProcesoResponseDTO } from '../../../input/adapter/dto/RubrosidocargaxprocesoDto';
import { RubrosidocargaxprocesoApiMapper } from '../mapper/RubrosidocargaxprocesoApiMapper';
import { httpClient } from '@shared/infrastructure/output/adapter/api/httpClient';

const BASE_PATH = '/api/v1/rubros-ido/cargar-proceso';

/**
 * API Gateway Adapter: rubrosIDOcargaxProceso.zul
 * Implementa los endpoints del cargar-proceso.
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosidocargaxprocesoGatewayAdapter implements RubrosidocargaxprocesoGatewayPort {

  async findById(id: string): Promise<RubrosidocargaxprocesoResponse> {
    const { data } = await httpClient.get(`${BASE_PATH}/${id}`);
    return RubrosidocargaxprocesoApiMapper.toResponse(data);
  }

  async findAll(params?: RubrosidocargaxprocesoFilterParams): Promise<RubrosidocargaxprocesoListResponse> {
    const { data } = await httpClient.get(BASE_PATH, { params });
    return RubrosidocargaxprocesoApiMapper.toListResponse(data);
  }

  async create(request: CreateRubrosidocargaxprocesoRequest): Promise<RubrosidocargaxprocesoResponse | ProcesoResponseDTO> {
    const payload = RubrosidocargaxprocesoApiMapper.toCreatePayload(request);
    const { data } = await httpClient.post(BASE_PATH, payload);
    return RubrosidocargaxprocesoApiMapper.toResponse(data);
  }

  async update(id: string, request: UpdateRubrosidocargaxprocesoRequest): Promise<RubrosidocargaxprocesoResponse> {
    const payload = RubrosidocargaxprocesoApiMapper.toUpdatePayload(request);
    const { data } = await httpClient.put(`${BASE_PATH}/${id}`, payload);
    return RubrosidocargaxprocesoApiMapper.toResponse(data);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    const { data } = await httpClient.delete(`${BASE_PATH}/${id}`);
    return data;
  }
}
