import { RubrosRubrosdialogGatewayPort } from '../../../../application/port/output/RubrosRubrosdialogGatewayPort';
import { RubrosRubrosdialogResponse, RubrosRubrosdialogListResponse, CreateRubrosRubrosdialogRequest, UpdateRubrosRubrosdialogRequest, RubrosRubrosdialogFilterParams, DeleteResponseDTO } from '../../../input/adapter/dto/RubrosRubrosdialogDto';
import { RubrosRubrosdialogApiMapper } from '../mapper/RubrosRubrosdialogApiMapper';
import { httpClient } from '@shared/infrastructure/output/adapter/api/httpClient';

const BASE_PATH = '/api/v1/rubros';

/**
 * API Gateway Adapter: rubros.zul / rubrosDialog.zul
 * Implementa el Gateway Port usando Axios (httpClient).
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosRubrosdialogGatewayAdapter implements RubrosRubrosdialogGatewayPort {

  async findById(id: string): Promise<RubrosRubrosdialogResponse> {
    const { data } = await httpClient.get(`${BASE_PATH}/${id}`);
    return RubrosRubrosdialogApiMapper.toResponse(data);
  }

  async findAll(params?: RubrosRubrosdialogFilterParams): Promise<RubrosRubrosdialogListResponse> {
    const { data } = await httpClient.get(BASE_PATH, { params });
    return RubrosRubrosdialogApiMapper.toListResponse(data);
  }

  async create(request: CreateRubrosRubrosdialogRequest): Promise<RubrosRubrosdialogResponse> {
    const payload = RubrosRubrosdialogApiMapper.toCreatePayload(request);
    const { data } = await httpClient.post(BASE_PATH, payload);
    return RubrosRubrosdialogApiMapper.toResponse(data);
  }

  async update(id: string, request: UpdateRubrosRubrosdialogRequest): Promise<RubrosRubrosdialogResponse> {
    const payload = RubrosRubrosdialogApiMapper.toUpdatePayload(request);
    const { data } = await httpClient.put(`${BASE_PATH}/${id}`, payload);
    return RubrosRubrosdialogApiMapper.toResponse(data);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    const { data } = await httpClient.delete(`${BASE_PATH}/${id}`);
    return data;
  }
}
