import { RubrosidomainRubrosidolistRubrosidodetailGatewayPort } from '../../../../application/port/output/RubrosidomainRubrosidolistRubrosidodetailGatewayPort';
import { RubrosidomainRubrosidolistRubrosidodetailResponse, RubrosidomainRubrosidolistRubrosidodetailListResponse, CreateRubrosidomainRubrosidolistRubrosidodetailRequest, UpdateRubrosidomainRubrosidolistRubrosidodetailRequest, RubrosidomainRubrosidolistRubrosidodetailFilterParams, DeleteResponseDTO } from '../../../input/adapter/dto/RubrosidomainRubrosidolistRubrosidodetailDto';
import { RubrosidomainRubrosidolistRubrosidodetailApiMapper } from '../mapper/RubrosidomainRubrosidolistRubrosidodetailApiMapper';
import { httpClient } from '@shared/infrastructure/output/adapter/api/httpClient';

const BASE_PATH = '/api/v1/rubros-ido';

/**
 * API Gateway Adapter: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Implementa el Gateway Port usando Axios (httpClient).
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosidomainRubrosidolistRubrosidodetailGatewayAdapter implements RubrosidomainRubrosidolistRubrosidodetailGatewayPort {

  async findById(id: string): Promise<RubrosidomainRubrosidolistRubrosidodetailResponse> {
    const { data } = await httpClient.get(`${BASE_PATH}/${id}`);
    return RubrosidomainRubrosidolistRubrosidodetailApiMapper.toResponse(data);
  }

  async findAll(params?: RubrosidomainRubrosidolistRubrosidodetailFilterParams): Promise<RubrosidomainRubrosidolistRubrosidodetailListResponse> {
    const { data } = await httpClient.get(BASE_PATH, { params });
    return RubrosidomainRubrosidolistRubrosidodetailApiMapper.toListResponse(data);
  }

  async create(request: CreateRubrosidomainRubrosidolistRubrosidodetailRequest): Promise<RubrosidomainRubrosidolistRubrosidodetailResponse> {
    const payload = RubrosidomainRubrosidolistRubrosidodetailApiMapper.toCreatePayload(request);
    const { data } = await httpClient.post(BASE_PATH, payload);
    return RubrosidomainRubrosidolistRubrosidodetailApiMapper.toResponse(data);
  }

  async update(id: string, request: UpdateRubrosidomainRubrosidolistRubrosidodetailRequest): Promise<RubrosidomainRubrosidolistRubrosidodetailResponse> {
    const payload = RubrosidomainRubrosidolistRubrosidodetailApiMapper.toUpdatePayload(request);
    const { data } = await httpClient.put(`${BASE_PATH}/${id}`, payload);
    return RubrosidomainRubrosidolistRubrosidodetailApiMapper.toResponse(data);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    const { data } = await httpClient.delete(`${BASE_PATH}/${id}`);
    return data;
  }
}
