import { RubrosidomainGatewayPort } from '../../../../application/port/output/RubrosidomainGatewayPort';
import { RubrosidomainResponse, RubrosidomainListResponse, CreateRubrosidomainRequest, UpdateRubrosidomainRequest, RubrosidomainFilterParams, DeleteResponseDTO } from '../../../input/adapter/dto/RubrosidomainDto';
import { RubrosidomainApiMapper } from '../mapper/RubrosidomainApiMapper';
import { httpClient } from '@shared/infrastructure/output/adapter/api/httpClient';

const BASE_PATH = '/api/v1/rubros-ido';

/**
 * API Gateway Adapter: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul
 * Implementa el Gateway Port usando Axios (httpClient).
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosidomainGatewayAdapter implements RubrosidomainGatewayPort {

  async findById(id: string): Promise<RubrosidomainResponse> {
    const { data } = await httpClient.get(`${BASE_PATH}/${id}`);
    return RubrosidomainApiMapper.toResponse(data);
  }

  async findAll(params?: RubrosidomainFilterParams): Promise<RubrosidomainListResponse> {
    const { data } = await httpClient.get(BASE_PATH, { params });
    return RubrosidomainApiMapper.toListResponse(data);
  }

  async create(request: CreateRubrosidomainRequest): Promise<RubrosidomainResponse> {
    const payload = RubrosidomainApiMapper.toCreatePayload(request);
    const { data } = await httpClient.post(BASE_PATH, payload);
    return RubrosidomainApiMapper.toResponse(data);
  }

  async update(id: string, request: UpdateRubrosidomainRequest): Promise<RubrosidomainResponse> {
    const payload = RubrosidomainApiMapper.toUpdatePayload(request);
    const { data } = await httpClient.put(`${BASE_PATH}/${id}`, payload);
    return RubrosidomainApiMapper.toResponse(data);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    const { data } = await httpClient.delete(`${BASE_PATH}/${id}`);
    return data;
  }
}
