import { RubrosxprocesodialogGatewayPort } from '../../../../application/port/output/RubrosxprocesodialogGatewayPort';
import { RubrosxprocesodialogResponse, RubrosxprocesodialogListResponse, CreateRubrosxprocesodialogRequest, UpdateRubrosxprocesodialogRequest, RubrosxprocesodialogFilterParams, DeleteResponseDTO } from '../../../input/adapter/dto/RubrosxprocesodialogDto';
import { RubrosxprocesodialogApiMapper } from '../mapper/RubrosxprocesodialogApiMapper';
import { httpClient } from '@shared/infrastructure/output/adapter/api/httpClient';

const BASE_PATH = '/api/v1/rubros-proceso';

/**
 * API Gateway Adapter: rubrosxprocesoDialog.zul
 * Implementa el Gateway Port usando Axios (httpClient).
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 */
export class RubrosxprocesodialogGatewayAdapter implements RubrosxprocesodialogGatewayPort {

  async findById(id: string): Promise<RubrosxprocesodialogResponse> {
    const { data } = await httpClient.get(`${BASE_PATH}/${id}`);
    return RubrosxprocesodialogApiMapper.toResponse(data);
  }

  async findAll(params?: RubrosxprocesodialogFilterParams): Promise<RubrosxprocesodialogListResponse> {
    const { data } = await httpClient.get(BASE_PATH, { params });
    return RubrosxprocesodialogApiMapper.toListResponse(data);
  }

  async create(request: CreateRubrosxprocesodialogRequest): Promise<RubrosxprocesodialogResponse> {
    const payload = RubrosxprocesodialogApiMapper.toCreatePayload(request);
    const { data } = await httpClient.post(BASE_PATH, payload);
    return RubrosxprocesodialogApiMapper.toResponse(data);
  }

  async update(id: string, request: UpdateRubrosxprocesodialogRequest): Promise<RubrosxprocesodialogResponse> {
    const payload = RubrosxprocesodialogApiMapper.toUpdatePayload(request);
    const { data } = await httpClient.put(`${BASE_PATH}/${id}`, payload);
    return RubrosxprocesodialogApiMapper.toResponse(data);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    const { data } = await httpClient.delete(`${BASE_PATH}/${id}`);
    return data;
  }
}
