// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateEjecucionbot, Ejecucionbot, EjecucionbotFilter, EjecucionbotPageResult, UpdateEjecucionbot } from '../../../domain/model/Ejecucionbot';

export interface EjecucionbotUseCase {
  findById(id: string): Promise<Ejecucionbot>;
  findAll(filter?: EjecucionbotFilter): Promise<EjecucionbotPageResult>;
  create(model: CreateEjecucionbot): Promise<Ejecucionbot>;
  update(id: string, model: UpdateEjecucionbot): Promise<Ejecucionbot>;
  remove(id: string): Promise<void>;
}
