// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateEjecucionproccierre, Ejecucionproccierre, EjecucionproccierreFilter, EjecucionproccierrePageResult, UpdateEjecucionproccierre } from '../../../domain/model/Ejecucionproccierre';

export interface EjecucionproccierreUseCase {
  findById(id: string): Promise<Ejecucionproccierre>;
  findAll(filter?: EjecucionproccierreFilter): Promise<EjecucionproccierrePageResult>;
  create(model: CreateEjecucionproccierre): Promise<Ejecucionproccierre>;
  update(id: string, model: UpdateEjecucionproccierre): Promise<Ejecucionproccierre>;
  remove(id: string): Promise<void>;
  cerrar(id: string, request: CreateEjecucionproccierre): Promise<{ success: boolean; message: string }>;
  reabrir(id: string, request: UpdateEjecucionproccierre): Promise<{ success: boolean; message: string }>;
}
