// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateInstanciasprocesosInstanciasprocesosdialog, InstanciasprocesosInstanciasprocesosdialog, InstanciasprocesosInstanciasprocesosdialogFilter, InstanciasprocesosInstanciasprocesosdialogPageResult, UpdateInstanciasprocesosInstanciasprocesosdialog } from '../../../domain/model/InstanciasprocesosInstanciasprocesosdialog';

export interface InstanciasprocesosInstanciasprocesosdialogUseCase {
  findById(id: string): Promise<InstanciasprocesosInstanciasprocesosdialog>;
  findAll(filter?: InstanciasprocesosInstanciasprocesosdialogFilter): Promise<InstanciasprocesosInstanciasprocesosdialogPageResult>;
  create(model: CreateInstanciasprocesosInstanciasprocesosdialog): Promise<InstanciasprocesosInstanciasprocesosdialog>;
  update(id: string, model: UpdateInstanciasprocesosInstanciasprocesosdialog): Promise<InstanciasprocesosInstanciasprocesosdialog>;
  remove(id: string): Promise<void>;
}
