// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateLogderegistrosdeprocesosubrecurso, Logderegistrosdeprocesosubrecurso, LogderegistrosdeprocesosubrecursoFilter, LogderegistrosdeprocesosubrecursoPageResult, UpdateLogderegistrosdeprocesosubrecurso } from '../../../domain/model/Logderegistrosdeprocesosubrecurso';

export interface LogderegistrosdeprocesosubrecursoUseCase {
  findById(id: string): Promise<Logderegistrosdeprocesosubrecurso>;
  findAll(filter: LogderegistrosdeprocesosubrecursoFilter): Promise<LogderegistrosdeprocesosubrecursoPageResult>;
  create(model: CreateLogderegistrosdeprocesosubrecurso): Promise<Logderegistrosdeprocesosubrecurso>;
  update(id: string, model: UpdateLogderegistrosdeprocesosubrecurso): Promise<Logderegistrosdeprocesosubrecurso>;
  remove(id: string): Promise<void>;
  clear(ejecucionId: string): Promise<void>;
}
