// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosProcesosdialog, ProcesosProcesosdialog, ProcesosProcesosdialogFilter, ProcesosProcesosdialogPageResult, UpdateProcesosProcesosdialog } from '../../../domain/model/ProcesosProcesosdialog';

export interface ProcesosProcesosdialogUseCase {
  findById(id: string): Promise<ProcesosProcesosdialog>;
  findAll(filter?: ProcesosProcesosdialogFilter): Promise<ProcesosProcesosdialogPageResult>;
  create(model: CreateProcesosProcesosdialog): Promise<ProcesosProcesosdialog>;
  update(id: string, model: UpdateProcesosProcesosdialog): Promise<ProcesosProcesosdialog>;
  remove(id: string): Promise<void>;
}
