// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejecucionreversionProcesosejecucionreversiondialog, ProcesosejecucionreversionProcesosejecucionreversiondialog, ProcesosejecucionreversionProcesosejecucionreversiondialogFilter, ProcesosejecucionreversionProcesosejecucionreversiondialogPageResult, UpdateProcesosejecucionreversionProcesosejecucionreversiondialog } from '../../../domain/model/ProcesosejecucionreversionProcesosejecucionreversiondialog';

export interface ProcesosejecucionreversionProcesosejecucionreversiondialogUseCase {
  findById(id: string): Promise<ProcesosejecucionreversionProcesosejecucionreversiondialog>;
  findAll(filter?: ProcesosejecucionreversionProcesosejecucionreversiondialogFilter): Promise<ProcesosejecucionreversionProcesosejecucionreversiondialogPageResult>;
  create(model: CreateProcesosejecucionreversionProcesosejecucionreversiondialog): Promise<ProcesosejecucionreversionProcesosejecucionreversiondialog>;
  update(id: string, model: UpdateProcesosejecucionreversionProcesosejecucionreversiondialog): Promise<ProcesosejecucionreversionProcesosejecucionreversiondialog>;
  remove(id: string): Promise<void>;
  revertir(id: string, request: { motivo?: string; empresaId?: number }): Promise<{ success: boolean; message: string }>;
  listSobregiros(id: string, colaboradorId?: number, rubroId?: string): Promise<{ items: Array<{ ejecucionId: number; colaboradorId: number; rubroId: string; valor?: number; descripcion?: string }>; total: number }>;
}
