// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejecucionProcesosejecdialog, ProcesosejecucionProcesosejecdialog, ProcesosejecucionProcesosejecdialogFilter, ProcesosejecucionProcesosejecdialogPageResult, UpdateProcesosejecucionProcesosejecdialog } from '../../../domain/model/ProcesosejecucionProcesosejecdialog';

export interface ProcesosejecucionProcesosejecdialogUseCase {
  findById(id: string): Promise<ProcesosejecucionProcesosejecdialog>;
  findAll(filter?: ProcesosejecucionProcesosejecdialogFilter): Promise<ProcesosejecucionProcesosejecdialogPageResult>;
  create(model: CreateProcesosejecucionProcesosejecdialog): Promise<ProcesosejecucionProcesosejecdialog>;
  update(id: string, model: UpdateProcesosejecucionProcesosejecdialog): Promise<ProcesosejecucionProcesosejecdialog>;
  remove(id: string): Promise<void>;
  ejecutar(id: string, request: { entornoEjecucionId?: number; empresaId?: number }): Promise<{ success: boolean; message: string }>;
}
