// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejecaprobarlq, Procesosejecaprobarlq, ProcesosejecaprobarlqFilter, ProcesosejecaprobarlqPageResult, UpdateProcesosejecaprobarlq } from '../../../domain/model/Procesosejecaprobarlq';

export interface ProcesosejecaprobarlqUseCase {
  findById(id: string): Promise<Procesosejecaprobarlq>;
  findAll(filter?: ProcesosejecaprobarlqFilter): Promise<ProcesosejecaprobarlqPageResult>;
  create(model: CreateProcesosejecaprobarlq): Promise<{ success: boolean; message: string }>;
  update(id: string, model: UpdateProcesosejecaprobarlq): Promise<Procesosejecaprobarlq>;
  remove(id: string): Promise<void>;
  rechazar(request: { ejecucionId: number; colaboradorIds: number[] }): Promise<{ success: boolean; message: string }>;
}
