// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejecabrirlq, Procesosejecabrirlq, ProcesosejecabrirlqFilter, ProcesosejecabrirlqPageResult, UpdateProcesosejecabrirlq } from '../../../domain/model/Procesosejecabrirlq';

export interface ProcesosejecabrirlqUseCase {
  findById(id: string): Promise<Procesosejecabrirlq>;
  findAll(filter?: ProcesosejecabrirlqFilter): Promise<ProcesosejecabrirlqPageResult>;
  create(model: CreateProcesosejecabrirlq): Promise<{ success: boolean; message: string }>;
  update(id: string, model: UpdateProcesosejecabrirlq): Promise<Procesosejecabrirlq>;
  remove(id: string): Promise<void>;
}
