// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejeccolaboradores, Procesosejeccolaboradores, ProcesosejeccolaboradoresFilter, ProcesosejeccolaboradoresPageResult, UpdateProcesosejeccolaboradores } from '../../../domain/model/Procesosejeccolaboradores';

export interface ProcesosejeccolaboradoresUseCase {
  findById(id: string): Promise<Procesosejeccolaboradores>;
  findAll(filter: ProcesosejeccolaboradoresFilter): Promise<ProcesosejeccolaboradoresPageResult>;
  create(model: CreateProcesosejeccolaboradores): Promise<Procesosejeccolaboradores>;
  update(id: string, model: UpdateProcesosejeccolaboradores): Promise<Procesosejeccolaboradores>;
  remove(id: string): Promise<void>;
  listRubros(ejecucionId: string, colaboradorId: string): Promise<{ items: Array<{ rubroId: string; valor?: number; descripcion?: string }>; total: number }>;
  ejecutarColaborador(ejecucionId: string, request: { colaboradorId: number; empresaId: number }): Promise<{ success: boolean; message: string }>;
}
