// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateRubrospreliquidadossubrecurso, Rubrospreliquidadossubrecurso, RubrospreliquidadossubrecursoFilter, RubrospreliquidadossubrecursoPageResult, UpdateRubrospreliquidadossubrecurso } from '../../../domain/model/Rubrospreliquidadossubrecurso';

export interface RubrospreliquidadossubrecursoUseCase {
  findById(id: string): Promise<Rubrospreliquidadossubrecurso>;
  findAll(filter?: RubrospreliquidadossubrecursoFilter): Promise<RubrospreliquidadossubrecursoPageResult>;
  create(model: CreateRubrospreliquidadossubrecurso): Promise<Rubrospreliquidadossubrecurso>;
  update(id: string, model: UpdateRubrospreliquidadossubrecurso): Promise<Rubrospreliquidadossubrecurso>;
  remove(id: string): Promise<void>;
}
