// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateSobregiroshistricossubrecurso, Sobregiroshistricossubrecurso, SobregiroshistricossubrecursoFilter, SobregiroshistricossubrecursoPageResult, UpdateSobregiroshistricossubrecurso } from '../../../domain/model/Sobregiroshistricossubrecurso';

export interface SobregiroshistricossubrecursoUseCase {
  findById(id: string): Promise<Sobregiroshistricossubrecurso>;
  findAll(filter?: SobregiroshistricossubrecursoFilter): Promise<SobregiroshistricossubrecursoPageResult>;
  create(model: CreateSobregiroshistricossubrecurso): Promise<Sobregiroshistricossubrecurso>;
  update(id: string, model: UpdateSobregiroshistricossubrecurso): Promise<Sobregiroshistricossubrecurso>;
  remove(id: string): Promise<void>;
}
