// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import {
  CreateEjecucionbot,
  Ejecucionbot,
  EjecucionbotFilter,
  EjecucionbotPageResult,
  UpdateEjecucionbot,
} from "../../../../domain/model/Ejecucionbot";
import {
  CreateEjecucionbotRequest,
  EjecucionbotFilterParams,
  EjecucionbotListResponse,
  EjecucionbotResponse,
  UpdateEjecucionbotRequest,
} from "../dto/EjecucionbotDto";

export class EjecucionbotViewMapper {
  static toDomain(response: EjecucionbotResponse): Ejecucionbot {
    return { ...response };
  }
  static toPageResult(
    listResponse: EjecucionbotListResponse,
  ): EjecucionbotPageResult {
    return {
      data: listResponse.data.map(this.toDomain),
      totalElements: listResponse.totalElements,
      totalPages: listResponse.totalPages,
      page: listResponse.page,
      size: listResponse.size,
    };
  }
  static toCreateRequest(model: CreateEjecucionbot): CreateEjecucionbotRequest {
    return {
      colaboradorId: model.colaboradorId,
      codigoActa: model.codigoActa,
      tipoPago: model.tipoPago,
    };
  }
  static toUpdateRequest(model: UpdateEjecucionbot): UpdateEjecucionbotRequest {
    return {
      codigoActa: model.codigoActa,
      tipoPago: model.tipoPago,
      estado: model.estado,
    };
  }
  static toFilterParams(filter: EjecucionbotFilter): EjecucionbotFilterParams {
    return { ...filter };
  }
}
