// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateEjecucionproccierre, Ejecucionproccierre, EjecucionproccierreFilter, EjecucionproccierrePageResult, UpdateEjecucionproccierre } from '../../../../domain/model/Ejecucionproccierre';
import { CreateEjecucionproccierreRequest, EjecucionproccierreFilterParams, EjecucionproccierreListResponse, EjecucionproccierreResponse, UpdateEjecucionproccierreRequest } from '../dto/EjecucionproccierreDto';

export class EjecucionproccierreViewMapper {
  static toDomain(response: EjecucionproccierreResponse): Ejecucionproccierre { return { ...response }; }
  static toPageResult(listResponse: EjecucionproccierreListResponse): EjecucionproccierrePageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateEjecucionproccierre): CreateEjecucionproccierreRequest { return { empresaId: model.empresaId ?? 0, contabilizar: true }; }
  static toUpdateRequest(model: UpdateEjecucionproccierre): UpdateEjecucionproccierreRequest { return { motivo: model.estado }; }
  static toFilterParams(filter: EjecucionproccierreFilter): EjecucionproccierreFilterParams { return { ...filter }; }
}
