// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateInstanciasprocesosInstanciasprocesosdialog, InstanciasprocesosInstanciasprocesosdialog, InstanciasprocesosInstanciasprocesosdialogFilter, InstanciasprocesosInstanciasprocesosdialogPageResult, UpdateInstanciasprocesosInstanciasprocesosdialog } from '../../../../domain/model/InstanciasprocesosInstanciasprocesosdialog';
import { CreateInstanciasprocesosInstanciasprocesosdialogRequest, InstanciasprocesosInstanciasprocesosdialogFilterParams, InstanciasprocesosInstanciasprocesosdialogListResponse, InstanciasprocesosInstanciasprocesosdialogResponse, UpdateInstanciasprocesosInstanciasprocesosdialogRequest } from '../dto/InstanciasprocesosInstanciasprocesosdialogDto';

export class InstanciasprocesosInstanciasprocesosdialogViewMapper {
  static toDomain(response: InstanciasprocesosInstanciasprocesosdialogResponse): InstanciasprocesosInstanciasprocesosdialog { return { ...response }; }
  static toPageResult(listResponse: InstanciasprocesosInstanciasprocesosdialogListResponse): InstanciasprocesosInstanciasprocesosdialogPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateInstanciasprocesosInstanciasprocesosdialog): CreateInstanciasprocesosInstanciasprocesosdialogRequest { return { procesoId: model.procesoId, instancia: model.instancia, anio: model.anio, mes: model.mes }; }
  static toUpdateRequest(model: UpdateInstanciasprocesosInstanciasprocesosdialog): UpdateInstanciasprocesosInstanciasprocesosdialogRequest { return { instancia: model.instancia, fechaInicio: model.fechaInicio, fechaFin: model.fechaFin, cerrado: model.cerrado, esFinal: model.esFinal, reversado: model.reversado }; }
  static toFilterParams(filter: InstanciasprocesosInstanciasprocesosdialogFilter): InstanciasprocesosInstanciasprocesosdialogFilterParams { return { ...filter }; }
}
