// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateLogderegistrosdeprocesosubrecurso, Logderegistrosdeprocesosubrecurso, LogderegistrosdeprocesosubrecursoFilter, LogderegistrosdeprocesosubrecursoPageResult, UpdateLogderegistrosdeprocesosubrecurso } from '../../../../domain/model/Logderegistrosdeprocesosubrecurso';
import { CreateLogderegistrosdeprocesosubrecursoRequest, LogderegistrosdeprocesosubrecursoFilterParams, LogderegistrosdeprocesosubrecursoListResponse, LogderegistrosdeprocesosubrecursoResponse, UpdateLogderegistrosdeprocesosubrecursoRequest } from '../dto/LogderegistrosdeprocesosubrecursoDto';

export class LogderegistrosdeprocesosubrecursoViewMapper {
  static toDomain(response: LogderegistrosdeprocesosubrecursoResponse): Logderegistrosdeprocesosubrecurso { return { ...response }; }
  static toPageResult(listResponse: LogderegistrosdeprocesosubrecursoListResponse): LogderegistrosdeprocesosubrecursoPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateLogderegistrosdeprocesosubrecurso): CreateLogderegistrosdeprocesosubrecursoRequest { return { ejecucionId: model.ejecucionId, empresaId: model.empresaId, colaboradorId: model.colaboradorId, tipoProceso: model.tipoProceso, ejecuto: model.ejecuto }; }
  static toUpdateRequest(model: UpdateLogderegistrosdeprocesosubrecurso): UpdateLogderegistrosdeprocesosubrecursoRequest { return { ejecuto: model.ejecuto, observacion: model.mensaje }; }
  static toFilterParams(filter: LogderegistrosdeprocesosubrecursoFilter): LogderegistrosdeprocesosubrecursoFilterParams { return { ...filter }; }
}
