// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosProcesosdialog, ProcesosProcesosdialog, ProcesosProcesosdialogFilter, ProcesosProcesosdialogPageResult, UpdateProcesosProcesosdialog } from '../../../../domain/model/ProcesosProcesosdialog';
import { CreateProcesosProcesosdialogRequest, ProcesosProcesosdialogFilterParams, ProcesosProcesosdialogListResponse, ProcesosProcesosdialogResponse, UpdateProcesosProcesosdialogRequest } from '../dto/ProcesosProcesosdialogDto';

export class ProcesosProcesosdialogViewMapper {
  static toDomain(response: ProcesosProcesosdialogResponse): ProcesosProcesosdialog { return { ...response }; }
  static toPageResult(listResponse: ProcesosProcesosdialogListResponse): ProcesosProcesosdialogPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateProcesosProcesosdialog): CreateProcesosProcesosdialogRequest { return { ...model }; }
  static toUpdateRequest(model: UpdateProcesosProcesosdialog): UpdateProcesosProcesosdialogRequest { return { ...model }; }
  static toFilterParams(filter: ProcesosProcesosdialogFilter): ProcesosProcesosdialogFilterParams { return { ...filter }; }
}
