// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejecaprobarlq, Procesosejecaprobarlq, ProcesosejecaprobarlqFilter, ProcesosejecaprobarlqPageResult, UpdateProcesosejecaprobarlq } from '../../../../domain/model/Procesosejecaprobarlq';
import { CreateProcesosejecaprobarlqRequest, ProcesosejecaprobarlqFilterParams, ProcesosejecaprobarlqListResponse, ProcesosejecaprobarlqResponse, UpdateProcesosejecaprobarlqRequest } from '../dto/ProcesosejecaprobarlqDto';

export class ProcesosejecaprobarlqViewMapper {
  static toDomain(response: ProcesosejecaprobarlqResponse): Procesosejecaprobarlq { return { ...response }; }
  static toPageResult(listResponse: ProcesosejecaprobarlqListResponse): ProcesosejecaprobarlqPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateProcesosejecaprobarlq): CreateProcesosejecaprobarlqRequest { return { ejecucionId: model.ejecucionId, colaboradorIds: [model.colaboradorId] }; }
  static toUpdateRequest(model: UpdateProcesosejecaprobarlq): UpdateProcesosejecaprobarlqRequest { return { estado: model.estado }; }
  static toFilterParams(filter: ProcesosejecaprobarlqFilter): ProcesosejecaprobarlqFilterParams { return { ...filter }; }
}
