// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejeccolaboradores, Procesosejeccolaboradores, ProcesosejeccolaboradoresFilter, ProcesosejeccolaboradoresPageResult, UpdateProcesosejeccolaboradores } from '../../../../domain/model/Procesosejeccolaboradores';
import { CreateProcesosejeccolaboradoresRequest, ProcesosejeccolaboradoresFilterParams, ProcesosejeccolaboradoresListResponse, ProcesosejeccolaboradoresResponse, UpdateProcesosejeccolaboradoresRequest } from '../dto/ProcesosejeccolaboradoresDto';

export class ProcesosejeccolaboradoresViewMapper {
  static toDomain(response: ProcesosejeccolaboradoresResponse): Procesosejeccolaboradores { return { ...response }; }
  static toPageResult(listResponse: ProcesosejeccolaboradoresListResponse): ProcesosejeccolaboradoresPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateProcesosejeccolaboradores): CreateProcesosejeccolaboradoresRequest { return { ejecucionId: model.ejecucionId, colaboradorId: model.colaboradorId, empresaId: model.empresaId ?? 0 }; }
  static toUpdateRequest(_model: UpdateProcesosejeccolaboradores): UpdateProcesosejeccolaboradoresRequest { return { observacion: undefined }; }
  static toFilterParams(filter: ProcesosejeccolaboradoresFilter): ProcesosejeccolaboradoresFilterParams { return { ...filter }; }
}
