// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejecucionProcesosejecdialog, ProcesosejecucionProcesosejecdialog, ProcesosejecucionProcesosejecdialogFilter, ProcesosejecucionProcesosejecdialogPageResult, UpdateProcesosejecucionProcesosejecdialog } from '../../../../domain/model/ProcesosejecucionProcesosejecdialog';
import { CreateProcesosejecucionProcesosejecdialogRequest, ProcesosejecucionProcesosejecdialogFilterParams, ProcesosejecucionProcesosejecdialogListResponse, ProcesosejecucionProcesosejecdialogResponse, UpdateProcesosejecucionProcesosejecdialogRequest } from '../dto/ProcesosejecucionProcesosejecdialogDto';

export class ProcesosejecucionProcesosejecdialogViewMapper {
  static toDomain(response: ProcesosejecucionProcesosejecdialogResponse): ProcesosejecucionProcesosejecdialog { return { ...response }; }
  static toPageResult(listResponse: ProcesosejecucionProcesosejecdialogListResponse): ProcesosejecucionProcesosejecdialogPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateProcesosejecucionProcesosejecdialog): CreateProcesosejecucionProcesosejecdialogRequest { return { ...model }; }
  static toUpdateRequest(model: UpdateProcesosejecucionProcesosejecdialog): UpdateProcesosejecucionProcesosejecdialogRequest { return { ...model }; }
  static toFilterParams(filter: ProcesosejecucionProcesosejecdialogFilter): ProcesosejecucionProcesosejecdialogFilterParams { return { ...filter }; }
}
