// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejecucionreversionProcesosejecucionreversiondialog, ProcesosejecucionreversionProcesosejecucionreversiondialog, ProcesosejecucionreversionProcesosejecucionreversiondialogFilter, ProcesosejecucionreversionProcesosejecucionreversiondialogPageResult, UpdateProcesosejecucionreversionProcesosejecucionreversiondialog } from '../../../../domain/model/ProcesosejecucionreversionProcesosejecucionreversiondialog';
import { CreateProcesosejecucionreversionProcesosejecucionreversiondialogRequest, ProcesosejecucionreversionProcesosejecucionreversiondialogFilterParams, ProcesosejecucionreversionProcesosejecucionreversiondialogListResponse, ProcesosejecucionreversionProcesosejecucionreversiondialogResponse, UpdateProcesosejecucionreversionProcesosejecucionreversiondialogRequest } from '../dto/ProcesosejecucionreversionProcesosejecucionreversiondialogDto';

export class ProcesosejecucionreversionProcesosejecucionreversiondialogViewMapper {
  static toDomain(response: ProcesosejecucionreversionProcesosejecucionreversiondialogResponse): ProcesosejecucionreversionProcesosejecucionreversiondialog { return { ...response }; }
  static toPageResult(listResponse: ProcesosejecucionreversionProcesosejecucionreversiondialogListResponse): ProcesosejecucionreversionProcesosejecucionreversiondialogPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateProcesosejecucionreversionProcesosejecucionreversiondialog): CreateProcesosejecucionreversionProcesosejecucionreversiondialogRequest { return { motivo: model.motivoReversion }; }
  static toUpdateRequest(model: UpdateProcesosejecucionreversionProcesosejecucionreversiondialog): UpdateProcesosejecucionreversionProcesosejecucionreversiondialogRequest { return { motivo: model.motivoReversion }; }
  static toFilterParams(filter: ProcesosejecucionreversionProcesosejecucionreversiondialogFilter): ProcesosejecucionreversionProcesosejecucionreversiondialogFilterParams { return { ...filter }; }
}
