// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateProcesosejecabrirlq, Procesosejecabrirlq, ProcesosejecabrirlqFilter, ProcesosejecabrirlqPageResult, UpdateProcesosejecabrirlq } from '../../../../domain/model/Procesosejecabrirlq';
import { CreateProcesosejecabrirlqRequest, ProcesosejecabrirlqFilterParams, ProcesosejecabrirlqListResponse, ProcesosejecabrirlqResponse, UpdateProcesosejecabrirlqRequest } from '../dto/ProcesosejecabrirlqDto';

export class ProcesosejecabrirlqViewMapper {
  static toDomain(response: ProcesosejecabrirlqResponse): Procesosejecabrirlq { return { ...response }; }
  static toPageResult(listResponse: ProcesosejecabrirlqListResponse): ProcesosejecabrirlqPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateProcesosejecabrirlq): CreateProcesosejecabrirlqRequest { return { ejecucionId: model.ejecucionId, colaboradorIds: [model.colaboradorId] }; }
  static toUpdateRequest(model: UpdateProcesosejecabrirlq): UpdateProcesosejecabrirlqRequest { return { cerrado: model.cerrado, estado: model.estado }; }
  static toFilterParams(filter: ProcesosejecabrirlqFilter): ProcesosejecabrirlqFilterParams { return { ...filter }; }
}
