// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateRubrospreliquidadossubrecurso, Rubrospreliquidadossubrecurso, RubrospreliquidadossubrecursoFilter, RubrospreliquidadossubrecursoPageResult, UpdateRubrospreliquidadossubrecurso } from '../../../../domain/model/Rubrospreliquidadossubrecurso';
import { CreateRubrospreliquidadossubrecursoRequest, RubrospreliquidadossubrecursoFilterParams, RubrospreliquidadossubrecursoListResponse, RubrospreliquidadossubrecursoResponse, UpdateRubrospreliquidadossubrecursoRequest } from '../dto/RubrospreliquidadossubrecursoDto';

export class RubrospreliquidadossubrecursoViewMapper {
  static toDomain(response: RubrospreliquidadossubrecursoResponse): Rubrospreliquidadossubrecurso { return { ...response }; }
  static toPageResult(listResponse: RubrospreliquidadossubrecursoListResponse): RubrospreliquidadossubrecursoPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateRubrospreliquidadossubrecurso): CreateRubrospreliquidadossubrecursoRequest { return { ejecucionId: model.ejecucionId, colaboradorId: model.colaboradorId, rubroId: model.rubroId, valorSalida01: model.valorSalida01, valorSalida02: model.valorSalida02 }; }
  static toUpdateRequest(model: UpdateRubrospreliquidadossubrecurso): UpdateRubrospreliquidadossubrecursoRequest { return { valorSalida01: model.valorSalida01, valorSalida02: model.valorSalida02 }; }
  static toFilterParams(filter: RubrospreliquidadossubrecursoFilter): RubrospreliquidadossubrecursoFilterParams { return { ...filter }; }
}
