// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

import { CreateSobregiroshistricossubrecurso, Sobregiroshistricossubrecurso, SobregiroshistricossubrecursoFilter, SobregiroshistricossubrecursoPageResult, UpdateSobregiroshistricossubrecurso } from '../../../../domain/model/Sobregiroshistricossubrecurso';
import { CreateSobregiroshistricossubrecursoRequest, SobregiroshistricossubrecursoFilterParams, SobregiroshistricossubrecursoListResponse, SobregiroshistricossubrecursoResponse, UpdateSobregiroshistricossubrecursoRequest } from '../dto/SobregiroshistricossubrecursoDto';

export class SobregiroshistricossubrecursoViewMapper {
  static toDomain(response: SobregiroshistricossubrecursoResponse): Sobregiroshistricossubrecurso { return { ...response }; }
  static toPageResult(listResponse: SobregiroshistricossubrecursoListResponse): SobregiroshistricossubrecursoPageResult { return { data: listResponse.data.map(this.toDomain), totalElements: listResponse.totalElements, totalPages: listResponse.totalPages, page: listResponse.page, size: listResponse.size }; }
  static toCreateRequest(model: CreateSobregiroshistricossubrecurso): CreateSobregiroshistricossubrecursoRequest { return { ejecucionId: model.ejecucionId, colaboradorId: model.colaboradorId, rubroId: model.rubroId }; }
  static toUpdateRequest(_model: UpdateSobregiroshistricossubrecurso): UpdateSobregiroshistricossubrecursoRequest { return {}; }
  static toFilterParams(filter: SobregiroshistricossubrecursoFilter): SobregiroshistricossubrecursoFilterParams { return { ...filter }; }
}
