// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface Ejecucionbot {
  id: string;
  colaboradorId: number;
  codigoActa?: string;
  tipoPago?: string;
  estado?: string;
  fechaEjecucion?: string;
}

export type CreateEjecucionbot = Omit<Ejecucionbot, 'id'>;
export type UpdateEjecucionbot = Partial<Omit<Ejecucionbot, 'id'>>;

export interface EjecucionbotFilter {
  page?: number;
  size?: number;
  colaboradorId?: number;
  tipoPago?: string;
  estado?: string;
}

export interface EjecucionbotPageResult {
  data: Ejecucionbot[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
