// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface Ejecucionproccierre {
  id: string;
  procesoId: number;
  empresaId?: number;
  anio?: number;
  mes?: number;
  cerrado?: boolean;
  estado?: string;
}

export type CreateEjecucionproccierre = Omit<Ejecucionproccierre, 'id'>;
export type UpdateEjecucionproccierre = Partial<Omit<Ejecucionproccierre, 'id'>>;

export interface EjecucionproccierreFilter {
  page?: number;
  size?: number;
  empresaId?: number;
  procesoId?: number;
  anio?: number;
  mes?: number;
  cerrado?: number;
}

export interface EjecucionproccierrePageResult {
  data: Ejecucionproccierre[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
