// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface InstanciasprocesosInstanciasprocesosdialog {
  id: string;
  procesoId: number;
  instancia?: string;
  anio?: number;
  mes?: number;
  fechaInicio?: string;
  fechaFin?: string;
  cerrado?: boolean;
  esFinal?: boolean;
  reversado?: boolean;
}

export type CreateInstanciasprocesosInstanciasprocesosdialog = Omit<InstanciasprocesosInstanciasprocesosdialog, 'id'>;
export type UpdateInstanciasprocesosInstanciasprocesosdialog = Partial<Omit<InstanciasprocesosInstanciasprocesosdialog, 'id'>>;

export interface InstanciasprocesosInstanciasprocesosdialogFilter {
  page?: number;
  size?: number;
  procesoId?: number;
  anio?: number;
  mes?: number;
  cerrado?: number;
  esFinal?: number;
  reversado?: number;
}

export interface InstanciasprocesosInstanciasprocesosdialogPageResult {
  data: InstanciasprocesosInstanciasprocesosdialog[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
