// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface Logderegistrosdeprocesosubrecurso {
  id: string;
  ejecucionId: number;
  empresaId?: number;
  colaboradorId?: number;
  tipoProceso?: string;
  mensaje?: string;
  ejecuto?: string;
  fechaRegistro?: string;
}

export type CreateLogderegistrosdeprocesosubrecurso = Omit<Logderegistrosdeprocesosubrecurso, 'id'>;
export type UpdateLogderegistrosdeprocesosubrecurso = Partial<Omit<Logderegistrosdeprocesosubrecurso, 'id'>>;

export interface LogderegistrosdeprocesosubrecursoFilter {
  ejecucionId: number;
  page?: number;
  size?: number;
  empresaId?: number;
  colaboradorId?: number;
  tipoProceso?: string;
  ejecuto?: string;
}

export interface LogderegistrosdeprocesosubrecursoPageResult {
  data: Logderegistrosdeprocesosubrecurso[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
