// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface Procesosejeccolaboradores {
  id: string;
  ejecucionId: number;
  colaboradorId: number;
  cedula?: string;
  nombres?: string;
  empresaId?: number;
  totalIngresos?: number;
  totalEgresos?: number;
  totalNeto?: number;
}

export type CreateProcesosejeccolaboradores = Omit<Procesosejeccolaboradores, 'id'>;
export type UpdateProcesosejeccolaboradores = Partial<Omit<Procesosejeccolaboradores, 'id'>>;

export interface ProcesosejeccolaboradoresFilter {
  page?: number;
  size?: number;
  colaboradorId?: number;
  cedula?: string;
  empresaId?: number;
}

export interface ProcesosejeccolaboradoresPageResult {
  data: Procesosejeccolaboradores[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
