// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface ProcesosProcesosdialog {
  id: string;
  empresaId: number;
  tipoProceso: string;
  frecuencia?: string;
  rolId?: number;
  spEjecucion?: string;
  spReversion?: string;
  spContabilizacion?: string;
  spSalvarHistoricos?: string;
  busquedaCpr?: string;
  procesoSecurityId?: number;
  nombre?: string;
  descripcion?: string;
  activo?: boolean;
}

export type CreateProcesosProcesosdialog = Omit<ProcesosProcesosdialog, 'id'>;
export type UpdateProcesosProcesosdialog = Partial<Omit<ProcesosProcesosdialog, 'id'>>;

export interface ProcesosProcesosdialogFilter {
  page?: number;
  size?: number;
  empresaId?: number;
  tipoProceso?: string;
  frecuencia?: string;
  rolId?: number;
}

export interface ProcesosProcesosdialogPageResult {
  data: ProcesosProcesosdialog[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
