// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface ProcesosejecucionProcesosejecdialog {
  id: string;
  procesoId: number;
  instancia?: string;
  anio?: number;
  mes?: number;
  fechaInicio?: string;
  fechaFin?: string;
  cerrado?: boolean;
  entornoEjecucionId?: number;
}

export type CreateProcesosejecucionProcesosejecdialog = Omit<ProcesosejecucionProcesosejecdialog, 'id'>;
export type UpdateProcesosejecucionProcesosejecdialog = Partial<Omit<ProcesosejecucionProcesosejecdialog, 'id'>>;

export interface ProcesosejecucionProcesosejecdialogFilter {
  page?: number;
  size?: number;
  procesoId?: number;
  anio?: number;
  mes?: number;
  cerrado?: number;
  entornoEjecucion?: number;
}

export interface ProcesosejecucionProcesosejecdialogPageResult {
  data: ProcesosejecucionProcesosejecdialog[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
