// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface Procesosejecabrirlq {
  id: string;
  ejecucionId: number;
  colaboradorId: number;
  estado?: string;
  cerrado?: string;
  nombres?: string;
}

export type CreateProcesosejecabrirlq = Omit<Procesosejecabrirlq, 'id'>;
export type UpdateProcesosejecabrirlq = Partial<Omit<Procesosejecabrirlq, 'id'>>;

export interface ProcesosejecabrirlqFilter {
  page?: number;
  size?: number;
  ejecucionId?: number;
  colaboradorId?: number;
  cerrado?: string;
  estado?: string;
}

export interface ProcesosejecabrirlqPageResult {
  data: Procesosejecabrirlq[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
