// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface ProcesosejecucionreversionProcesosejecucionreversiondialog {
  id: string;
  procesoId: number;
  anio?: number;
  mes?: number;
  reversado?: boolean;
  motivoReversion?: string;
}

export type CreateProcesosejecucionreversionProcesosejecucionreversiondialog = Omit<ProcesosejecucionreversionProcesosejecucionreversiondialog, 'id'>;
export type UpdateProcesosejecucionreversionProcesosejecucionreversiondialog = Partial<Omit<ProcesosejecucionreversionProcesosejecucionreversiondialog, 'id'>>;

export interface ProcesosejecucionreversionProcesosejecucionreversiondialogFilter {
  page?: number;
  size?: number;
  procesoId?: number;
  anio?: number;
  mes?: number;
  reversado?: number;
}

export interface ProcesosejecucionreversionProcesosejecucionreversiondialogPageResult {
  data: ProcesosejecucionreversionProcesosejecucionreversiondialog[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
