// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface Procesosejecaprobarlq {
  id: string;
  ejecucionId: number;
  colaboradorId: number;
  estado?: string;
  nombres?: string;
}

export type CreateProcesosejecaprobarlq = Omit<Procesosejecaprobarlq, 'id'>;
export type UpdateProcesosejecaprobarlq = Partial<Omit<Procesosejecaprobarlq, 'id'>>;

export interface ProcesosejecaprobarlqFilter {
  page?: number;
  size?: number;
  ejecucionId?: number;
  colaboradorId?: number;
  estado?: string;
}

export interface ProcesosejecaprobarlqPageResult {
  data: Procesosejecaprobarlq[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
