// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface Rubrospreliquidadossubrecurso {
  id: string;
  ejecucionId: number;
  colaboradorId: number;
  rubroId: string;
  valorSalida01?: number;
  valorSalida02?: number;
  descripcion?: string;
}

export type CreateRubrospreliquidadossubrecurso = Omit<Rubrospreliquidadossubrecurso, 'id'>;
export type UpdateRubrospreliquidadossubrecurso = Partial<Omit<Rubrospreliquidadossubrecurso, 'id'>>;

export interface RubrospreliquidadossubrecursoFilter {
  page?: number;
  size?: number;
  ejecucionId?: number;
  colaboradorId?: number;
  rubroId?: string;
}

export interface RubrospreliquidadossubrecursoPageResult {
  data: Rubrospreliquidadossubrecurso[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
