// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-04-01

export interface Sobregiroshistricossubrecurso {
  id: string;
  ejecucionId: number;
  colaboradorId: number;
  rubroId: string;
  valor?: number;
  descripcion?: string;
}

export type CreateSobregiroshistricossubrecurso = Omit<Sobregiroshistricossubrecurso, 'id'>;
export type UpdateSobregiroshistricossubrecurso = Partial<Omit<Sobregiroshistricossubrecurso, 'id'>>;

export interface SobregiroshistricossubrecursoFilter {
  ejecucionId?: number;
  colaboradorId?: number;
  rubroId?: string;
}

export interface SobregiroshistricossubrecursoPageResult {
  data: Sobregiroshistricossubrecurso[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}
