// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Cargarubrosido, CreateCargarubrosido, UpdateCargarubrosido, CargarubrosidoFilter, CargarubrosidoPageResult, CargarubrosidoLineaPageResult } from '../../domain/model/Cargarubrosido';
import { CargarubrosidoUseCase } from '../port/input/CargarubrosidoUseCase';
import { CargarubrosidoGatewayPort } from '../port/output/CargarubrosidoGatewayPort';
import { CargarubrosidoNotFoundError, CargarubrosidoValidationError, CargarubrosidoBusinessRuleError } from '../../domain/exception/CargarubrosidoError';
import { CargarubrosidoViewMapper } from '../../infrastructure/input/adapter/mapper/CargarubrosidoViewMapper';

export class CargarubrosidoApplicationService implements CargarubrosidoUseCase {

  constructor(private readonly gatewayPort: CargarubrosidoGatewayPort) {}

  async findById(id: string): Promise<Cargarubrosido> {
    if (!id) {
      throw new CargarubrosidoValidationError('El ID es requerido');
    }
    const response = await this.gatewayPort.findById(id);
    if (!response) {
      throw new CargarubrosidoNotFoundError(id);
    }
    return CargarubrosidoViewMapper.toDomain(response);
  }

  async findAll(filter?: CargarubrosidoFilter): Promise<CargarubrosidoPageResult> {
    const params = filter ? CargarubrosidoViewMapper.toFilterParams(filter) : undefined;
    const response = await this.gatewayPort.findAll(params);
    return CargarubrosidoViewMapper.toPageResult(response);
  }

  async create(model: CreateCargarubrosido): Promise<Cargarubrosido> {
    if (!model.archivo) {
      throw new CargarubrosidoValidationError('El archivo es obligatorio', 'archivo');
    }
    if (!model.empresaId) {
      throw new CargarubrosidoValidationError('La empresa es obligatoria', 'empresaId');
    }
    const request = CargarubrosidoViewMapper.toCreateRequest(model);
    const result = await this.gatewayPort.create(request);
    if (!result.success) {
      throw new CargarubrosidoBusinessRuleError('UPLOAD_FAILED', result.message);
    }
    return this.findById(String(result.id));
  }

  async update(id: string, model: UpdateCargarubrosido): Promise<Cargarubrosido> {
    if (!id) {
      throw new CargarubrosidoValidationError('El ID es requerido para actualizar');
    }
    const request = CargarubrosidoViewMapper.toUpdateRequest(model);
    const response = await this.gatewayPort.update(id, request);
    return CargarubrosidoViewMapper.toDomain(response);
  }

  async remove(id: string): Promise<void> {
    if (!id) {
      throw new CargarubrosidoValidationError('El ID es requerido para eliminar');
    }
    await this.gatewayPort.remove(id);
  }

  async getLineas(id: string, page?: number, size?: number): Promise<CargarubrosidoLineaPageResult> {
    if (!id) {
      throw new CargarubrosidoValidationError('El ID es requerido para obtener líneas');
    }
    const response = await this.gatewayPort.getLineas(id, page, size);
    return CargarubrosidoViewMapper.toLineaPageResult(response);
  }

  async aprobar(id: string): Promise<Cargarubrosido> {
    if (!id) {
      throw new CargarubrosidoValidationError('El ID es requerido para aprobar');
    }
    const result = await this.gatewayPort.aprobar(id);
    if (!result.success) {
      throw new CargarubrosidoBusinessRuleError('APROBAR_FAILED', result.message);
    }
    return this.findById(id);
  }
}
