import { CargarubrosidoGatewayPort } from '../port/output/CargarubrosidoGatewayPort';
import { CargarubrosidoResponse, CargarubrosidoListResponse, CargarubrosidoLineaListResponse, CreateCargarubrosidoRequest, UpdateCargarubrosidoRequest, CargarubrosidoFilterParams, DeleteResponseDTO, ProcesoResponseDTO, CargaMasivaIDOResultDTO } from '../../infrastructure/input/adapter/dto/CargarubrosidoDto';

/**
 * Application Service: cargaRubrosIDO.zul (cargaRubrosIDO)
 * Implementa la lógica de aplicación invocando el Gateway Port (puerto de salida).
 * Controladores fuente: 6
 * Servicios fuente: 0
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Origen controlador:
 *   GET /api/v1/rubros-ido/cargas-masivas — Listar cargas masivas IDO
 *   GET /api/v1/rubros-ido/cargas-masivas/{id} — Obtener carga masiva IDO por ID
 *   GET /api/v1/rubros-ido/cargas-masivas/{id}/lineas — Obtener líneas de carga masiva
 *   POST /api/v1/rubros-ido/cargas-masivas — Crear carga masiva IDO
 *   POST /api/v1/rubros-ido/cargas-masivas/{id}/aprobar — Aprobar carga masiva
 *   DELETE /api/v1/rubros-ido/cargas-masivas/{id} — Eliminar carga masiva IDO
 */
export class CargarubrosidoService {
  constructor(private readonly gateway: CargarubrosidoGatewayPort) {}

  async findById(id: string): Promise<CargarubrosidoResponse> {
    return this.gateway.findById(id);
  }

  async findAll(params?: CargarubrosidoFilterParams): Promise<CargarubrosidoListResponse> {
    return this.gateway.findAll(params);
  }

  async create(request: CreateCargarubrosidoRequest): Promise<CargaMasivaIDOResultDTO> {
    // TODO: Validaciones de negocio antes de crear
    return this.gateway.create(request);
  }

  async update(id: string, request: UpdateCargarubrosidoRequest): Promise<CargarubrosidoResponse> {
    // TODO: Validaciones de negocio antes de actualizar
    return this.gateway.update(id, request);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    return this.gateway.remove(id);
  }

  async getLineas(id: string, page?: number, size?: number): Promise<CargarubrosidoLineaListResponse> {
    return this.gateway.getLineas(id, page, size);
  }

  async aprobar(id: string): Promise<ProcesoResponseDTO> {
    // TODO: Validaciones de negocio antes de aprobar
    return this.gateway.aprobar(id);
  }

  // TODO: Agregar métodos de negocio adicionales que combinen llamadas al gateway
}
