import { ConsultarubrosidolistGatewayPort } from '../port/output/ConsultarubrosidolistGatewayPort';
import { ConsultarubrosidolistResponse, ConsultarubrosidolistListResponse, CreateConsultarubrosidolistRequest, UpdateConsultarubrosidolistRequest, ConsultarubrosidolistFilterParams, DeleteResponseDTO, ExportarConsultaIDORequest, CambiarEstadoIDORequest, ExportarResponseDTO } from '../../infrastructure/input/adapter/dto/ConsultarubrosidolistDto';

/**
 * Application Service: consultaRubrosIdoList.zul (consultaRubrosIdoList)
 * Implementa la lógica de aplicación invocando el Gateway Port (puerto de salida).
 * Controladores fuente: 5
 * Servicios fuente: 0
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Origen controlador:
 *   GET /api/v1/rubros-ido/consulta — Consultar rubros IDO
 *   GET /api/v1/rubros-ido/consulta/{id} — Obtener rubro IDO de consulta por ID
 *   POST /api/v1/rubros-ido/consulta/exportar — Exportar consulta a Excel
 *   PUT /api/v1/rubros-ido/consulta/{id}/estado — Cambiar estado de rubro IDO
 *   DELETE /api/v1/rubros-ido/consulta/{id} — Eliminar rubro IDO desde consulta
 */
export class ConsultarubrosidolistService {
  constructor(private readonly gateway: ConsultarubrosidolistGatewayPort) {}

  async findById(id: string): Promise<ConsultarubrosidolistResponse> {
    return this.gateway.findById(id);
  }

  async findAll(params?: ConsultarubrosidolistFilterParams): Promise<ConsultarubrosidolistListResponse> {
    return this.gateway.findAll(params);
  }

  async create(request: CreateConsultarubrosidolistRequest): Promise<ConsultarubrosidolistResponse> {
    // TODO: Validaciones de negocio antes de crear
    return this.gateway.create(request);
  }

  async update(id: string, request: UpdateConsultarubrosidolistRequest): Promise<ConsultarubrosidolistResponse> {
    // TODO: Validaciones de negocio antes de actualizar
    return this.gateway.update(id, request);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    return this.gateway.remove(id);
  }

  async exportar(request: ExportarConsultaIDORequest): Promise<ExportarResponseDTO> {
    // TODO: Validaciones de filtros antes de exportar
    return this.gateway.exportar(request);
  }

  async cambiarEstado(id: string, request: CambiarEstadoIDORequest): Promise<ConsultarubrosidolistResponse> {
    // TODO: Validaciones de estado permitidos
    return this.gateway.cambiarEstado(id, request);
  }

  // TODO: Agregar métodos de negocio adicionales que combinen llamadas al gateway
}
