// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Consultarubrosidolist, CreateConsultarubrosidolist, UpdateConsultarubrosidolist, ConsultarubrosidolistFilter, ConsultarubrosidolistPageResult } from '../../domain/model/Consultarubrosidolist';
import { ConsultarubrosidolistUseCase } from '../port/input/ConsultarubrosidolistUseCase';
import { ConsultarubrosidolistGatewayPort } from '../port/output/ConsultarubrosidolistGatewayPort';
import { ConsultarubrosidolistNotFoundError, ConsultarubrosidolistValidationError } from '../../domain/exception/ConsultarubrosidolistError';
import { ConsultarubrosidolistViewMapper } from '../../infrastructure/input/adapter/mapper/ConsultarubrosidolistViewMapper';

export class ConsultarubrosidolistApplicationService implements ConsultarubrosidolistUseCase {

  constructor(private readonly gatewayPort: ConsultarubrosidolistGatewayPort) {}

  async findById(id: string): Promise<Consultarubrosidolist> {
    if (!id) {
      throw new ConsultarubrosidolistValidationError('El ID es requerido');
    }
    const response = await this.gatewayPort.findById(id);
    if (!response) {
      throw new ConsultarubrosidolistNotFoundError(id);
    }
    return ConsultarubrosidolistViewMapper.toDomain(response);
  }

  async findAll(filter?: ConsultarubrosidolistFilter): Promise<ConsultarubrosidolistPageResult> {
    const params = filter ? ConsultarubrosidolistViewMapper.toFilterParams(filter) : undefined;
    const response = await this.gatewayPort.findAll(params);
    return ConsultarubrosidolistViewMapper.toPageResult(response);
  }

  async create(model: CreateConsultarubrosidolist): Promise<Consultarubrosidolist> {
    const request = ConsultarubrosidolistViewMapper.toCreateRequest(model);
    const response = await this.gatewayPort.create(request);
    return ConsultarubrosidolistViewMapper.toDomain(response);
  }

  async update(id: string, model: UpdateConsultarubrosidolist): Promise<Consultarubrosidolist> {
    if (!id) {
      throw new ConsultarubrosidolistValidationError('El ID es requerido para actualizar');
    }
    const request = ConsultarubrosidolistViewMapper.toUpdateRequest(model);
    const response = await this.gatewayPort.update(id, request);
    return ConsultarubrosidolistViewMapper.toDomain(response);
  }

  async remove(id: string): Promise<void> {
    if (!id) {
      throw new ConsultarubrosidolistValidationError('El ID es requerido para eliminar');
    }
    await this.gatewayPort.remove(id);
  }

  async exportar(filter: ConsultarubrosidolistFilter): Promise<Blob> {
    const request = ConsultarubrosidolistViewMapper.toExportarRequest(filter);
    const response = await this.gatewayPort.exportar(request);
    return response as unknown as Blob;
  }

  async cambiarEstado(id: string, estado: string): Promise<Consultarubrosidolist> {
    if (!id) {
      throw new ConsultarubrosidolistValidationError('El ID es requerido');
    }
    if (!estado || estado.trim() === '') {
      throw new ConsultarubrosidolistValidationError('El estado es requerido', 'estado');
    }
    const response = await this.gatewayPort.cambiarEstado(id, { estado });
    return ConsultarubrosidolistViewMapper.toDomain(response);
  }
}
