import { RubrosidocargaxprocesoGatewayPort } from '../port/output/RubrosidocargaxprocesoGatewayPort';
import { RubrosidocargaxprocesoResponse, RubrosidocargaxprocesoListResponse, CreateRubrosidocargaxprocesoRequest, UpdateRubrosidocargaxprocesoRequest, RubrosidocargaxprocesoFilterParams, DeleteResponseDTO, ProcesoResponseDTO } from '../../infrastructure/input/adapter/dto/RubrosidocargaxprocesoDto';

/**
 * Application Service: rubrosIDOcargaxProceso.zul (rubrosIDOcargaxProceso)
 * Implementa la lógica de aplicación invocando el Gateway Port (puerto de salida).
 * Controladores fuente: 5
 * Servicios fuente: 0
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Origen controlador:
 *   GET /api/v1/rubros-ido/cargar-proceso — Listar cargas por proceso
 *   GET /api/v1/rubros-ido/cargar-proceso/{id} — Obtener carga por proceso por ID
 *   POST /api/v1/rubros-ido/cargar-proceso — Ejecutar carga por proceso
 *   PUT /api/v1/rubros-ido/cargar-proceso/{id} — Actualizar carga por proceso
 *   DELETE /api/v1/rubros-ido/cargar-proceso/{id} — Eliminar carga por proceso
 */
export class RubrosidocargaxprocesoService {
  constructor(private readonly gateway: RubrosidocargaxprocesoGatewayPort) {}

  async findById(id: string): Promise<RubrosidocargaxprocesoResponse> {
    return this.gateway.findById(id);
  }

  async findAll(params?: RubrosidocargaxprocesoFilterParams): Promise<RubrosidocargaxprocesoListResponse> {
    return this.gateway.findAll(params);
  }

  async create(request: CreateRubrosidocargaxprocesoRequest): Promise<RubrosidocargaxprocesoResponse | ProcesoResponseDTO> {
    // TODO: Validaciones de negocio antes de crear
    return this.gateway.create(request);
  }

  async update(id: string, request: UpdateRubrosidocargaxprocesoRequest): Promise<RubrosidocargaxprocesoResponse> {
    // TODO: Validaciones de negocio antes de actualizar
    return this.gateway.update(id, request);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    return this.gateway.remove(id);
  }

  // TODO: Agregar métodos de negocio adicionales que combinen llamadas al gateway
}
