// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { RubrosRubrosdialog, CreateRubrosRubrosdialog, UpdateRubrosRubrosdialog, RubrosRubrosdialogFilter, RubrosRubrosdialogPageResult } from '../../domain/model/RubrosRubrosdialog';
import { RubrosRubrosdialogUseCase } from '../port/input/RubrosRubrosdialogUseCase';
import { RubrosRubrosdialogGatewayPort } from '../port/output/RubrosRubrosdialogGatewayPort';
import { RubrosRubrosdialogNotFoundError, RubrosRubrosdialogValidationError } from '../../domain/exception/RubrosRubrosdialogError';
import { RubrosRubrosdialogViewMapper } from '../../infrastructure/input/adapter/mapper/RubrosRubrosdialogViewMapper';

export class RubrosRubrosdialogApplicationService implements RubrosRubrosdialogUseCase {

  constructor(private readonly gatewayPort: RubrosRubrosdialogGatewayPort) {}

  async findById(id: string): Promise<RubrosRubrosdialog> {
    if (!id || id.trim() === '') {
      throw new RubrosRubrosdialogValidationError('El ID del rubro es requerido', 'idRubro');
    }
    const response = await this.gatewayPort.findById(id);
    if (!response) {
      throw new RubrosRubrosdialogNotFoundError(id);
    }
    return RubrosRubrosdialogViewMapper.toDomain(response);
  }

  async findAll(filter?: RubrosRubrosdialogFilter): Promise<RubrosRubrosdialogPageResult> {
    const params = filter ? RubrosRubrosdialogViewMapper.toFilterParams(filter) : undefined;
    console.log("params for findAll:", params); // Debug log
    const response = await this.gatewayPort.findAll(params);
    return RubrosRubrosdialogViewMapper.toPageResult(response);
  }

  async create(model: CreateRubrosRubrosdialog): Promise<RubrosRubrosdialog> {
    if (!model.idRubro || model.idRubro.trim() === '') {
      throw new RubrosRubrosdialogValidationError('El código del rubro es obligatorio', 'idRubro');
    }
    if (!model.nombre || model.nombre.trim() === '') {
      throw new RubrosRubrosdialogValidationError('El nombre del rubro es obligatorio', 'nombre');
    }
    const request = RubrosRubrosdialogViewMapper.toCreateRequest(model);
    const response = await this.gatewayPort.create(request);
    return RubrosRubrosdialogViewMapper.toDomain(response);
  }

  async update(id: string, model: UpdateRubrosRubrosdialog): Promise<RubrosRubrosdialog> {
    if (!id || id.trim() === '') {
      throw new RubrosRubrosdialogValidationError('El ID del rubro es requerido para actualizar', 'idRubro');
    }
    if (model.nombre !== undefined && model.nombre.trim() === '') {
      throw new RubrosRubrosdialogValidationError('El nombre del rubro no puede estar vacío', 'nombre');
    }
    const request = RubrosRubrosdialogViewMapper.toUpdateRequest(model);
    const response = await this.gatewayPort.update(id, request);
    return RubrosRubrosdialogViewMapper.toDomain(response);
  }

  async remove(id: string): Promise<void> {
    if (!id || id.trim() === '') {
      throw new RubrosRubrosdialogValidationError('El ID del rubro es requerido para eliminar', 'idRubro');
    }
    await this.gatewayPort.remove(id);
  }
}
