// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosidocargaxproceso, CreateRubrosidocargaxproceso, UpdateRubrosidocargaxproceso, RubrosidocargaxprocesoFilter, RubrosidocargaxprocesoPageResult } from '../../domain/model/Rubrosidocargaxproceso';
import { RubrosidocargaxprocesoUseCase } from '../port/input/RubrosidocargaxprocesoUseCase';
import { RubrosidocargaxprocesoGatewayPort } from '../port/output/RubrosidocargaxprocesoGatewayPort';
import { RubrosidocargaxprocesoNotFoundError, RubrosidocargaxprocesoValidationError, RubrosidocargaxprocesoBusinessRuleError } from '../../domain/exception/RubrosidocargaxprocesoError';
import { RubrosidocargaxprocesoViewMapper } from '../../infrastructure/input/adapter/mapper/RubrosidocargaxprocesoViewMapper';
import { RubrosidocargaxprocesoResponse } from '../../infrastructure/input/adapter/dto/RubrosidocargaxprocesoDto';

export class RubrosidocargaxprocesoApplicationService implements RubrosidocargaxprocesoUseCase {

  constructor(private readonly gatewayPort: RubrosidocargaxprocesoGatewayPort) {}

  async findById(id: string): Promise<Rubrosidocargaxproceso> {
    if (!id) {
      throw new RubrosidocargaxprocesoValidationError('El ID es requerido');
    }
    const response = await this.gatewayPort.findById(id);
    if (!response) {
      throw new RubrosidocargaxprocesoNotFoundError(id);
    }
    return RubrosidocargaxprocesoViewMapper.toDomain(response);
  }

  async findAll(filter?: RubrosidocargaxprocesoFilter): Promise<RubrosidocargaxprocesoPageResult> {
    const params = filter ? RubrosidocargaxprocesoViewMapper.toFilterParams(filter) : undefined;
    const response = await this.gatewayPort.findAll(params);
    return RubrosidocargaxprocesoViewMapper.toPageResult(response);
  }

  async create(model: CreateRubrosidocargaxproceso): Promise<Rubrosidocargaxproceso> {
    if (!model.empresaId) {
      throw new RubrosidocargaxprocesoValidationError('La empresa es obligatoria', 'empresaId');
    }
    if (!model.rubroId || model.rubroId.trim() === '') {
      throw new RubrosidocargaxprocesoValidationError('El código de rubro es obligatorio', 'rubroId');
    }
    const request = RubrosidocargaxprocesoViewMapper.toCreateRequest(model);
    const response = await this.gatewayPort.create(request);
    if (!('id' in response)) {
      throw new RubrosidocargaxprocesoBusinessRuleError('CREATE_RESPONSE', response.message);
    }
    return RubrosidocargaxprocesoViewMapper.toDomain(response as RubrosidocargaxprocesoResponse);
  }

  async update(id: string, model: UpdateRubrosidocargaxproceso): Promise<Rubrosidocargaxproceso> {
    if (!id) {
      throw new RubrosidocargaxprocesoValidationError('El ID es requerido para actualizar');
    }
    const request = RubrosidocargaxprocesoViewMapper.toUpdateRequest(model);
    const response = await this.gatewayPort.update(id, request);
    return RubrosidocargaxprocesoViewMapper.toDomain(response);
  }

  async remove(id: string): Promise<void> {
    if (!id) {
      throw new RubrosidocargaxprocesoValidationError('El ID es requerido para eliminar');
    }
    await this.gatewayPort.remove(id);
  }

  async ejecutarCarga(model: CreateRubrosidocargaxproceso): Promise<{ success: boolean; message: string }> {
    if (!model.empresaId) {
      throw new RubrosidocargaxprocesoValidationError('La empresa es obligatoria para ejecutar la carga', 'empresaId');
    }
    if (!model.rubroId || model.rubroId.trim() === '') {
      throw new RubrosidocargaxprocesoValidationError('El código de rubro es obligatorio para ejecutar la carga', 'rubroId');
    }
    const request = RubrosidocargaxprocesoViewMapper.toCreateRequest(model);
    const response = await this.gatewayPort.create(request);
    if ('id' in response) {
      return { success: true, message: 'Carga ejecutada correctamente' };
    }
    return response;
  }
}
