import { RubrosidomainRubrosidolistRubrosidodetailGatewayPort } from '../port/output/RubrosidomainRubrosidolistRubrosidodetailGatewayPort';
import { RubrosidomainRubrosidolistRubrosidodetailResponse, RubrosidomainRubrosidolistRubrosidodetailListResponse, CreateRubrosidomainRubrosidolistRubrosidodetailRequest, UpdateRubrosidomainRubrosidolistRubrosidodetailRequest, RubrosidomainRubrosidolistRubrosidodetailFilterParams, DeleteResponseDTO } from '../../infrastructure/input/adapter/dto/RubrosidomainRubrosidolistRubrosidodetailDto';

/**
 * Application Service: rubrosIDOMain.zul / rubrosIDOList.zul / rubrosIDODetail.zul (rubrosIDOMain_rubrosIDOList_rubrosIDODetail)
 * Implementa la lógica de aplicación invocando el Gateway Port (puerto de salida).
 * Controladores fuente: 5
 * Servicios fuente: 0
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Origen controlador:
 *   GET /api/v1/rubros-ido — Listar rubros IDO
 *   GET /api/v1/rubros-ido/{id} — Obtener rubro IDO por ID
 *   POST /api/v1/rubros-ido — Crear rubro IDO
 *   PUT /api/v1/rubros-ido/{id} — Actualizar rubro IDO
 *   DELETE /api/v1/rubros-ido/{id} — Eliminar rubro IDO
 */
export class RubrosidomainRubrosidolistRubrosidodetailService {
  constructor(private readonly gateway: RubrosidomainRubrosidolistRubrosidodetailGatewayPort) {}

  async findById(id: string): Promise<RubrosidomainRubrosidolistRubrosidodetailResponse> {
    return this.gateway.findById(id);
  }

  async findAll(params?: RubrosidomainRubrosidolistRubrosidodetailFilterParams): Promise<RubrosidomainRubrosidolistRubrosidodetailListResponse> {
    return this.gateway.findAll(params);
  }

  async create(request: CreateRubrosidomainRubrosidolistRubrosidodetailRequest): Promise<RubrosidomainRubrosidolistRubrosidodetailResponse> {
    // TODO: Validaciones de negocio antes de crear
    return this.gateway.create(request);
  }

  async update(id: string, request: UpdateRubrosidomainRubrosidolistRubrosidodetailRequest): Promise<RubrosidomainRubrosidolistRubrosidodetailResponse> {
    // TODO: Validaciones de negocio antes de actualizar
    return this.gateway.update(id, request);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    return this.gateway.remove(id);
  }

  // TODO: Agregar métodos de negocio adicionales que combinen llamadas al gateway
}
