// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosxprocesodialog, CreateRubrosxprocesodialog, UpdateRubrosxprocesodialog, RubrosxprocesodialogFilter, RubrosxprocesodialogPageResult } from '../../domain/model/Rubrosxprocesodialog';
import { RubrosxprocesodialogUseCase } from '../port/input/RubrosxprocesodialogUseCase';
import { RubrosxprocesodialogGatewayPort } from '../port/output/RubrosxprocesodialogGatewayPort';
import { RubrosxprocesodialogNotFoundError, RubrosxprocesodialogValidationError } from '../../domain/exception/RubrosxprocesodialogError';
import { RubrosxprocesodialogViewMapper } from '../../infrastructure/input/adapter/mapper/RubrosxprocesodialogViewMapper';

export class RubrosxprocesodialogApplicationService implements RubrosxprocesodialogUseCase {

  constructor(private readonly gatewayPort: RubrosxprocesodialogGatewayPort) {}

  async findById(id: string): Promise<Rubrosxprocesodialog> {
    if (!id) {
      throw new RubrosxprocesodialogValidationError('El ID es requerido');
    }
    const response = await this.gatewayPort.findById(id);
    if (!response) {
      throw new RubrosxprocesodialogNotFoundError(id);
    }
    return RubrosxprocesodialogViewMapper.toDomain(response);
  }

  async findAll(filter?: RubrosxprocesodialogFilter): Promise<RubrosxprocesodialogPageResult> {
    const params = filter ? RubrosxprocesodialogViewMapper.toFilterParams(filter) : undefined;
    const response = await this.gatewayPort.findAll(params);
    return RubrosxprocesodialogViewMapper.toPageResult(response);
  }

  async create(model: CreateRubrosxprocesodialog): Promise<Rubrosxprocesodialog> {
    if (!model.rubroId || model.rubroId.trim() === '') {
      throw new RubrosxprocesodialogValidationError('El código de rubro es obligatorio', 'rubroId');
    }
    if (!model.procesoId) {
      throw new RubrosxprocesodialogValidationError('El proceso es obligatorio', 'procesoId');
    }
    const request = RubrosxprocesodialogViewMapper.toCreateRequest(model);
    const response = await this.gatewayPort.create(request);
    return RubrosxprocesodialogViewMapper.toDomain(response);
  }

  async update(id: string, model: UpdateRubrosxprocesodialog): Promise<Rubrosxprocesodialog> {
    if (!id) {
      throw new RubrosxprocesodialogValidationError('El ID es requerido para actualizar');
    }
    const request = RubrosxprocesodialogViewMapper.toUpdateRequest(model);
    const response = await this.gatewayPort.update(id, request);
    return RubrosxprocesodialogViewMapper.toDomain(response);
  }

  async remove(id: string): Promise<void> {
    if (!id) {
      throw new RubrosxprocesodialogValidationError('El ID es requerido para eliminar');
    }
    await this.gatewayPort.remove(id);
  }
}
