import { RubrosxprocesodialogGatewayPort } from '../port/output/RubrosxprocesodialogGatewayPort';
import { RubrosxprocesodialogResponse, RubrosxprocesodialogListResponse, CreateRubrosxprocesodialogRequest, UpdateRubrosxprocesodialogRequest, RubrosxprocesodialogFilterParams, DeleteResponseDTO } from '../../infrastructure/input/adapter/dto/RubrosxprocesodialogDto';

/**
 * Application Service: rubrosxprocesoDialog.zul (rubrosxprocesoDialog)
 * Implementa la lógica de aplicación invocando el Gateway Port (puerto de salida).
 * Controladores fuente: 5
 * Servicios fuente: 0
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Origen controlador:
 *   GET /api/v1/rubros-proceso — Listar asignaciones rubro-proceso
 *   GET /api/v1/rubros-proceso/{id} — Obtener asignación rubro-proceso por ID
 *   POST /api/v1/rubros-proceso — Crear asignación rubro-proceso
 *   PUT /api/v1/rubros-proceso/{id} — Actualizar asignación rubro-proceso
 *   DELETE /api/v1/rubros-proceso/{id} — Eliminar asignación rubro-proceso
 */
export class RubrosxprocesodialogService {
  constructor(private readonly gateway: RubrosxprocesodialogGatewayPort) {}

  async findById(id: string): Promise<RubrosxprocesodialogResponse> {
    return this.gateway.findById(id);
  }

  async findAll(params?: RubrosxprocesodialogFilterParams): Promise<RubrosxprocesodialogListResponse> {
    return this.gateway.findAll(params);
  }

  async create(request: CreateRubrosxprocesodialogRequest): Promise<RubrosxprocesodialogResponse> {
    // TODO: Validaciones de negocio antes de crear
    return this.gateway.create(request);
  }

  async update(id: string, request: UpdateRubrosxprocesodialogRequest): Promise<RubrosxprocesodialogResponse> {
    // TODO: Validaciones de negocio antes de actualizar
    return this.gateway.update(id, request);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    return this.gateway.remove(id);
  }

  // TODO: Agregar métodos de negocio adicionales que combinen llamadas al gateway
}
