import { RubrosRubrosdialogGatewayPort } from '../port/output/RubrosRubrosdialogGatewayPort';
import { RubrosRubrosdialogResponse, RubrosRubrosdialogListResponse, CreateRubrosRubrosdialogRequest, UpdateRubrosRubrosdialogRequest, RubrosRubrosdialogFilterParams, DeleteResponseDTO } from '../../infrastructure/input/adapter/dto/RubrosRubrosdialogDto';

/**
 * Application Service: rubros.zul / rubrosDialog.zul (rubros_rubrosDialog)
 * Implementa la lógica de aplicación invocando el Gateway Port (puerto de salida).
 * Controladores fuente: 5
 * Servicios fuente: 0
 * Generated by migration-flow | GeneratedAt: 2026-03-27
 *
 * Origen controlador:
 *   GET /api/v1/rubros — Listar rubros
 *   GET /api/v1/rubros/{idRubro} — Obtener rubro por ID
 *   POST /api/v1/rubros — Crear rubro
 *   PUT /api/v1/rubros/{idRubro} — Actualizar rubro
 *   DELETE /api/v1/rubros/{idRubro} — Eliminar rubro
 */
export class RubrosRubrosdialogService {
  constructor(private readonly gateway: RubrosRubrosdialogGatewayPort) {}

  async findById(id: string): Promise<RubrosRubrosdialogResponse> {
    return this.gateway.findById(id);
  }

  async findAll(params?: RubrosRubrosdialogFilterParams): Promise<RubrosRubrosdialogListResponse> {
    return this.gateway.findAll(params);
  }

  async create(request: CreateRubrosRubrosdialogRequest): Promise<RubrosRubrosdialogResponse> {
    // TODO: Validaciones de negocio antes de crear
    return this.gateway.create(request);
  }

  async update(id: string, request: UpdateRubrosRubrosdialogRequest): Promise<RubrosRubrosdialogResponse> {
    // TODO: Validaciones de negocio antes de actualizar
    return this.gateway.update(id, request);
  }

  async remove(id: string): Promise<DeleteResponseDTO> {
    return this.gateway.remove(id);
  }

  // TODO: Agregar métodos de negocio adicionales que combinen llamadas al gateway
}
