// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { Rubrosidomain, CreateRubrosidomain, UpdateRubrosidomain, RubrosidomainFilter, RubrosidomainPageResult } from '../../domain/model/Rubrosidomain';
import { RubrosidomainUseCase } from '../port/input/RubrosidomainUseCase';
import { RubrosidomainGatewayPort } from '../port/output/RubrosidomainGatewayPort';
import { RubrosidomainNotFoundError, RubrosidomainValidationError } from '../../domain/exception/RubrosidomainError';
import { RubrosidomainViewMapper } from '../../infrastructure/input/adapter/mapper/RubrosidomainViewMapper';

export class RubrosidomainApplicationService implements RubrosidomainUseCase {

  constructor(private readonly gatewayPort: RubrosidomainGatewayPort) {}

  async findById(id: string): Promise<Rubrosidomain> {
    if (!id) {
      throw new RubrosidomainValidationError('El ID es requerido');
    }
    const response = await this.gatewayPort.findById(id);
    if (!response) {
      throw new RubrosidomainNotFoundError(id);
    }
    return RubrosidomainViewMapper.toDomain(response);
  }

  async findAll(filter?: RubrosidomainFilter): Promise<RubrosidomainPageResult> {
    const params = filter ? RubrosidomainViewMapper.toFilterParams(filter) : undefined;
    const response = await this.gatewayPort.findAll(params);
    return RubrosidomainViewMapper.toPageResult(response);
  }

  async create(model: CreateRubrosidomain): Promise<Rubrosidomain> {
    if (!model.rubroId || model.rubroId.trim() === '') {
      throw new RubrosidomainValidationError('El código de rubro es obligatorio', 'rubroId');
    }
    if (!model.colaboradorId) {
      throw new RubrosidomainValidationError('El colaborador es obligatorio', 'colaboradorId');
    }
    if (!model.empresaId) {
      throw new RubrosidomainValidationError('La empresa es obligatoria', 'empresaId');
    }
    const request = RubrosidomainViewMapper.toCreateRequest(model);
    const response = await this.gatewayPort.create(request);
    return RubrosidomainViewMapper.toDomain(response);
  }

  async update(id: string, model: UpdateRubrosidomain): Promise<Rubrosidomain> {
    if (!id) {
      throw new RubrosidomainValidationError('El ID es requerido para actualizar');
    }
    const request = RubrosidomainViewMapper.toUpdateRequest(model);
    const response = await this.gatewayPort.update(id, request);
    return RubrosidomainViewMapper.toDomain(response);
  }

  async remove(id: string): Promise<void> {
    if (!id) {
      throw new RubrosidomainValidationError('El ID es requerido para eliminar');
    }
    await this.gatewayPort.remove(id);
  }
}
