// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

import { RubrosidomainRubrosidolistRubrosidodetail, CreateRubrosidomainRubrosidolistRubrosidodetail, UpdateRubrosidomainRubrosidolistRubrosidodetail, RubrosidomainRubrosidolistRubrosidodetailFilter, RubrosidomainRubrosidolistRubrosidodetailPageResult } from '../../domain/model/RubrosidomainRubrosidolistRubrosidodetail';
import { RubrosidomainRubrosidolistRubrosidodetailUseCase } from '../port/input/RubrosidomainRubrosidolistRubrosidodetailUseCase';
import { RubrosidomainRubrosidolistRubrosidodetailGatewayPort } from '../port/output/RubrosidomainRubrosidolistRubrosidodetailGatewayPort';
import { RubrosidomainRubrosidolistRubrosidodetailNotFoundError, RubrosidomainRubrosidolistRubrosidodetailValidationError } from '../../domain/exception/RubrosidomainRubrosidolistRubrosidodetailError';
import { RubrosidomainRubrosidolistRubrosidodetailViewMapper } from '../../infrastructure/input/adapter/mapper/RubrosidomainRubrosidolistRubrosidodetailViewMapper';

export class RubrosidomainRubrosidolistRubrosidodetailApplicationService implements RubrosidomainRubrosidolistRubrosidodetailUseCase {

  constructor(private readonly gatewayPort: RubrosidomainRubrosidolistRubrosidodetailGatewayPort) {}

  async findById(id: string): Promise<RubrosidomainRubrosidolistRubrosidodetail> {
    if (!id) {
      throw new RubrosidomainRubrosidolistRubrosidodetailValidationError('El ID es requerido');
    }
    const response = await this.gatewayPort.findById(id);
    if (!response) {
      throw new RubrosidomainRubrosidolistRubrosidodetailNotFoundError(id);
    }
    return RubrosidomainRubrosidolistRubrosidodetailViewMapper.toDomain(response);
  }

  async findAll(filter?: RubrosidomainRubrosidolistRubrosidodetailFilter): Promise<RubrosidomainRubrosidolistRubrosidodetailPageResult> {
    const params = filter ? RubrosidomainRubrosidolistRubrosidodetailViewMapper.toFilterParams(filter) : undefined;
    const response = await this.gatewayPort.findAll(params);
    return RubrosidomainRubrosidolistRubrosidodetailViewMapper.toPageResult(response);
  }

  async create(model: CreateRubrosidomainRubrosidolistRubrosidodetail): Promise<RubrosidomainRubrosidolistRubrosidodetail> {
    if (!model.rubroId || model.rubroId.trim() === '') {
      throw new RubrosidomainRubrosidolistRubrosidodetailValidationError('El código de rubro es obligatorio', 'rubroId');
    }
    if (!model.colaboradorId) {
      throw new RubrosidomainRubrosidolistRubrosidodetailValidationError('El colaborador es obligatorio', 'colaboradorId');
    }
    if (!model.empresaId) {
      throw new RubrosidomainRubrosidolistRubrosidodetailValidationError('La empresa es obligatoria', 'empresaId');
    }
    const request = RubrosidomainRubrosidolistRubrosidodetailViewMapper.toCreateRequest(model);
    const response = await this.gatewayPort.create(request);
    return RubrosidomainRubrosidolistRubrosidodetailViewMapper.toDomain(response);
  }

  async update(id: string, model: UpdateRubrosidomainRubrosidolistRubrosidodetail): Promise<RubrosidomainRubrosidolistRubrosidodetail> {
    if (!id) {
      throw new RubrosidomainRubrosidolistRubrosidodetailValidationError('El ID es requerido para actualizar');
    }
    const request = RubrosidomainRubrosidolistRubrosidodetailViewMapper.toUpdateRequest(model);
    const response = await this.gatewayPort.update(id, request);
    return RubrosidomainRubrosidolistRubrosidodetailViewMapper.toDomain(response);
  }

  async remove(id: string): Promise<void> {
    if (!id) {
      throw new RubrosidomainRubrosidolistRubrosidodetailValidationError('El ID es requerido para eliminar');
    }
    await this.gatewayPort.remove(id);
  }
}
