/**
 * Modelo de Dominio: cargaRubrosIDO.zul (cargaRubrosIDO)
 * Vertical Slice: 📋 Gestión de Rubros
 * Entidades fuente: 7
 *
 * Representa la entidad de negocio pura, sin dependencias de infraestructura.
 * Los campos deben reflejar los atributos reales del negocio.
 *
 * TODO: Copilot — Completa los atributos basándote en las entidades fuente y los schemas de la API.
 */

// Fuente: CargaMasivaIDOPageResponseDTO — Lista paginada de cargas masivas de rubros IDO
// Fuente: CargaMasivaIDOResponseDTO — Detalle de una carga masiva de rubros IDO
// Fuente: CargaMasivaIDOLineaPageResponseDTO — Lista paginada de líneas de la carga masiva
// Fuente: CargaMasivaIDOCreateDTO — Datos para iniciar una carga masiva de rubros IDO (multipart)
// Fuente: CargaMasivaIDOResultDTO — Resultado del procesamiento de la carga masiva
// Fuente: ProcesoResponseDTO — Resultado de la aprobación
// Fuente: DeleteResponseDTO — Confirmación de eliminación

// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

export interface CargarubrosidoLinea {
  iidrubrosIdoUpl?: number;
  iidrubrosIdoUp?: number;
  dfdesde?: string;
  dfhasta?: string;
  mvalor01?: number;
  mvalor02?: number;
  vidrubro?: string;
  vcedula?: string;
  itcomporta?: number;
  vcuentabanco?: string;
  lineaId?: number;
  rubroId: string;
  colaboradorId: number;
  valor?: number;
  estado?: string;
  mensaje?: string;
}

export interface Cargarubrosido {
  id: number;
  iidrubrosIdoUp?: number;
  empresaId?: number;
  rubroId: string;
  vidrubro?: string;
  estado?: string;
  ambito?: string;
  vidambito?: string;
  accion?: string;
  fechaAplica?: string;
  dfechaaplica?: string;
  pathArchivo?: string;
  empresaNombreLargo?: string;
  empresaNombreCorto?: string;
  bancoId?: string;
  rubroNombre?: string;
  usuarioIngreso?: string;
  usuarioModificacion?: string;
  fechaIngreso?: string;
  fechaModificacion?: string;
  // Legacy aliases kept for current UI compatibility.
  nombreArchivo?: string;
  fechaCarga?: string;
  usuarioCarga?: string;
  numeroRegistros?: number;
  numeroErrores?: number;
  numeroExitosos?: number;
  procesoId?: string;
  descripcion?: string;
  fechaActualizacion?: string;
}

export type CreateCargarubrosido = {
  archivo: File;
  empresaId: number;
  rubroId?: string;
  accion?: string;
  fechaAplica?: string;
  ambito?: string;
  tipoAP?: number;
  bancoId?: number;
  tipoCuenta?: string;
  tipoColaborador?: string;
  periodoInicio?: string;
  periodoFin?: string;
  descripcion?: string;
  observaciones?: string;
};

export type UpdateCargarubrosido = {
  estado?: string;
  descripcion?: string;
};

export interface CargarubrosidoFilter {
  page?: number;
  size?: number;
  empresaId?: number;
  rubroId?: string;
  estado?: string;
  sort?: string;
}

export interface CargarubrosidoPageResult {
  items: Cargarubrosido[];
  totalElements: number;
  totalPages: number;
  currentPage: number;
}

export interface CargarubrosidoLineaPageResult {
  items: CargarubrosidoLinea[];
  totalElements: number;
  totalPages: number;
  currentPage: number;
}
