// Generated by migration-flow
// Source: migration/mapping/react-domain-application-context-slice-4-consultas.json
// GeneratedAt: 2026-04-09

/**
 * Modelo de dominio para Clases de Rubro.
 * Endpoints:
 *   GET /api/v1/nomina-colaborador/clases-rubro
 *   GET /api/v1/nomina-colaborador/clases-rubro/{claseId}
 */
export interface Clasesrubro {
  id: string;
  nombre: string;
  codigo?: string;
  descripcion?: string;
  estado?: string;
}

export interface ClasesrubroFilter {
  page?: number;
  size?: number;
  search?: string;
}

export interface ClasesrubroPageResult {
  items: Clasesrubro[];
  totalElements: number;
  totalPages: number;
  currentPage: number;
}
