/**
 * Modelo de Dominio: consultaRubrosIdoList.zul (consultaRubrosIdoList)
 * Vertical Slice: 📋 Gestión de Rubros
 * Entidades fuente: 6
 *
 * Representa la entidad de negocio pura, sin dependencias de infraestructura.
 * Los campos deben reflejar los atributos reales del negocio.
 *
 * TODO: Copilot — Completa los atributos basándote en las entidades fuente y los schemas de la API.
 */

// Fuente: ConsultaRubroIDOPageResponseDTO — Lista paginada de resultados de consulta de rubros IDO
// Fuente: RubroIDOResponseDTO — Detalle del rubro IDO consultado (mismo DTO que rubros-ido)
// Fuente: ExportarConsultaIDODTO — Filtros para la exportación de consulta de rubros IDO
// Fuente: ExportarResponseDTO — Resultado de la exportación
// Fuente: CambiarEstadoIDODTO — Datos para cambiar el estado de un rubro IDO
// Fuente: DeleteResponseDTO — Confirmación de eliminación

// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

export interface Consultarubrosidolist {
  id: number;
  dfechapagocaja?: string;
  rubroId: string;
  rubroNombre?: string;
  colaboradorId?: number;
  empresaId?: number;
  localidadId?: number;
  centroCostoId?: number;
  rolId?: number;
  neroId?: number;
  tipoComportamiento: number;
  valor01?: number;
  valor02?: number;
  cartaImpresion?: number;
  flagEnvio?: number;
  generarCarta?: number;
  estadoCaja?: string;
  usuarioCaja?: string;
  vstts?: string;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
  aplicacion?: string;
  origen?: string;
  cargaUploadId?: number;
  usuarioIngreso?: string;
  fechaIngreso?: string;
  usuarioModificacion?: string;
  fechaModificacion?: string;
  nombreColaborador?: string;
  nombreRubro?: string;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export type CreateConsultarubrosidolist = {
  rubroId?: string;
  dfechapagocaja?: string;
  colaboradorId?: number;
  empresaId?: number;
  localidadId?: number;
  centroCostoId?: number;
  rolId?: number;
  neroId?: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  cartaImpresion?: number;
  flagEnvio?: number;
  generarCarta?: number;
  estadoCaja?: string;
  usuarioCaja?: string;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
};

export type UpdateConsultarubrosidolist = {
  estado?: string;
};

export interface ConsultarubrosidolistFilter {
  page?: number;
  size?: number;
  pagina?: number;
  tamanio?: number;
  rubroId?: string;
  vidrubro?: string;
  colaboradorId?: number;
  iidcolaborador?: number;
  empresaId?: number;
  iidempresa?: number;
  estado?: string;
  fechaDesde?: string;
  dfdesde?: string;
  fechaHasta?: string;
  localidadId?: number;
  iidlocalidad?: number;
  centroCostoId?: number;
}

export interface ConsultarubrosidolistPageResult {
  items: Consultarubrosidolist[];
  totalElements: number;
  totalPages: number;
  currentPage: number;
}
