// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

export interface RubrosRubrosdialog {
  idRubro: string;
  nombre: string;
  ambito?: AmbitoRubro;
  efecto?: EfectoRubro;
  observaciones?: string;
  procedimientoCalculo?: string;
  rubroHistorico?: number;
  secuenciaImpresion?: number;
  secuenciaSobregiro?: number;
  aplicaInterfaz?: boolean;
  insertaEnLote?: boolean;
  carta?: string;
  estado?: string;
  antiguedadMinima?: number;
  numAprobaciones?: number;
  numAprobacionesNoLocales?: number;
  plazoMaximo?: number;
  plazoMinimo?: number;
  montoMaximo?: number;
  verificaEndeudamiento?: boolean;
  usuarioCreacion?: string;
  fechaCreacion?: string;
  usuarioActualizacion?: string;
  fechaActualizacion?: string;
  acumulable?: boolean;
}

export type EfectoRubro = "ING" | "EGR" | "NA";

export type AmbitoRubro = "NA" | "IDO" | "PTM";

export type CreateRubrosRubrosdialog = {
  idRubro: string;
  nombre: string;
  ambito?: AmbitoRubro;
  efecto?: EfectoRubro;
  observaciones?: string;
  procedimientoCalculo?: string;
  rubroHistorico?: number;
  secuenciaImpresion?: number;
  secuenciaSobregiro?: number;
  aplicaInterfaz?: boolean;
  insertaEnLote?: boolean;
  carta?: string;
  antiguedadMinima?: number;
  numAprobaciones?: number;
  numAprobacionesNoLocales?: number;
  plazoMaximo?: number;
  plazoMinimo?: number;
  montoMaximo?: number;
  verificaEndeudamiento?: boolean;
  acumulable?: boolean;
};

export type UpdateRubrosRubrosdialog = {
  nombre?: string;
  ambito?: AmbitoRubro;
  efecto?: EfectoRubro;
  observaciones?: string;
  procedimientoCalculo?: string;
  rubroHistorico?: number;
  secuenciaImpresion?: number;
  secuenciaSobregiro?: number;
  aplicaInterfaz?: boolean;
  insertaEnLote?: boolean;
  carta?: string;
  antiguedadMinima?: number;
  numAprobaciones?: number;
  numAprobacionesNoLocales?: number;
  plazoMaximo?: number;
  plazoMinimo?: number;
  montoMaximo?: number;
  verificaEndeudamiento?: boolean;
  acumulable?: boolean;
};

export interface RubrosRubrosdialogFilter {
  page?: number;
  size?: number;
  idRubro?: string;
  nombre?: string;
  efecto?: EfectoRubro;
  ambito?: AmbitoRubro;
}

export interface RubrosRubrosdialogPageResult {
  items: RubrosRubrosdialog[];
  totalElements: number;
  totalPages: number;
  currentPage: number;
}
