/**
 * Modelo de Dominio: rubrosIDOcargaxProceso.zul (rubrosIDOcargaxProceso)
 * Vertical Slice: 📋 Gestión de Rubros
 * Entidades fuente: 6
 *
 * Representa la entidad de negocio pura, sin dependencias de infraestructura.
 * Los campos deben reflejar los atributos reales del negocio.
 *
 * TODO: Copilot — Completa los atributos basándote en las entidades fuente y los schemas de la API.
 */

// Fuente: CargaProcesoListResponseDTO — Lista de ejecuciones de carga por proceso
// Fuente: CargaProcesoResponseDTO — Detalle de carga de rubros IDO por proceso
// Fuente: CargaProcesoCreateDTO — Datos para ejecutar la carga de rubros IDO por proceso
// Fuente: ProcesoResponseDTO — Resultado de la ejecución de la carga
// Fuente: CargaProcesoUpdateDTO — Datos para actualizar la carga por proceso
// Fuente: DeleteResponseDTO — Confirmación de eliminación

// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

export interface Rubrosidocargaxproceso {
  id: number;
  iidrubrosIdocp?: number;
  iidrubrosIdo?: number;
  iidempresa?: number;
  vidrubro?: string;
  vidambito?: string;
  dfechaaplica?: string;
  usuarioingresoAu?: string;
  empresa?: string;
  fechaCarga?: string;
  cargadoPor?: string;
  registrosProcesados?: number;
  mensaje?: string;
  empresaId: number;
  rubroId: string;
  rubroNombre?: string;
  ambito?: string;
  accion?: string;
  fechaAplica?: string;
  estado?: string;
  pathArchivo?: string;
  usuarioIngreso?: string;
  fechaIngreso?: string;
  efecto?: 'ING' | 'EGR' | 'NA';
  aplicacion?: string;
  valor1?: number;
  valor2?: number;
  origen?: string;
  // Legacy aliases kept for current UI compatibility.
  procesoId?: string;
  fechaEjecucion?: string;
  numeroRegistrosCargados?: number;
  numeroErrores?: number;
  usuarioEjecucion?: string;
  descripcion?: string;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export type CreateRubrosidocargaxproceso = {
  empresaId: number;
  rubroId: string;
  accion: string;
  fechaAplica: string;
  ambito?: string;
  iidrubrosIdo?: number;
  dfechaaplica?: string;
  vidambito?: string;
  procesoId?: number;
  descripcion?: string;
};

export type UpdateRubrosidocargaxproceso = {
  accion?: string;
  fechaAplica?: string;
  ambito?: string;
  estado?: string;
};

export interface RubrosidocargaxprocesoFilter {
  page?: number;
  size?: number;
  empresaId?: number;
  rubroId?: string;
  estado?: string;
}

export interface RubrosidocargaxprocesoPageResult {
  items: Rubrosidocargaxproceso[];
  totalElements: number;
  totalPages: number;
  currentPage: number;
}
