/**
 * Modelo de Dominio: rubrosxprocesoDialog.zul (rubrosxprocesoDialog)
 * Vertical Slice: 📋 Gestión de Rubros
 * Entidades fuente: 5
 *
 * Representa la entidad de negocio pura, sin dependencias de infraestructura.
 * Los campos deben reflejar los atributos reales del negocio.
 *
 * TODO: Copilot — Completa los atributos basándote en las entidades fuente y los schemas de la API.
 */

// Fuente: RubroProcesoPageResponseDTO — Lista paginada de asignaciones rubro-proceso
// Fuente: RubroProcesoResponseDTO — Detalle de la asignación rubro-proceso
// Fuente: RubroProcesoCreateDTO — Datos para asignar un rubro a un proceso
// Fuente: RubroProcesoUpdateDTO — Datos para actualizar la asignación rubro-proceso
// Fuente: DeleteResponseDTO — Confirmación de eliminación

// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

export interface Rubrosxprocesodialog {
  id: number;
  rubroId: string;
  rubroNombre?: string;
  procesoId: number;
  procesoNombre?: string;
  secuencia?: number;
  frecuenciaEjecucion?: string;
  procedimientoCalculo?: string;
  ambitoEjecucion?: string;
  insertaEnLote?: string;
  validaPlantillaContable?: string;
  estado?: string;
  usuarioIngreso?: string;
  fechaIngreso?: string;
  usuarioModificacion?: string;
  fechaModificacion?: string;
  activo?: boolean;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export type CreateRubrosxprocesodialog = {
  rubroId: string;
  procesoId: number;
  secuencia?: number;
  frecuenciaEjecucion?: string;
  procedimientoCalculo?: string;
  ambitoEjecucion?: string;
  insertaEnLote?: string;
  validaPlantillaContable?: string;
  estado?: string;
  activo?: boolean;
};

export type UpdateRubrosxprocesodialog = {
  secuencia?: number;
  frecuenciaEjecucion?: string;
  procedimientoCalculo?: string;
  ambitoEjecucion?: string;
  insertaEnLote?: string;
  validaPlantillaContable?: string;
  estado?: string;
  activo?: boolean;
};

export interface RubrosxprocesodialogFilter {
  page?: number;
  size?: number;
  rubroId?: string;
  procesoId?: number;
}

export interface RubrosxprocesodialogPageResult {
  items: Rubrosxprocesodialog[];
  totalElements: number;
  totalPages: number;
  currentPage: number;
}
