// Generated by migration-flow
// Source: migration/plan/config.json
// GeneratedAt: 2026-03-27

export interface Rubrosidomain {
  id: number;
  dfechapagocaja?: string;
  rubroId: string;
  colaboradorId: number;
  empresaId: number;
  centroCostoId?: number;
  localidadId?: number;
  neroId?: number;
  rolId?: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  cartaImpresion?: number;
  flagEnvio?: number;
  generarCarta?: number;
  estadoCaja?: string;
  usuarioCaja?: string;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
  nombreColaborador?: string;
  nombreRubro?: string;
  fechaCreacion?: string;
  fechaActualizacion?: string;
}

export type CreateRubrosidomain = {
  dfechapagocaja?: string;
  rubroId: string;
  colaboradorId: number;
  empresaId: number;
  centroCostoId?: number;
  localidadId?: number;
  neroId?: number;
  rolId?: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  cartaImpresion?: number;
  flagEnvio?: number;
  generarCarta?: number;
  estadoCaja?: string;
  usuarioCaja?: string;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
};

export type UpdateRubrosidomain = {
  dfechapagocaja?: string;
  rubroId?: string;
  colaboradorId?: number;
  empresaId?: number;
  centroCostoId?: number;
  localidadId?: number;
  neroId?: number;
  rolId?: number;
  tipoComportamiento?: number;
  valor01?: number;
  valor02?: number;
  valor03?: number;
  cartaImpresion?: number;
  flagEnvio?: number;
  generarCarta?: number;
  estadoCaja?: string;
  usuarioCaja?: string;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
};

export interface RubrosidomainFilter {
  page?: number;
  size?: number;
  rubroId?: string;
  colaboradorId?: number;
  empresaId?: number;
  estado?: string;
  fechaDesde?: string;
  fechaHasta?: string;
}

export interface RubrosidomainPageResult {
  items: Rubrosidomain[];
  totalElements: number;
  totalPages: number;
  currentPage: number;
}
